### ISSUE TITLE
建议：能否写成Laravel package用 composer 在已有项目中安装？

### ISSUE THREAD

**Issue by guoxiangke** [WangNingkai/OLAINDEX#10]
rt

**Comment by guoxiangke** [comment]
https://laravel.com/docs/5.7/packages
https://devdojo.com/tutorials/how-to-create-a-laravel-package

**Comment by WangNingkai** [comment]
@guoxiangke 因为这个是已经写好的，目前还没有将其发布到packagist ,所以只能用git拉取下来

**Comment by WangNingkai** [comment]
@guoxiangke 后续也是可以把它 写成package的
