### ISSUE TITLE
关于images图床上传文件保存路径问题

### ISSUE THREAD

**Issue by woytu** [WangNingkai/OLAINDEX#101]
参考https://github.com/donwa/oneindex/issues/459

修改https://github.com/WangNingkai/OLAINDEX/blob/5408b477c557a5af1ecb2e10ee7ae2dd86b1873d/app/Http/Controllers/ManageController.php#L64

![image](https://user-images.githubusercontent.com/30252550/52493436-65272180-2c06-11e9-8e01-c11767d4aa94.png)

**Comment by dgfun** [comment]
赞

**Comment by WangNingkai** [comment]
有需要的话，从这里可以修改的

**Comment by CallMeSkyCN** [comment]
首先感谢WangNingkai大大的付出~ ~
再提一个咨询，关于改造现有图床为“自由上传”的咨询。现在的图床限制上传文件的类型为图片，上传容量为4M，想放开所有限制，实现自由上传。已知解除上传容量限制，可在ManageController文件修改，请问：
1、上传文件类型限制在哪里修改？
2、如需要把页面中所有涉及“图床”两个字替换为“上传”，您看能够提供思路吗？
以上，谢谢您啦！~

**Comment by woytu** [comment]
> 首先感谢WangNingkai大大的付出~ ~
> 再提一个咨询，关于改造现有图床为“自由上传”的咨询。现在的图床限制上传文件的类型为图片，上传容量为4M，想放开所有限制，实现自由上传。已知解除上传容量限制，可在ManageController文件修改，请问：
> 1、上传文件类型限制在哪里修改？
> 2、如需要把页面中所有涉及“图床”两个字替换为“上传”，您看能够提供思路吗？
> 以上，谢谢您啦！~

![image](https://user-images.githubusercontent.com/30252550/53220824-7a3d8f00-36a1-11e9-9caa-b8750598cf65.png)

# 你这个限制怎么去掉的？？？

**Comment by CallMeSkyCN** [comment]
ManageController文件中有required|max:4096 参数，但似乎我理解的有误。单纯修改required|max:4096 参数，还不能实现突破上传限制的需要

**Comment by CallMeSkyCN** [comment]
web.php 中似乎有图床对图片的check，但注释后 重启php 会500错误

**Comment by WangNingkai** [comment]
@woytu @CallMeSkyCN  
微软接口对简单文件有大小限制，最大只能4m ，过大的文件，需要分片上传  
可以参考这里 
https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online
我这里有命令行上传的大文件 
`OLAINDEX/app/Console/Commands/OneDrive/UploadFile.php`

![image](https://user-images.githubusercontent.com/23030927/53242371-7f213380-36df-11e9-973b-c09d5788f97f.png)

**Comment by CallMeSkyCN** [comment]
继续咨询您：
1、如何解除现在图床模块上传文件类型的限制？
2、将“图床”字样修改为其他文字

望您方便时，给个思路即可，谢谢啦

**Comment by WangNingkai** [comment]
@ 图片上传类型的话 修改插件drpzone 上传文件的限制
![image](https://user-images.githubusercontent.com/23030927/53296432-e1964300-3849-11e9-875c-7bc3ccd24a78.png)
![image](https://user-images.githubusercontent.com/23030927/53296433-ece96e80-3849-11e9-8962-57e4cc1a590a.png)

**Comment by CallMeSkyCN** [comment]
感谢您的回复，已解决。辛苦啦

**Comment by woytu** [comment]
### 强迫症的我受不了Chrome的自动翻译，自己手动修改`lang="en"`为`lang="zh_CN"`，如果你跟我一样可以修改一下文件中的`<html lang="en">`为`<html lang="zh_CN">`
```
\resources\views\default\about.blade.php
\resources\views\default\admin\login.blade.php
\resources\views\default\install\bind.blade.php
\resources\views\default\install\init.blade.php
\resources\views\default\layouts\admin.blade.php
\resources\views\default\layouts\main.blade.php
\resources\views\mdui\layouts\admin.blade.php
\resources\views\mdui\layouts\main.blade.php
```

**Comment by WangNingkai** [comment]
@woytu  有空我看下修改一下吧😂😂
