### ISSUE TITLE
md文件无法打开

### ISSUE THREAD

**Issue by ErichTao** [WangNingkai/OLAINDEX#103]
网站打开主页出现429错误:

Error: 22: HTTP response code said error: The requested URL returned error: 429

首页的readme.md文件无法显示
![image](https://user-images.githubusercontent.com/39548509/52646745-484c6000-2f1e-11e9-8289-376b7164ebee.png)

错误日志：
![image](https://user-images.githubusercontent.com/39548509/52646896-982b2700-2f1e-11e9-8be8-519292a1a357.png)

**Comment by WangNingkai** [comment]
请求次数过多 被微软限制了
