### ISSUE TITLE
详情页图片不显示

### ISSUE THREAD

**Issue by uubbbb** [WangNingkai/OLAINDEX#104]
如下图，在详情页中图片不显示，点击查看原图却可以弹出图片，世纪互联的，宝塔，安装步骤没出错。wiki里有图片不显示的方案，不过apache网站配置文件没有方案中的那些参数，请问该怎么解决呢？

- 操作系统版本：
- Apache/NGINX 版本：Apache 2.4.38
- PHP 版本：php7.2
- OLAINDEX 版本：release最新版
- 浏览器版本：Chromium 71.0.3578.98
![tim 20190213203706](https://user-images.githubusercontent.com/47598438/52712430-7b026100-2fcf-11e9-8335-b109af642539.png)

**Comment by WangNingkai** [comment]
此处应该是apache 配置问题 ，关闭apache图片防盗链 配置相关静态资源显示

**Comment by uubbbb** [comment]
防盗链没启用呢，伪静态就public下默认的.htaccess，怎么配置呢？

**Comment by WangNingkai** [comment]
apache 具体我也比较少用 建议google 一下 apache静态资源的配置
