### ISSUE TITLE
看图模式

### ISSUE THREAD

**Issue by Flysky12138** [WangNingkai/OLAINDEX#106]
点开看图模式罗列出的图片，滑动看下一张，显示的是第3,5,7…张图片，偶数位置的看不了

**Comment by WangNingkai** [comment]
看图模式用的插件 部分图片格式可能不受支持 也不是完全显示的是奇数张图片 看你的图片格式 此功能不太完整 慎重使用

**Comment by Flysky12138** [comment]
> 看图模式用的插件部分图片格式可能不受支持也不是完全显示的是奇数张图片看你的图片格式此功能不太完整慎重使用

不是这个意思，我说的是：看图不点开图片显示的张数没问题，但是点开后，滑动看下一张显示的是挨着的第奇数张图片，比如点开第一张，滑动看下一张就是第三张图片，第二张看不了

**Comment by WangNingkai** [comment]
这个应该就是看图插件的问题 有空我看下有没有其他插件可以较好解决这一问题

**Comment by WangNingkai** [comment]
看图模式已经调整，使用fancybox，更新后，点击目录小眼睛，左右滑动即可
