### ISSUE TITLE
使用od:cache后出现部分文件夹500

### ISSUE THREAD

**Issue by chiakge** [WangNingkai/OLAINDEX#109]
### 1. 该问题的重现步骤是什么？
使用od:cache后出现部分文件夹500
### 3. 问题出现的环境

- 操作系统版本：Debian 9 BT
- Apache/NGINX 版本：1.14
- PHP 版本：7.3
- OLAINDEX 版本：最新
- 浏览器版本：

**Comment by chiakge** [comment]
![image](https://user-images.githubusercontent.com/33163118/52974943-53136300-33fe-11e9-9cad-d5fdf98dfa50.png)

**Comment by WangNingkai** [comment]
部分缓存写入失败 目录执行相应权限 `chmod 755 -R storage`

**Comment by chiakge** [comment]
设置过了，删除缓存后问题就解决啦，应该是写入的缓存有bug

**Comment by chiakge** [comment]
![image](https://user-images.githubusercontent.com/33163118/52985648-cbdee300-342f-11e9-8131-0aadfcdf7a01.png)
![image](https://user-images.githubusercontent.com/33163118/52985667-dc8f5900-342f-11e9-8624-8af2d4466181.png)

**Comment by chiakge** [comment]
设置后是这样的

**Comment by chiakge** [comment]
发现宝塔自动新创建的缓存文件默认权限为644，有办法让他默认755吗？

**Comment by WangNingkai** [comment]
有个办法 用户权限的问题 或者你设置你个crontab 每分钟执行755
