### ISSUE TITLE
各种安装 好了 最后打开url一看空白。。

### ISSUE THREAD

**Issue by hatvgit** [WangNingkai/OLAINDEX#11]
git clone下来 都弄好了全空白。 权限都给了 chown -R www-data:www-data
日志都没有 不知道什么情况

新的代码  .env里面不用手动添加 client_id、client_secret 了吧

**Comment by WangNingkai** [comment]
数据库内的数据都有了吗？手动配置client_id、client_secret好了吗

下图内的数据库parameters里数据都有没

![image.png](https://image.ningkai.wang/item/origin/view/01HS36VAFWK2PALTLPPNGZVCJFJKGCGPXU)
