### ISSUE TITLE
部署 OLAINDEX 到 Heroku 上

### ISSUE THREAD

**Issue by xrw002** [WangNingkai/OLAINDEX#110]
git push heroku master
Counting objects: 259, done.
Compressing objects: 100% (238/238), done.
Writing objects: 100% (259/259), 514.80 KiB | 0 bytes/s, done.
Total 259 (delta 52), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> PHP app detected
remote:
remote:  !     ERROR: No 'composer.lock' found!
remote:  !
remote:  !     A 'composer.lock' file was not found in your project, but there
remote:  !     is a 'composer.json' file with dependencies inside 'require'.
remote:  !
remote:  !     The lock file is required in order to guarantee reliable and
remote:  !     reproducible installation of dependencies across platforms and
remote:  !     deploys. You must follow the Composer best practice of having
remote:  !     your lock file under version control in order to deploy. The
remote:  !     lock file must not be in your '.gitignore'.
remote:  !
remote:  !     Please perform the following steps locally on your computer to
remote:  !     resolve this issue before attempting another deploy:
remote:  !     1) remove 'composer.lock' from file '.gitignore', if present
remote:  !     2) if no 'composer.lock' exists, run 'composer update'
remote:  !     3) stage the lock file changes using 'git add composer.lock'
remote:  !     4) if you edited '.gitignore', also run 'git add .gitignore'
remote:  !     5) commit the change using 'git commit'
remote:  !
remote:  !     Please remember to always keep your 'composer.lock' updated in
remote:  !     lockstep with 'composer.json' to avoid common problems related
remote:  !     to dependencies during collaboration and deployment.
remote:  !
remote:  !     Please refer to the Composer documentation for further details:
remote:  !     https://getcomposer.org/doc/
remote:  !     https://getcomposer.org/doc/01-basic-usage.md
remote:
remote:  !     Push rejected, failed to compile PHP app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to dir-olaindex.
remote:
To https://git.heroku.com/dir-olaindex.git
 ! [remote rejected] master -> master (pre-receive hook declined)

**Comment by WangNingkai** [comment]
缺少composer.lock文件 建议仓库拉取到本地然后composer安装后再提交到heroku
