### ISSUE TITLE
429错误

### ISSUE THREAD

**Issue by LittleTurtle2333** [WangNingkai/OLAINDEX#111]
- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：7.2
- OLAINDEX 版本：3.2.1
- 浏览器版本：Chrome最新

[//]: # (如有图片请附上截图)
http://dl2.romsg.com/1.png
http://dl2.romsg.com/2.png
http://dl2.romsg.com/3.png

Get OneDrive file content error. {"code":22,"msg":"HTTP response code said error: The requested URL returned error: 429 "}
今天突然出现的问题，无法下载文件
好几个小时了，都没有恢复

**Comment by WangNingkai** [comment]
帐号被微软限制请求了 只能换账号了

**Comment by LittleTurtle2333** [comment]
那我这个整个全局管理员都boom了？？

**Comment by LittleTurtle2333** [comment]
朋友跟同域下的，也死了

**Comment by WangNingkai** [comment]
不会吧 存在滥用资源吗 可能被限制了

**Comment by LittleTurtle2333** [comment]
没有啊

**Comment by LittleTurtle2333** [comment]
就是我的用户比较多，可能一挤boom

**Comment by WangNingkai** [comment]
没有做缓存的话 每个用户访问就会请求一次， 所以 可以尝试再后台设置crontab自动定时刷新缓存 这样用户访问的是缓存 可以缓解请求压力的 避免此种情况

**Comment by LittleTurtle2333** [comment]
懂了
