### ISSUE TITLE
视频播放界面

### ISSUE THREAD

**Issue by Flysky12138** [WangNingkai/OLAINDEX#113]
不知道是不是最近你更新了视频播放的按键样式，在手机上看的话会出现错位，显示不全，个人觉得还是以前的好看，不加Unmute,Setting,Enter fullscreen这些字在上面

**Comment by WangNingkai** [comment]
可能是播放器的原因 手机端显示不友好





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by iiivii** [comment]
应该是plyr.js引用的cdn的问题吧，把
[/resources/views/default/show/audio.blade.php](https://github.com/WangNingkai/OLAINDEX/blob/master/resources/views/default/show/audio.blade.php) 
[/resources/views/default/show/dash.blade.php](https://github.com/WangNingkai/OLAINDEX/blob/master/resources/views/default/show/dash.blade.php)
[/resources/views/default/show/video.blade.php](https://github.com/WangNingkai/OLAINDEX/blob/master/resources/views/default/show/viedo.blade.php)
[/resources/views/mdui/show/audio.blade.php](https://github.com/WangNingkai/OLAINDEX/blob/master/resources/views/mdui/show/audio.blade.php)
[/resources/views/mdui/show/dash.blade.php](https://github.com/WangNingkai/OLAINDEX/blob/master/resources/views/mdui/show/dash.blade.php)
[/resources/views/mdui/show/video.blade.php](https://github.com/WangNingkai/OLAINDEX/blob/master/resources/views/mdui/show/video.blade.php)
这几个文件里的
https://cdn.jsdelivr.net/npm/plyr@3/dist/plyr.min.css 替换为 https://cdn.plyr.io/3.5.2/plyr.css
https://cdn.jsdelivr.net/npm/plyr@3/dist/plyr.min.js 替换为 https://cdn.plyr.io/3.5.2/plyr.js
https://cdn.jsdelivr.net/npm/plyr@3/dist/plyr.svg 替换为 https://cdn.plyr.io/3.5.2/plyr.svg
就行了。

**Comment by WangNingkai** [comment]
确实是这个问题，精确版本就可以解决，感谢

**Comment by iiivii** [comment]
> 确实是这个问题，精确版本就可以解决，感谢

刚刚测试了一下，使用jsdelivr压缩过的css文件和js文件会出现错位，未压缩的正常显示。

**Comment by Flysky12138** [comment]
多谢，解决了
