### ISSUE TITLE
图床上传非图片文件

### ISSUE THREAD

**Issue by Flysky12138** [WangNingkai/OLAINDEX#115]
图床上传其他文件，需要改哪些文件，怎样改呢。

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/issues/101 参考此issue内容

**Comment by Flysky12138** [comment]
`./resources/views/default`文件中改成这样
```
acceptedFiles: '*',
```
只是可以选择其他类型的文件，不能上传成功。
哪里还限制了上传类型啊

**Comment by WangNingkai** [comment]
后台的脚本文件 ，这里是限制只能上传图片文件，其他规则参考laravel 表单验证
![image](https://user-images.githubusercontent.com/23030927/54065316-37131c80-425a-11e9-90ac-bacc27446269.png)
![image](https://user-images.githubusercontent.com/23030927/54065318-42fede80-425a-11e9-9f68-bfae060eb39f.png)
