### ISSUE TITLE
音频播放器的倍速选项无法完整显示

### ISSUE THREAD

**Issue by rangerwill** [WangNingkai/OLAINDEX#117]
音频播放器的倍速调节设置在手机Chrome中，慢倍速选项被完全遮挡。在电脑Chrome中，只能显示0.75倍速选项。
试着换了好几种主题，没有改观。

![image](https://user-images.githubusercontent.com/19543803/53572336-f8b89600-3ba5-11e9-957a-362bf46430f8.png)
![image](https://user-images.githubusercontent.com/19543803/53572488-4d5c1100-3ba6-11e9-9bb0-8ceebf65e07e.png)

**Comment by WangNingkai** [comment]
这个问题确实存在，我调整下页面好了
