### ISSUE TITLE
JS CDN 失效

### ISSUE THREAD

**Issue by vcheckzen** [WangNingkai/OLAINDEX#118]
### 1. 该问题的重现步骤是什么？
CDN 失效，导致加载任何页面非常缓慢
### 2. 你期待的结果是什么？实际看到的又是什么？
本地集成，或使用可靠 CDN
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx 1.14
- PHP 版本：7.2
- OLAINDEX 版本：3.2.1
- 浏览器版本：Chrome 72

[//]: # (如有图片请附上截图)

失效链接如下：
https://cdn.jsdelivr.net/npm/popper.js@1.0.1/dist/umd/popper.min.js

另外 googleapis 和 gstatic 链接同样存在上述问题

**Comment by chiakge** [comment]
还是把所有js内置吧

**Comment by WangNingkai** [comment]
@vcheckzen @vcheckzen 上午已经将cdn源换为loli.net  内置的太占用空间 ，有考虑重构直接全部打包

**Comment by lukemin** [comment]
内置好点，要不加选项，不在乎那点空间

**Comment by WangNingkai** [comment]
@lukemin 肯定内置好点的 我打包优化下

**Comment by WangNingkai** [comment]
Python这一块我也不太熟悉，不过链接过期是由于token过期，是目前的限制。可以使用永久下载直链试试
