### ISSUE TITLE
加快在线视频缓冲速度的可能方法

### ISSUE THREAD

**Issue by vcheckzen** [WangNingkai/OLAINDEX#119]
### 1. 该问题的重现步骤是什么？
在线视频缓冲缓慢，使用 potplay 也卡成 ppt
### 2. 你期待的结果是什么？实际看到的又是什么？
流畅观看
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.14
- PHP 版本：7.2
- OLAINDEX 版本：3.2.1
- 浏览器版本：Chrome 72

[//]: # (如有图片请附上截图)

---

目前使用一个 python 分段多线程下载工具，搭配 mpv 可以流畅播放，在此分享给大家，同时希望作者将其用 js 实现，详情移步 [OlaindexPlayer](https://github.com/vcheckzen/video-funnel)

**Comment by sxxcb** [comment]
看的一头雾水，只能希望作者加上功能了

**Comment by vcheckzen** [comment]
@WangNingkai  这种视频下载的 [链接](https://onedroptbsteduau-my.sharepoint.com/personal/102419_onmicrosoft_net/_layouts/15/download.aspx?UniqueId=7c73e7a7-47f6-4ad2-8cf5-56625654a438&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvb25lZHJvcHRic3RlZHVhdS1teS5zaGFyZXBvaW50LmNvbUAxNDY3ZDZhOS1hZjc0LTRmNDUtOGE2NC1jYzg3NzU2Nzg1MWUiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNTUxNTkzNzk3IiwiZXhwIjoiMTU1MTU5NzM5NyIsImVuZHBvaW50dXJsIjoiVEVIMm1pUmJEOG9FZGVWYnNLVGlQeldmQ2p0Z0NRS3dUS3BpQ1BDY1M1ST0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE2MiIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiWXpVelltUXhZalV0TXpBMFpDMDBabVpoTFRreE9Ea3RZelE1TkRSak16WmtOR1kwIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik1EYzRaakkxTmpjdFltRTNNUzAwTjJZNExXRmtZak10TURrMU9HSmlPR1F6TUdOaCIsImFwcF9kaXNwbGF5bmFtZSI6Ik9MQUlOREVYIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiNDE0MTUyNzktNzBjOS00N2I3LThmOGItZjUwODk0MTFhMjFiIiwidGlkIjoiMTQ2N2Q2YTktYWY3NC00ZjQ1LThhNjQtY2M4Nzc1Njc4NTFlIiwidXBuIjoiMTAyNDE5QG9ubWljcm9zb2Z0Lm5ldCIsInB1aWQiOiIxMDAzM0ZGRjk0RjY3NjczIiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzNmZmY5NGY2NzY3M0BsaXZlLmNvbSIsInNjcCI6ImFsbGZpbGVzLndyaXRlIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.dHJjTnB0RmxlbGQwcGhVdTN3eHlvSFZZZjJ5azhmczJ6SlBEZHNLQnJOVT0&ApiVersion=2.0) 一个小时会失效，导致在线播放到 1h 就无法播放了，请问有办法延长 `onedrive token` 时间吗

`The access token has expired. It's valid from '3/3/2019 6:16:37 AM' and to '3/3/2019 7:16:37 AM'.`

![image](https://user-images.githubusercontent.com/18008498/53693774-d27e3a80-3ddf-11e9-9a4c-273be3d340a1.png)

**Comment by WangNingkai** [comment]
Python这一块我也不太熟悉，不过链接过期是由于token过期，是目前的限制。可以使用永久下载直链试试

**Comment by vcheckzen** [comment]
> Python这一块我也不太熟悉，不过链接过期是由于token过期，是目前的限制。可以使用永久下载直链试试

请问微软是否提供了自定义 token 时长的 api 那，目前只有 1h 和永久链接两种吗

**Comment by WangNingkai** [comment]
@vcheckzen token是你认证授权的，时间只有一个小时，目前的话过期要刷新token，永久的需要自己转换

**Comment by vcheckzen** [comment]
> @vcheckzen token是你认证授权的，时间只有一个小时，目前的话过期要刷新token，永久的需要自己转换

好的，谢谢

**Comment by sxxcb** [comment]
> @vcheckzen token是你认证授权的，时间只有一个小时，目前的话过期要刷新令牌，永久的需要自己转换

作者大大，这个功能能集中到olaindex吗

**Comment by mqdlzh** [comment]
问一下大佬，永久下载链接怎么转啊？在onedrive分享中选择链接分享（不需要登入）的链接是一个网页而不是文件本身。
