### ISSUE TITLE
文件名显示问题

### ISSUE THREAD

**Issue by m1911** [WangNingkai/OLAINDEX#12]
现在的文件名是这样/item/01XKOG6HIRSSOZIMCLNFEJ5JBRNOMZIMTQ

能改成，和上传文件名一样的格式吗 不然wget 下载不了

**Comment by m1911** [comment]
@WangNingkai 
这个 会解决吗？

**Comment by WangNingkai** [comment]
@m1911 这个以前出过问题，无法解析部分结尾的文件，会出错。 我看下能不能兼容一下

**Comment by m1911** [comment]
@WangNingkai 
我看https://github.com/donwa/oneindex  他的演示都是用的文件名字

**Comment by WangNingkai** [comment]
@m1911 php结尾的会报错

**Comment by m1911** [comment]
@WangNingkai 
https://xn.tn/one.php  他这个我看可以下 直接点击是把代码显示出来了 点下载就可以了。

对了还有你那个php扩展 得有fileinfo 这个不然安装报错 军哥的php 这个默认是不开启的

**Comment by WangNingkai** [comment]
@m1911 laravel的框架和oneindex本身就不一样，两者路由不同，解析也不同，php的扩展安起来我是比较简单的

**Comment by WangNingkai** [comment]
@m1911 我环境机没有特意安装fileinfo，麻烦问一下，报错显示什么，哪一个扩展需要fileinfo

**Comment by m1911** [comment]
@WangNingkai 
composer install -vvv  在这一步 就会报错了

我昨晚就是用lnmp.org 军哥的 会报错

**Comment by m1911** [comment]
@WangNingkai 
应该就是这两个包，我看你标注了 基本没问题了

**Comment by WangNingkai** [comment]
@m1911  dev开发版 已解决 wget 文件名不显示的问题，我重构了路径显示

**Comment by m1911** [comment]
@WangNingkai 
https://dev.ningkai.wang/show/file/reward.php  php 是打不开的
https://dev.ningkai.wang/show/file/sqlite-dll-win32-x86-3250200.zip  直接500

**Comment by WangNingkai** [comment]
@m1911 php文件结尾，nginx服务器自动解析了，这个需要配置以下的，zip结尾的文件无法显示，这里我没有加限制，用download可以下载下来的

**Comment by WangNingkai** [comment]
https://dev.ningkai.wang/download/file/sqlite-dll-win32-x86-3250200.zip

**Comment by m1911** [comment]
@WangNingkai  现在测试 是都可以下载了
