### ISSUE TITLE
萌新问个缓存问题，每隔一段时间必须要手动刷新缓存一次？

### ISSUE THREAD

**Issue by sxxcb** [WangNingkai/OLAINDEX#120]
用的是默认缓存。后台设置的是缓存10分钟。根据帮助文档设置了* * * * * /php/bin/path/php /you/site/path/artisan schedule:run >> /dev/null 2>&1 &
但是返回的是[1] 26212  。
就是不知道这个命名执行成功了没有，求帮助。

**Comment by WangNingkai** [comment]
这个是后台的定时命令，类似linux的crontab，里面包括两条命令，每10分钟刷新缓存，每30分钟刷新token

**Comment by sxxcb** [comment]
> 这个是后台的定时命令，类似linux的crontab，里面包括两条命令，每10分钟刷新缓存，每30分钟刷新token

我就是想知道我那个有没有设置成功？

**Comment by WangNingkai** [comment]
一般设置了没有报错，基本上没有问题的
