### ISSUE TITLE
README.md文件的[TOC]目录没法预览

### ISSUE THREAD

**Issue by 1349422030** [WangNingkai/OLAINDEX#121]
如题，[TOC]是markdown的目录链接，但是在我的网页上没有解析成链接，效果如图
![default](https://user-images.githubusercontent.com/35253997/53739014-ba83e500-3ecb-11e9-994f-b0c479e5d6fb.png)

对了，还有写的脚注也没有渲染出来😂

**Comment by WangNingkai** [comment]
使用的是 https://github.com/erusev/parsedown 的markdown 解析，目前支持简单的markdown。如果想要更多功能可自行替换
