### ISSUE TITLE
功能请求 未来能否考虑加入更复杂的目录（文件）访问控制

### ISSUE THREAD

**Issue by CallMeSkyCN** [WangNingkai/OLAINDEX#122]
目前通过/  +  加密目录列表，已可以做到初步文件的访问控制（不显示目录内的文件）

未来能否加入更复杂的目录（文件）访问控制，即：
1、对文件，可实现目录内不显示某个文件；
2、对目录，可实现精确屏蔽某个目录，使其不出现在页面

------------------------------
当前对文件，要么都显示、要么都不显示
/下载/1.txt
/下载/2.txt
/下载/3.txt

未来
/下载/1.txt
/下载/2.txt（仅管理员可见）
/下载/3.txt

------------------------------
对目录，目前全部都会列出
/下载/Movie
/下载/Music
/下载/Hotxxx

未来
/下载/Movie
/下载/Music
/下载/Hotxxx（仅管理员可见）

**Comment by WangNingkai** [comment]
功能上可以实现这个需求挺好，值得考虑

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/releases/tag/v4.0_pre_2
