### ISSUE TITLE
AADSTS90102: 'redirect_uri' value must be a valid absolute Uri.

### ISSUE THREAD

**Issue by dollarkillerx** [WangNingkai/OLAINDEX#123]
### 1. 该问题的重现步骤是什么？
我套用了一层cloudflare dns接入 SSL状态 强制https http自动转https 简易全程https
宝塔上的httpsLet's Encrypt免费证书 强制https
### 2. 你期待的结果是什么？实际看到的又是什么？
AADSTS90102: 'redirect_uri' value must be a valid absolute Uri.
![](https://upload-images.jianshu.io/upload_images/2489344-da8e44ca60334704.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![](https://upload-images.jianshu.io/upload_images/2489344-13db849b51a9757c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
### 3. 问题出现的环境

- 操作系统版本：centos7.5
- Apache/NGINX 版本：ngingx1.15
- PHP 版本：7.2
- OLAINDEX 版本：v3.2.1
- 浏览器版本：chrmoe
- 面板 宝塔

[//]: # (如有图片请附上截图)
AADSTS90102: 'redirect_uri' value must be a valid absolute Uri.

**Comment by WangNingkai** [comment]
我看到你填写的回调地址没有加协议，请求回调必须带协议

**Comment by dollarkillerx** [comment]
您好添加协议返回
Error: 401: HTTP/1.1 401 Unauthorized

![](https://upload-images.jianshu.io/upload_images/2489344-bfd5ce91ac38c3d1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/2489344-6112a1d55d729dfa.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by WangNingkai** [comment]
确保国内版本的 client配置正确，国内版和国外的版本不一样
