### ISSUE TITLE
如何批量导出下载链接？

### ISSUE THREAD

**Issue by 1349422030** [WangNingkai/OLAINDEX#125]
就怎样才能导出一个文件夹下所有文件的下载链接供批量下载？

**Comment by SsorryQaQ** [comment]
+1 怎么批量下载呢

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/54504609-4b989880-496f-11e9-979d-d38c67b17b58.png)
![image](https://user-images.githubusercontent.com/23030927/54504660-797ddd00-496f-11e9-9903-1fc2afa39878.png)


**目前存在导出文件夹内的文件链接 登陆后 点击导出直链就可以了**

**Comment by SsorryQaQ** [comment]
啊..如果只是游客,可以批量下载吗

**Comment by SsorryQaQ** [comment]
> ![image](https://user-images.githubusercontent.com/23030927/54504609-4b989880-496f-11e9-979d-d38c67b17b58.png)
> ![image](https://user-images.githubusercontent.com/23030927/54504660-797ddd00-496f-11e9-9903-1fc2afa39878.png)
> 
> **目前存在导出文件夹内的文件链接 登陆后 点击导出直链就可以了**
啊..如果只是游客,可以批量下载吗

**Comment by 1349422030** [comment]
同样，是否可以把导入下载链接这个地方放在/admin界面中的一个选项，让管理员自行选择能否开放游客批量下载

还有图床上传限制能否也放在设置里面呢😂

不然每次git pull前都要git reset --hard，更新后还要再去改一遍配置文件挺不方便的😂

**Comment by WangNingkai** [comment]
好的 回头在后台添加可选项 使用批量下载

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/ac1ec22791a2845b174fc9e536552b2638ed15fb
