### ISSUE TITLE
世纪互联版出现Error: 22: HTTP response code said error: The requested URL returned error: 429

### ISSUE THREAD

**Issue by uubbbb** [WangNingkai/OLAINDEX#126]
用的世纪互联版，之前安装之后一些都正常，最近打开出现Error: 22: HTTP response code said error: The requested URL returned error: 429

不知道是什么原因，没有动过。

- 操作系统版本：
- Apache/NGINX 版本：apache2.4.38
- PHP 版本：php7.2
- OLAINDEX 版本：2月13下载的
- 浏览器版本：Chromium 71.0.3578.98

![TIM截图20190318110544](https://user-images.githubusercontent.com/47598438/54504450-ab427400-496e-11e9-8792-92b29121011f.png)

**Comment by uubbbb** [comment]
后台显示也正常
![TIM截图20190318111340](https://user-images.githubusercontent.com/47598438/54504514-e775d480-496e-11e9-87b6-52581e6fc3d2.png)

**Comment by WangNingkai** [comment]
账号部分接口请求权限被限制 应该是缓存设置不够 或者后台没有设置定时刷新缓存。微软判定此账号请求滥用，封了接口。换账号就可以了

**Comment by coyzjt** [comment]
> 账号部分接口请求权限被限制 应该是缓存设置不够 或者后台没有设置定时刷新缓存。微软判定此账号请求滥用，封了接口。换账号就可以了

作者你好，我也是世纪互联版本，但是最近文件都无法下载了，是被封了还是API变动导致的？
<img width="650" alt="QQ20190318-164755@2x" src="https://user-images.githubusercontent.com/5688203/54517895-e27c4980-499d-11e9-97cc-e992fe830fa1.png">

**Comment by WangNingkai** [comment]
帐号api访问权限被封堵了

**Comment by qiuye8023** [comment]
@@@@@@@@@请问公共账号什么时候恢复使用，自己申请账号总是提示“我们无法完成你的请求”，地址栏反馈“...invalid_request&error_description..."，谢谢。

**Comment by uubbbb** [comment]
大文件上群晖，小文件放七牛或者直接放服务器上，这些东西都不靠谱，最先用的oneindex，国际版账号被封了，现在用OLAINDEX，世纪互联版的账号也凉了，都不可靠，还是自己搭建吧

**Comment by WangNingkai** [comment]
@uubbbb 国内e1总帐号由于大家的活跃，被封了。 目前防止封禁的方法 有几个 ，1.通过olaindex 设置定时刷新缓存 防止不断发起请求 2.购买正规世纪互联帐号，经咨询接口访问过多，会被短暂限制 但是30分钟后会被解封。3.在访问列表加入加密访问，限制访问量
