### ISSUE TITLE
安装onedrive默认排序

### ISSUE THREAD

**Issue by yyaix** [WangNingkai/OLAINDEX#129]
谢谢大佬提供如此优秀的程序给我们使用，请问怎么修改才能变回onedrive默认的排序？或者默认文件夹排在前面？

**Comment by yyaix** [comment]
![TIM截图20190328123914.png](https://i.loli.net/2019/03/28/5c9c5052ebce7.png)
现在默认的就是这种排序，找文件夹很难受。。。。。

**Comment by WangNingkai** [comment]
昨天已经更新，添加了前端排序， 默认的是微软的排序。这里可以修改排序
![image](https://user-images.githubusercontent.com/23030927/55130832-59140680-5157-11e9-83a1-8c4ab917d569.png)
![image](https://user-images.githubusercontent.com/23030927/55130879-76e16b80-5157-11e9-9d54-6b19d4555a4e.png)

**Comment by yyaix** [comment]
> 昨天已经更新，添加了前端排序， 默认的是微软的排序。这里可以修改排序
> ![image](https://user-images.githubusercontent.com/23030927/55130832-59140680-5157-11e9-83a1-8c4ab917d569.png)
> ![image](https://user-images.githubusercontent.com/23030927/55130879-76e16b80-5157-11e9-9d54-6b19d4555a4e.png)

大佬，这是你的站点，（https://dev.ningkai.wang/home/images?page=2）
![TIM截图20190328125452.png](https://i.loli.net/2019/03/28/5c9c53b9bc50b.png)
在微软里面应该是文件夹排在前面的吧？

**Comment by WangNingkai** [comment]
这个是微软接口传过来的默认排序 有时间我把这一块优化下

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/ef84f6a88490cebefb94e9fd92eac4c8d0b1f4dc
