### ISSUE TITLE
nginx一定要配https么

### ISSUE THREAD

**Issue by linux52** [WangNingkai/OLAINDEX#13]
弄docker 了  有点搞不明白一定要配ssl么 就卡在最后了

docker pull linux52/olaindex
[https://github.com/linux52/olaindex-docker/blob/master/Dockerfile](url) 
这里是Dockerfile 
[https://github.com/linux52/olaindex-docker/blob/master/default.conf](url)
default.conf

有什么法子呢

**Comment by linux52** [comment]
刚刚 用cloudflare 把域名强制https 就成功了唉  
[https://one.kefu.tw/](url) 
这个绑定真蛋痛 最好写成oneindex 那个共用认证域名

**Comment by WangNingkai** [comment]
@linux52 其实现在的话https比较普及，微软强制https 的，oneindex使用的公用跳转，我不太清楚他那边怎么实现的，不过能集成docker很不错。

**Comment by WangNingkai** [comment]
@linux52 安装流程相对简化了一些

**Comment by linux52** [comment]
问题 又来了 图床上传 显示出错 但是实际图片查看onedrive 是有的。。
![2.JPG](http://one.kefu.tw/item/origin/view/01UET5VIAZRLMSZFSIL5E2NAHM63XRFMIE)

**Comment by linux52** [comment]
可以了
<img src="http://one.kefu.tw/item/origin/view/01UET5VIBVP6TSRM66SRCY2BSMT2CENWPC" alt="1.JPG" title="1.JPG" />

**Comment by WangNingkai** [comment]
@linux52 不应该啊 这个问题我还没遇见过

**Comment by WangNingkai** [comment]
可以看一下控制台upload返回的参数

**Comment by linux52** [comment]
缓存问题 等会就好用了 等代码稳定了 我再把docker弄下 感觉 nginx配制要把ssl加上 强行80跳转到443

**Comment by WangNingkai** [comment]
@linux52 我看了代码刚要说 这个需要加强https强制跳转 我这个安装流程可以再优化下的

**Comment by linux52** [comment]
环境太多了 还想撸到now.sh 一看只有100M 空间  docker弄下来 200多M 撸不了

**Comment by WangNingkai** [comment]
@linux52 laravel的依赖较多 个人还是觉得搭建到独立服务器比较好些，占用也不太大，不过安装起来对于不太懂的人也比较难了

**Comment by linux52** [comment]
多查资料 这个安装环境都有现成的  先这么弄着吧 懒了 哈哈
nginx +php 环镜弄好 
apt-get install composer -y 几步就弄好了

**Comment by MMBBao** [comment]
> 弄docker了有点搞不明白一定要配ssl么就卡在最后了
> 
> docker pull linux52 / olaindex 
> [https://github.com/linux52/olaindex-docker/blob/master/Dockerfile](url)
> 这里是Dockerfile 
> [https://github.com/linux52/olaindex-docker/blob/master/default.conf](url)
> 默认。 CONF
> 
> 有什么法子呢

大哥，能说说怎么用docker装最新版的Olaindex吗？
