### ISSUE TITLE
mdui和default两个模式是不是功能有区别？

### ISSUE THREAD

**Issue by qiuye8023** [WangNingkai/OLAINDEX#130]
mdui主题模式文件后面没有预览/下载/编辑按钮，主页没有图床和管理按钮（已登录）右上角还没有搜索功能，后台左上角“OLAINDEX”不能更改，不知道是没设置好还是mdui的确没有这些功能。

**Comment by WangNingkai** [comment]
部分功能确实没有，我也在完善。图床和搜索功能是有的，搜索在后台，图床根据路径来看的
