### ISSUE TITLE
音频播放器的倍速选项没有了

### ISSUE THREAD

**Issue by rangerwill** [WangNingkai/OLAINDEX#132]
音频播放器的倍速设置没有了

这个在听速度较快或者较慢的听力文件时还是很有用的

![image](https://user-images.githubusercontent.com/19543803/55532692-6eea7400-56e1-11e9-8bcf-4f6b93a8647e.png)

**Comment by WangNingkai** [comment]
更新过后的播放器确实没有倍速的功能了，不过这一块可以根据自己的需求更改 或者修改威远县版本
