### ISSUE TITLE
图床有没有可能支持复制粘贴上传？

### ISSUE THREAD

**Issue by 1349422030** [WangNingkai/OLAINDEX#134]
有没有可能做到像github这样可以直接粘贴剪切板的图片上传到图床？因为有时候我需要上传的是截图，然后还要保存到本地再上传

**Comment by WangNingkai** [comment]
之后会加上的

**Comment by WangNingkai** [comment]
@1349422030 已更改上传组件为 filepond https://github.com/WangNingkai/OLAINDEX/commit/47215cb3423f39d43e345ac2a579b216f1f995ad 支持截图复制上传
