### ISSUE TITLE
cloudfoundry support

### ISSUE THREAD

**Issue by landall** [WangNingkai/OLAINDEX#135]
是否可以支持cloudfoundry等PaaS服务（也就是没有本地文件系统，只能用SQL或者JSON数据库）的服务。我现在想将olaindex部署到ibm cloud lite上去，上边只支持数据库保存持久数据（类似于新浪云）。

**Comment by WangNingkai** [comment]
将配置文件持久化保存

**Comment by landall** [comment]
没用到其他临时存储么？ibm cloud好像没任何临时磁盘空间


发自我的iPhone

------------------ Original ------------------

**Comment by WangNingkai** [comment]
之前的配置是支持保存到数据库里面的 但是需要额外的数据库保存，我就改为本地文件系统保存了，改天有空新开个分支，支持下数据库存储数据

**Comment by landall** [comment]
感觉直接抽象个配置加载器让用户安装时自己改类名似乎就可以了。基本安装环境也就三种了，虚拟沙箱+数据库，shell完整权限，ftp上传+数据库


发自我的iPhone

------------------ Original ------------------

**Comment by WangNingkai** [comment]
近期准备优化下 支持文件存储和数据库存储
