### ISSUE TITLE
请问是否有可能实现下载文件夹

### ISSUE THREAD

**Issue by vcheckzen** [WangNingkai/OLAINDEX#136]
如题

**Comment by lonelyevil** [comment]
如果说是从od服务器下载的话，不可
如果从部署的服务器下载的话，可
如果说你接受生成一个链接到另外的页面下载的话，可

**Comment by vcheckzen** [comment]
> 如果说是从od服务器下载的话，不可
> 如果从部署的服务器下载的话，可
> 如果说你接受生成一个链接到另外的页面下载的话，可

从 ONEDRIVE 网页版，选择分享链接，提示被 IT 管理员限制，没有权限，这样是不是就不能下载文件夹了
