### ISSUE TITLE
The Process class relies on proc_open, which is not available on your PHP installation.

### ISSUE THREAD

**Issue by Ice-Hazymoon** [WangNingkai/OLAINDEX#137]
### 1. 该问题的重现步骤是什么？

宝塔面板，按照教程步骤安装
[https://imwnk.cn/article/104](https://imwnk.cn/article/104)

### 2. 你期待的结果是什么？实际看到的又是什么？

![image](https://user-images.githubusercontent.com/25239977/56418282-0696b780-62c9-11e9-805c-90deeed89dec.png)

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Nginx 1.15.6
- PHP 版本：7.3
- OLAINDEX 版本：bf0680e865244e2698b628bb92f62ec04e265d5b
- 浏览器版本：Chromium 72.0.3626.121

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/56428053-9f8cf900-62f0-11e9-8fa0-9374920d78ea.png)

这里的PHP禁用函数没有关闭

**Comment by Ice-Hazymoon** [comment]
`exec`、`shell_exec`、`proc_open` 这三个函数宝塔默认关闭，我安装的时候已经将他们从禁用列表里删除了，但是依旧出现上述的错误

**Comment by WangNingkai** [comment]
检查下命令行PHP环境是否一致

**Comment by Ice-Hazymoon** [comment]
谢谢，解决了，默认php版本和网站的不对应
