### ISSUE TITLE
file_put_contents(./composer.lock): failed to open stream: Permission denied 

### ISSUE THREAD

**Issue by anglabace** [WangNingkai/OLAINDEX#138]
composer install -vvv  执行这个时候
 [ErrorException]                                                              
  file_put_contents(./composer.lock): failed to open stream: Permission denied 
提示这个错误

- 操作系统版本：centos7
- Apache/NGINX 版本：14.2
- PHP 版本：7.1

**Comment by WangNingkai** [comment]
确保目录权限，需要添加写入权限

**Comment by anglabace** [comment]
给了777哈

**Comment by WangNingkai** [comment]
文件目录无法写入 composer.lock 文件 肯定是权限问题 ，请仔细检查
