### ISSUE TITLE
加密的方法有点没看懂啊，请教。

### ISSUE THREAD

**Issue by hyy34** [WangNingkai/OLAINDEX#139]
比如，我想机密根目录下的qwer121文件夹，应该如何操作？

**Comment by hyy34** [comment]
右上角没有加密的选项啊。

**Comment by hyy34** [comment]
后台加密里 添加   /qwer121/  保存？然后再如何操作？？

**Comment by hyy34** [comment]
比如密码设置为121 那么后台加密那写
qwer121 121,
是这样吗？但是不好使啊。

**Comment by WangNingkai** [comment]
`/qwer121 121,` 这种方式是正确的 但是加密是对用户的，登陆后台不会加密的，退后台就可以了

**Comment by hyy34** [comment]
> `/qwer121 121,` 这种方式是正确的 但是加密是对用户的，登陆后台不会加密的，退后台就可以了

OK,测试了,对劲。
