### ISSUE TITLE
路径中含有空格应该如何加密

### ISSUE THREAD

**Issue by Ice-Hazymoon** [WangNingkai/OLAINDEX#140]
比如有需要加密一个路径 `/a/bb cd` ，但是路径内包含空格，设置以后会把 `/a/bb` 和 `/cd` 目录给加密了

- 操作系统版本：
- Apache/NGINX 版本：Nginx 1.15.6
- PHP 版本：7.3
- OLAINDEX 版本：bf0680e865244e2698b628bb92f62ec04e265d5b
- 浏览器版本：Chromium 72.0.3626.121

**Comment by WangNingkai** [comment]
这是个已存在的问题

**Comment by WangNingkai** [comment]
新版加密已调整 @Ice-Hazymoon
