### ISSUE TITLE
怎么让文件夹排在前面呢

### ISSUE THREAD

**Issue by anadano** [WangNingkai/OLAINDEX#142]
### 2. 你期待的结果是什么？实际看到的又是什么？

能不能让文件夹排在前面
然后能不能指定一页里面项目的个数
能不能显示当前所处页的页码

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/56900172-c48b2400-6ac7-11e9-92c8-c52ad2d3be9b.png)
第一处已调整
https://github.com/WangNingkai/OLAINDEX/commit/ef84f6a88490cebefb94e9fd92eac4c8d0b1f4dc
