### ISSUE TITLE
如何修改默认的 域名/home 为根目录？

### ISSUE THREAD

**Issue by mokedc** [WangNingkai/OLAINDEX#143]
之前一直在用Oneindex和PyOne 现在换到Olaindex 
因为链接上有了个/home 很多原先的链接现在直接404
因为在很多地方都有 要改的话很麻烦

**Comment by WangNingkai** [comment]
默认的话 home 是无法去除的  此处home 是为了区别于其他路径

**Comment by z919126592** [comment]
那么可以用跳转之类的方式把/home下的链接重定向到/吗
