### ISSUE TITLE
设置Redis后出错

### ISSUE THREAD

**Issue by z919126592** [WangNingkai/OLAINDEX#144]
在.env中将files改成redis 重新刷新缓存后直接报错 页面500
报错信息：
 Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Predis\Client' not found

  at /www/wwwroot/pans.space/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php:25
    21|         $formattedOptions = array_merge(
    22|             ['timeout' => 10.0], $options, Arr::pull($config, 'options', [])
    23|         );
    24|
  > 25|         return new PredisConnection(new Client($config, $formattedOptions));
    26|     }
    27|
    28|     /**
    29|      * Create a new clustered Predis connection.

  Exception trace:

  1   Illuminate\Redis\Connectors\PredisConnector::connect(["127.0.0.1", "6379"], [])
      /www/wwwroot/pans.space/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php:98

  2   Illuminate\Redis\RedisManager::resolve("cache")
      /www/wwwroot/pans.space/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php:79

  Please use the argument -v to see more details.

**Comment by WangNingkai** [comment]
这里因该是没有安装 `predis` 扩展 ，手动执行 `composer require predis/predis` 安装

**Comment by z919126592** [comment]
谢谢 已经刷新成果
