### ISSUE TITLE
使用任务调度器后网站500，缓存写入有bug

### ISSUE THREAD

**Issue by dteen** [WangNingkai/OLAINDEX#145]
### 1. 该问题的重现步骤是什么？
执行任务调度器  php /you/site/path/artisan schedule:run >> /dev/null 2>&1 &

### 2. 你期待的结果是什么？实际看到的又是什么？
理应正常刷新缓存，实际网站500

### 3. 问题出现的环境
操作系统版本：centos7.6 
Apache/NGINX 版本：1.14
PHP 版本：7.2
OLAINDEX 版本：最新
---------------

经过排查发现经定时任务刷新出来的缓存，全部为 root权限，会造成网站无法读取的bug..

https://ae01.alicdn.com/kf/HTB1APMhT4jaK1RjSZFAq6zdLFXao.jpg

**Comment by Zxilly** [comment]
这是宝塔的锅
使用sudo控制，以www用户执行就OK

**Comment by WangNingkai** [comment]
可以更改缓存为redis 或者 memcached
