### ISSUE TITLE
使用heroku搭建时，.env内没有APP_KEY后的参数

### ISSUE THREAD

**Issue by royccg** [WangNingkai/OLAINDEX#147]
### 1. 该问题的重现步骤是什么？
使用heroku搭建时，设置 APP key时，.env中的APP_KEY后面没有参数。并且使用php artisan key:generate也不能成功生成key，其中显示PHP Warning:  require(*******/vendor/autoload.php
)，即autoload.php文件缺失。
### 2. 你期待的结果是什么？实际看到的又是什么？
希望能通过php artisan key:generate 生成key
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Apache24
- PHP 版本：php-7.3.5
- OLAINDEX 版本：最新的
- 浏览器版本：chrome

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/44716144/57966111-6a6fd700-7980-11e9-948d-cc410e444242.png)

**Comment by dongdongGit** [comment]
composer install

**Comment by royccg** [comment]
> composer install

没用啊？ 还是在php artisan key：generate 时报错 
并且 .env 文件内 app_key后还是没有参数

**Comment by WangNingkai** [comment]
heroku 文件不保存 项目内的配置文件，建议在heroku控制台配置具体的参数
