### ISSUE TITLE
能否出一个安装OLAINDEX详细的教程或视频。

### ISSUE THREAD

**Issue by ACGTe** [WangNingkai/OLAINDEX#148]
如题，希望大佬能出一个教程，对我这个刚入Linux宝塔面板坑来说有点难，我很想用OLAINDEX所以花了一整天的时间研究但老是出错24,,403,404,500等问题。
网上也有一些教程，按着做也会出错。

**Comment by WangNingkai** [comment]
建议仔细按照wiki步骤安装，一般问题不大，具体操作问题可在此提issue
