### ISSUE TITLE
宝塔安装，每次到输入域名回车都会报错

### ISSUE THREAD

**Issue by 1181590332** [WangNingkai/OLAINDEX#151]
Password：[ 12345678 ]

   Symfony\Component\Process\Exception\LogicException  : The Process class relies on proc_open, which is not available on your PHP installation.

  at /www/wwwroot/smloli.xyz/vendor/symfony/process/Process.php:143
    139|      */
    140|     public function __construct($command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)
    141|     {
    142|         if (!\function_exists('proc_open')) {
  > 143|             throw new LogicException('The Process class relies on proc_open, which is not available on your PHP installation.');
    144|         }
    145|
    146|         if (!\is_array($command)) {
    147|             @trigger_error(sprintf('Passing a command as string when creating a 

![Lily_Screenshot_1558369827](https://user-images.githubusercontent.com/34182357/58038975-060d6d00-7b64-11e9-8634-e67f35ad2252.png)

**Comment by WangNingkai** [comment]
禁用函数没有开启


 
---原始邮件---
发件人: "1181590332"<notifications@github.com>
发送时间: 2019年5月21日 01:01:59
收件人: "WangNingkai/OLAINDEX"<OLAINDEX@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [WangNingkai/OLAINDEX] 宝塔安装，每次到输入域名回车都会报错 (#151)



Password：[ 12345678 ]
 
Symfony\Component\Process\Exception\LogicException  : The Process class relies on proc_open, which is not available on your PHP installation.
 
at /www/wwwroot/smloli.xyz/vendor/symfony/process/Process.php:143
 139|      */
 140|     public function __construct($command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)
 141|     {
 142|         if (!\function_exists('proc_open')) {
  
143|             throw new LogicException('The Process class relies on proc_open, which is not available on your PHP installation.');
 144|         }
 145|
 146|         if (!\is_array($command)) {
 147|             @trigger_error(sprintf('Passing a command as string when creating a
