### ISSUE TITLE
你好，我将缓存类型改成redis后执行php artisan config:cache 进入网站显示500

### ISSUE THREAD

**Issue by 1181590332** [WangNingkai/OLAINDEX#154]
composer require predis/predis 命令也执行了
![Lily_Screenshot_1558613840](https://user-images.githubusercontent.com/34182357/58252265-45240400-7d98-11e9-999a-01435373880e.png)
![Lily_Screenshot_1558613846](https://user-images.githubusercontent.com/34182357/58252270-47865e00-7d98-11e9-8f0c-5cde2b036ffb.png)

**Comment by 1181590332** [comment]
![Lily_Screenshot_1558614121](https://user-images.githubusercontent.com/34182357/58252345-7b618380-7d98-11e9-9bd4-13cc57485dab.png)
![Lily_Screenshot_1558614136](https://user-images.githubusercontent.com/34182357/58252351-7dc3dd80-7d98-11e9-9ab3-5e78bd4a887b.png)

**Comment by WangNingkai** [comment]
@1181590332   首先需要安装redis扩展 `composer require predis/predis `然后执行 `php artisan config:cache` 最后刷新缓存 `php artisan od:cache`

**Comment by 1181590332** [comment]
> @ 1181590332 首先需要安装Redis的扩展`composer require predis/predis `然后执行`php artisan config:cache`求最后刷新缓存`php artisan od:cache`

谢谢，我再去试试！！！

**Comment by 1181590332** [comment]
我这次是先安装Redis的扩展 然后composer require predis/predis 改完env的缓存类型再执行php artisan config:cache最后刷新缓存的时候出了问题php artisan od:cache  请问我的步骤是不是错了
![Lily_Screenshot_1558615268](https://user-images.githubusercontent.com/34182357/58253573-5ae6f880-7d9b-11e9-9ed8-422cbbaed4c5.png)
![Lily_Screenshot_1558615274](https://user-images.githubusercontent.com/34182357/58253577-5d495280-7d9b-11e9-8d47-071d7e299180.png)

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/58253704-941f6880-7d9b-11e9-82e3-b3a6bcc1d535.png)


安装的扩展目录不对

**Comment by WangNingkai** [comment]
在项目目录安装 扩展，然后按步骤操作

**Comment by 1181590332** [comment]
> 在项目目录安装 扩展，然后按步骤操作

嗯嗯

**Comment by 1181590332** [comment]
谢谢，已经可以啦
