### ISSUE TITLE
文件/文件夹排序存在的一些问题

### ISSUE THREAD

**Issue by mqdlzh** [WangNingkai/OLAINDEX#156]
### 1. 该问题的重现步骤是什么？
![2019052401](https://user-images.githubusercontent.com/31967654/58706190-e2f48000-83e3-11e9-9ef1-88667128d461.gif)
Gif加载略慢啊。。。
前面4个文件夹明显就没排序正确，按 修改时间排序 也是一样的。

### 2. 你期待的结果是什么？实际看到的又是什么？
修正 文件/文件夹 的按 名称/修改时间/大小 的正确排序显示
如果可以希望能显示文件夹内容大小（最好就是可以在控制台里选择是否显示，嫌麻烦可以直接让它显示就好了）

### 3. 问题出现的环境

- 操作系统版本：CentOS Linux 7.3.1611 
- Apache/NGINX 版本：Nginx1.16.0
- PHP 版本：7.2
- OLAINDEX 版本：3.2.1
- 浏览器版本：Google Chrome 74.0.3729.169（正式版本）

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
@mqdlzh 已优化

**Comment by lurenJBD** [comment]
@WangNingkai 方便的话，把这个issues删除吧，感谢
