### ISSUE TITLE
建议增加非管理员用户的搜索功能

### ISSUE THREAD

**Issue by tanzhenhong** [WangNingkai/OLAINDEX#159]
目前管理员登录后，首页右上角有搜索框，但是普通游客没有搜索框，建议加上。
对于搜索结果文件是加密的情况，可以显示搜索结果，但打开需要输入密码。
不知道上述建议是否恰当。
感谢！

**Comment by WangNingkai** [comment]
感谢提供建议，目前我也在空余时间重构中

**Comment by mqdlzh** [comment]
> 感谢提供建议，目前我也在空余时间重构中

弱弱地问一下。。。文件名排序问题会考虑修复吗QAQ

**Comment by WangNingkai** [comment]
@tanzhenhong 新版已加入非管理员搜索限制 @mqdlzh 文件名排序也已经优化
