### ISSUE TITLE
php artisan init:install  报错

### ISSUE THREAD

**Issue by Abiu1314** [WangNingkai/OLAINDEX#16]
https://ae01.alicdn.com/kf/HTB1uHX7XxrvK1RjSsze761ObFXa3.png

另外 网页都没有样式的，演示站也是，chrome，safari 打开都是这样子
https://ae01.alicdn.com/kf/HTB1Q245XzzuK1Rjy0Fp761EpFXan.png

**Comment by Abiu1314** [comment]
第一个域名是由输入的，没截图全

**Comment by WangNingkai** [comment]
@Abiu1314 怎么会，jsdelivr屏蔽了？

**Comment by WangNingkai** [comment]
目录缺少文件 .env.example

**Comment by Abiu1314** [comment]
> 目录缺少文件 .env.example

我打开的是你的演示站点也是，自己按照旧的安装步骤安装完也是这个样子
https://ae01.alicdn.com/kf/HTB1P2d7XzvuK1Rjy0Fa7602aVXaK.png
你的目录下也没这个.env.example 文件么？换edge也是这样子

**Comment by Abiu1314** [comment]
浏览器都是隐身模式打开网站的，应该不存在缓存问题

**Comment by WangNingkai** [comment]
显示站我这里一点问题没有啊，安装的话我本地测试也没问题，确保安装拉取的仓库完整

**Comment by Abiu1314** [comment]
网页无样式布局已经解决了。是浏览器的ProxyeeDown的pac问题
