### ISSUE TITLE
请问是否可以将图床设置为主页而不显示/image呢？

### ISSUE THREAD

**Issue by fxzxmicah** [WangNingkai/OLAINDEX#160]
或者可以直接删除其它功能单独做一个图床版，毕竟OneDrive的下载速度也不敢恭维，做图床的速度还是可以的。

**Comment by fxzxmicah** [comment]
或者可以直接删除其它功能单独做一个图床版，毕竟OneDrive的下载速度也不敢恭维。

**Comment by WangNingkai** [comment]
可以，目前想法是后期可以为图床提供接口，然后可以单独调用上传图片接口

**Comment by fxzxmicah** [comment]
@WangNingkai 好的，我给你发了一封邮件，你可以查看一下。

**Comment by WangNingkai** [comment]
新版已调整 另外加入第三方上传接口
