### ISSUE TITLE
网站路径问题

### ISSUE THREAD

**Issue by anadano** [WangNingkai/OLAINDEX#161]
### 1. 该问题的重现步骤是什么？
正常使用
### 2. 你期待的结果是什么？实际看到的又是什么？
期待 abc.com/file.zip
实际 abc.com/home/file.zip

从oneindex切换过来的话，以前发过的链接不就全都失效了吗？而且加个home链接也变长了

**Comment by anadano** [comment]
还有一个小小的问题，就是能不能设置默认不分页
和博客之类的还不一样，目录程序更接近文件管理器
想一下如果文件管理器默认50个项目分一页还没法从设置调那得多难受

**Comment by WangNingkai** [comment]
1.目前本应用是按照home索引，目前修改的话涉及比较多。
2.分页设置这个可以考虑进来，感谢给与建议

**Comment by anadano** [comment]
多谢大佬考虑😊
