### ISSUE TITLE
wiki里面有个小错误

### ISSUE THREAD

**Issue by DoraemonSong** [WangNingkai/OLAINDEX#162]
地址：https://github.com/WangNingkai/OLAINDEX/wiki/其他

这篇wiki中，缓存配置里面有一段表述，“如使用 redis作为缓存的话，还需要安装 predis 包,手动执行 composer requrie predis/predis”，后面这里可能手速太快写了个错误的命令，应该是composer require predis/predis

**Comment by WangNingkai** [comment]
感谢提醒 已修改
