### ISSUE TITLE
图片有时候会无法显示

### ISSUE THREAD

**Issue by DoraemonSong** [WangNingkai/OLAINDEX#163]
打开图片查看页面，有时候图片会无法查看，清理缓存之后，就立马变好了，但是要不了多久，又可能变得不行
查看网页源代码发现是输出有点问题，见图
![](https://file.swei.us/view/pic/WX20190530-155110%402x.png)
![](https://file.swei.us/view/pic/WX20190530-155203%402x.png)
页面上其他内容都正常，日志也没输出错误

请问这个是程序bug还是我配置上有什么问题呢？

### 问题出现的环境

- 操作系统版本：CentOS7.6
- Apache/NGINX 版本：nginx1.16
- PHP 版本：7.3.0
- OLAINDEX 版本：2019.03

**Comment by WangNingkai** [comment]
麻烦提供具体的错误显示
