### ISSUE TITLE
关于静态文件的CDN加载慢的问题

### ISSUE THREAD

**Issue by luminouskk** [WangNingkai/OLAINDEX#164]
非常感谢您提供很棒的一个开源程序,不过有个小问题希望您能够关注一下

近期有个朋友一直跟我说他打开OLAINDEX的站点非常慢，第一次要十几秒，于是简单分析了一下原因

您目前的静态文件主要引用了兽兽的loli.net公共静态资源，此域名前段时间因被人举报国内的备案被吊销，源站已经迁移至香港。目前访问来看是HKBN+HKT的商宽，IPv4环境在分配至HKBN节点时速度比较稳定，而HKT节点在晚高峰会受到很严重的QoS。

但是拖慢速度的以上并不是主要的原因，实际上是因为该资源站开启了IPv6解析，而且IPv6优先级高于IPv4，在具有IPv6的条件下会优先通过IPv6访问。国内目前IPv6与香港peer建设尚未完成，在IPv6访问条件下，移动和电信路由会绕欧洲，联通和教育网会绕美国，延迟在400ms左右。
![avatar](https://i.lty.fun/images/TIM20190609202510.png)

国内的IPv6已经大面积铺开了，通过IPv6加载静态资源时会消耗很长的时间，这也是很多人第一次访问慢的原因了。

个人建议您选择其他具有国内节点的CDN服务商，亦或者提供本地化的选择，打包静态资源让用户自行选择放置在本地或自有的对象存储上。

之前尝试了一下本地化，深感这是一个不小的改动，感谢您的辛劳与付出，谢谢ヾ(≧▽≦*)o

**Comment by WangNingkai** [comment]
嗯看了下问题，确实这样，公共静态资源cdn存在一定的问题。目前也在筹备将此项目重新规划修改下，但是目前看到用此版本的用户还是蛮多的，反应的问题也比较多，近期会对其进行小量的修改

**Comment by luminouskk** [comment]
好的，辛苦啦(*'▽'*)♪
