### ISSUE TITLE
新版绑定不了账号 账号为国际版

### ISSUE THREAD

**Issue by yimshing** [WangNingkai/OLAINDEX#167]
### 1. 该问题的重现步骤是什么？
无法绑定账号
### 3. 问题出现的环境

- 操作系统版本：centos7
- Apache/NGINX 版本：NGINX 1.15.10
- PHP 版本：7.2
- OLAINDEX 版本：最新版
- 浏览器版本：Cent Browser  4.0.9.112

[//]: # (如有图片请附上截图)
[
[绑定失败情况录像.zip](https://github.com/WangNingkai/OLAINDEX/files/3286826/default.zip)

](url)

**Comment by moefir** [comment]
账号问题吧，我刚刚搭建，没问题，国际版onedrive

**Comment by yimshing** [comment]
> 账号问题吧，我刚刚搭建，没问题，国际版onedrive

铁定不是 我输入完secret和id 一按绑定就变空白了 换了三个号都这样

**Comment by WangNingkai** [comment]
@yimshing 清理缓存 然后重新拉取更新看下

**Comment by yimshing** [comment]
> @yimshing 清理缓存 然后重新拉取更新看下
从拉报以下错误 应该是database的问题
Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.email (SQL: insert into "users" ("name", "email", "password") values (admin, admin@admin.com, $2y$10$8PJ2ROYNDgdFDpso7cf82.t8934225Nk2UXqlY2Iofj6YkqHEXc3q))

**Comment by WangNingkai** [comment]
那就是数据库的原因，两个方法1是删除user是表中数据2是删除原先的database.sqlite ，重新复制 database.sample.sqlite 为database.sqlite

**Comment by yimshing** [comment]
> 那就是数据库的原因，两个方法1是删除user是表中数据2是删除原先的database.sqlite ，重新复制 database.sample.sqlite 为database.sqlite

问题是 我把整个网站目录删了 重新拉的 也这个情况 不知道这个database.sqlite的路径

**Comment by WangNingkai** [comment]
教程上写明了 database目录下 
![Uploading image.png…]()
