### ISSUE TITLE
BUG编辑按钮错位

### ISSUE THREAD

**Issue by moefir** [WangNingkai/OLAINDEX#168]
提交个bug哈
看图就好啦
![https://www.kuku.me/img/public/data/2019/06/5d026b9bafbbc.png](https://www.kuku.me/img/public/data/2019/06/5d026b9bafbbc.png)
应该是README.md后面会显示编辑按钮得吧，然后显示到其他地方去了。。

还有就是，更换外部资源的cdn之后，响应速度还是慢，和pyone、cuteone的响应速度差距有点大，这2个基本上可以秒开。。缓存方式都更换过，不知道作者大大还能优化优化下吗

**Comment by moefir** [comment]
还有一个bug，，，后台管理的设置都是空的？？？？？
![](https://www.kuku.me/img/public/data/2019/06/5d026de28fefd.png)

**Comment by WangNingkai** [comment]
1. 图中的问题我还没有遇见过，一般来说可编辑文本文件都有编辑按钮，也有可能网络原因导致，具体需要排查。
2.响应速度受到服务器网络状况、缓存类型等影响，给你看下我的响应速度 除了第一次从请求耗费较长时间，后期缓存速度都比较快的。

![image](https://user-images.githubusercontent.com/23030927/59479837-f4806200-8e90-11e9-9be0-cde0231eacbc.png)
3.后台管理默认就是空的，自己根据要求可以填写保存，此处非bug

**Comment by moefir** [comment]
> 
> 
>     1. 图中的问题我还没有遇见过，一般来说可编辑文本文件都有编辑按钮，也有可能网络原因导致，具体需要排查。
> 
>     2. 响应速度受到服务器网络状况、缓存类型等影响，给你看下我的响应速度 除了第一次从请求耗费较长时间，后期缓存速度都比较快的。
> 
> 
> ![image](https://user-images.githubusercontent.com/23030927/59479837-f4806200-8e90-11e9-9be0-cde0231eacbc.png)
> 
>     1. 后台管理默认就是空的，自己根据要求可以填写保存，此处非bug

第一个问题的话，我更改显示设置就正常啦，，谢谢作者解答哈

**Comment by WangNingkai** [comment]
响应较慢问题 经过排查已经发现，已经优化，更新后可体验。具体可以在演示站点测试
