### ISSUE TITLE
安装命令成功但是打开网页报错了

### ISSUE THREAD

**Issue by taotaolin** [WangNingkai/OLAINDEX#17]
Warning: require(): open_basedir restriction in effect. File(/www/wwwroot/od.ramiko.me/vendor/autoload.php) is not within the allowed path(s): (/www/wwwroot/od.ramiko.me/public/:/tmp/:/proc/) in /www/wwwroot/od.ramiko.me/public/index.php on line 24

Warning: require(/www/wwwroot/od.ramiko.me/vendor/autoload.php): failed to open stream: Operation not permitted in /www/wwwroot/od.ramiko.me/public/index.php on line 24

Fatal error: require(): Failed opening required '/www/wwwroot/od.ramiko.me/public/../vendor/autoload.php' (include_path='.:/www/server/php/71/lib/php') in /www/wwwroot/od.ramiko.me/public/index.php on line 24

**Comment by WangNingkai** [comment]
目录没有权限，看字面意思好像是open_basedir受到了限制，应该是你一开始配置的网页根目录没有指到public目录导致的，可以试下先拉取目录下来再配置网页目录应该就好了
