### ISSUE TITLE
issue - OLAINDEX

### ISSUE THREAD

**Issue by WangNingkai** [WangNingkai/OLAINDEX#171]
https://wangningkai.github.io/OLAINDEX/#/issue 

 Description

**Comment by mounull** [comment]
当执行`php artisan od:install`时,出现报错
```
   Illuminate\Database\QueryException  : could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)

  at /home/www/olaindex/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("could not find driver")
      /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("could not find driver")
      /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.
```

**Comment by miaachan** [comment]
> @mounull
> 当执行`php artisan od:install`时,出现报错
> ```
>    Illuminate\Database\QueryException  : could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)
> 
>   at /home/www/olaindex/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
>     660|         // If an exception occurs when attempting to run a query, we'll format the error
>     661|         // message to include the bindings with SQL, which will make this exception a
>     662|         // lot more helpful to the developer instead of just the database's errors.
>     663|         catch (Exception $e) {
>   > 664|             throw new QueryException(
>     665|                 $query, $this->prepareBindings($bindings), $e
>     666|             );
>     667|         }
>     668| 
> 
>   Exception trace:
> 
>   1   Doctrine\DBAL\Driver\PDOException::("could not find driver")
>       /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
> 
>   2   PDOException::("could not find driver")
>       /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
> 
>   Please use the argument -v to see more details.
> ``` 

同問

**Comment by miaachan** [comment]
> 当执行`php artisan od:install`时,出现报错
> 
> ```
>    Illuminate\Database\QueryException  : could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)
> 
>   at /home/www/olaindex/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
>     660|         // If an exception occurs when attempting to run a query, we'll format the error
>     661|         // message to include the bindings with SQL, which will make this exception a
>     662|         // lot more helpful to the developer instead of just the database's errors.
>     663|         catch (Exception $e) {
>   > 664|             throw new QueryException(
>     665|                 $query, $this->prepareBindings($bindings), $e
>     666|             );
>     667|         }
>     668| 
> 
>   Exception trace:
> 
>   1   Doctrine\DBAL\Driver\PDOException::("could not find driver")
>       /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
> 
>   2   PDOException::("could not find driver")
>       /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
> 
>   Please use the argument -v to see more details.
> ```

遇到過一樣的問題。
到phpinfo()檢查一下pdo drivers裡是否有開啟對sqlite的支持，如果沒有的話可以透過apt安裝
例
`sudo apt install php7.2-sqlite3`

**Comment by miaachan** [comment]
> 当执行`php artisan od:install`时,出现报错
> 
> ```
>    Illuminate\Database\QueryException  : could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)
> 
>   at /home/www/olaindex/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
>     660|         // If an exception occurs when attempting to run a query, we'll format the error
>     661|         // message to include the bindings with SQL, which will make this exception a
>     662|         // lot more helpful to the developer instead of just the database's errors.
>     663|         catch (Exception $e) {
>   > 664|             throw new QueryException(
>     665|                 $query, $this->prepareBindings($bindings), $e
>     666|             );
>     667|         }
>     668| 
> 
>   Exception trace:
> 
>   1   Doctrine\DBAL\Driver\PDOException::("could not find driver")
>       /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
> 
>   2   PDOException::("could not find driver")
>       /home/www/olaindex/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
> 
>   Please use the argument -v to see more details.
> ```

遇到過一樣的問題。
到phpinfo()檢查一下pdo drivers裡是否有開啟對sqlite的支持，如果沒有的話可以透過apt安裝
e.g. `sudo apt install php7.2-sqlite3`

Have encountered the same issue.
Please check the PDO drivers from phpinfo() to see whether the support for SQLite is enabled.
If not, enable it by installing the php-sqlite3 package.
e.g. `sudo apt install php7.2-sqlite3`

**Comment by anadano** [comment]
绑定之后返回首页显示
HTTP response code said error: The requested URL returned error: 403 Forbidden

后台log：Get OneDrive source content error. {"errno":22,"message":"HTTP response code said error: The requested URL returned error: 403 Forbidden","headers":"[object] (Curl\\CaseInsensitiveArray: {})"}

**Comment by pokima** [comment]
在图床上传之后,复制了链接,在浏览器打开之后直接下载了是什么情况啊

**Comment by wind-cool** [comment]
> 网站配置好后，出现截图这样，跟着教程来的，网站环境是Apache2+mysql5.7+php7.3

--- 

![访问域名就这样](https://i.loli.net/2019/11/23/7ZyDYEpA6JfM89B.png)
![网站目录权限](https://i.loli.net/2019/11/23/aBPYoLiVK1QClSp.png)
![网站conf配置](https://i.loli.net/2019/11/23/usIiA5SLUpGRgTa.png)

![ssl.conf配置](https://i.loli.net/2019/11/23/IhMmUS1H62JykW5.png)

> 请问我该怎么做？

**Comment by wind-cool** [comment]
> PHP模块如下：   
```php

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ds
enchant
exif
fileinfo
filter
ftp
gd
geoip
gettext
gmp
gnupg
hash
http
iconv
igbinary
imagick
imap
interbase
intl
json
ldap
libsmbclient
libxml
lua
mailparse
mbstring
mongodb
msgpack
mysqli
mysqlnd
OAuth
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
PDO_Firebird
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
propro
pspell
radius
raphf
readline
recode
redis
Reflection
rrd
session
shmop
SimpleXML
smbclient
snmp
soap
sockets
sodium
solr
SPL
sqlite3
ssh2
standard
Stomp
sysvmsg
sysvsem
sysvshm
tideways_xhprof
tidy
tokenizer
uploadprogress
uuid
wddx
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
yac
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

**Comment by wind-cool** [comment]
> 自动生成的 ssl.conf

![ssl](https://i.loli.net/2019/11/23/NEmvxKBwRo26ykA.png)

> .htaccess 内容

```php

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
#    RewriteCond %{HTTP:Authorization} .
#    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]


        RewriteCond %{HTTP_USER_AGENT} (^$|FeedDemon|Indy Library|Alexa Toolbar|AskTbFXTV|AhrefsBot|CrawlDaddy|CoolpadWebkit|Java|Feedly|UniversalFeedParser|ApacheBench|Microsoft URL Control|Swiftbot|ZmEu|oBot|jaunty|Python-urllib|lightDeckReports Bot|YYSpider|DigExt|HttpClient|MJ12bot|heritrix|EasouSpider|Ezooms) [NC]
        RewriteRule ^(.*)$ - [F]


    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

**Comment by wind-cool** [comment]
> 我域名 `doc.ucool.io` ,一开始在浏览器输入并访问  `https://doc.uccol.io ` ,回车后浏览器访问网站，结果自动变成了 `https://doc.ucool.io/admin/install `，提示 ` Not found ` 错误，请问这是什么情况?😭

**Comment by foodphoenix** [comment]
cert.pfx

**Comment by foodphoenix** [comment]
cert.pfx  这个文件怎么也下载来，如何去掉了

**Comment by wind-cool** [comment]
>本来今天下午5点还好好的，我只不过删除了四个视频文件，网站刷新后就500错误，重新刷新和重启网站后还是500错误，怎么办？

>下面是最新的日志

```php
[2019-11-30 17:00:05] local.ERROR: Get OneDrive source content error. {"errno":22,"message":"HTTP response code said error: The requested URL returned error: 401 Unauthorized","headers":"[object] (Curl\\CaseInsensitiveArray: {})"} 
[2019-11-30 17:00:05] local.ERROR: Undefined index: value {"exception":"[object] (ErrorException(code: 0): Undefined index: value at /var/www/doc/app/Service/OneDrive.php:182)
[stacktrace]
#0 /var/www/doc/app/Service/OneDrive.php(182): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/doc/ap...', 182, Array)
#1 /var/www/doc/app/Service/OneDrive.php(179): App\\Service\\OneDrive->getNextLinkList(Array, Array)
#2 /var/www/doc/app/Service/OneDrive.php(150): App\\Service\\OneDrive->getNextLinkList(Array)
#3 /var/www/doc/app/Console/Commands/OneDrive/RefreshCache.php(60): App\\Service\\OneDrive->getItemListByPath('/beautiful-Imag...', '?select=id,eTag...')
#4 /var/www/doc/app/Console/Commands/OneDrive/RefreshCache.php(74): App\\Console\\Commands\\OneDrive\\RefreshCache->getChildren('/beautiful-Imag...')
#5 /var/www/doc/app/Console/Commands/OneDrive/RefreshCache.php(86): App\\Console\\Commands\\OneDrive\\RefreshCache->getRecursive('/beautiful-Imag...')
#6 /var/www/doc/app/Console/Commands/OneDrive/RefreshCache.php(45): App\\Console\\Commands\\OneDrive\\RefreshCache->getRecursive('/')
#7 [internal function]: App\\Console\\Commands\\OneDrive\\RefreshCache->handle()
#8 /var/www/doc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /var/www/doc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/doc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /var/www/doc/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /var/www/doc/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#13 /var/www/doc/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /var/www/doc/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/doc/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/doc/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\OneDrive\\RefreshCache), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/doc/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/doc/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/doc/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/doc/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 

```

**Comment by wind-cool** [comment]
php7.4是不是不支持啊

**Comment by wind-cool** [comment]
`有没有人知道怎么将默认的Dplayer更换成plyr.js啊`

**Comment by WangNingkai** [comment]
> php7.4是不是不支持啊

支持的

**Comment by WangNingkai** [comment]
> `有没有人知道怎么将默认的Dplayer更换成plyr.js啊`

更换video.blade.php 和 dash.blade.php 即可

**Comment by guhailong18** [comment]
500报错

[2020-01-23 09:36:48] local.ERROR: SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select * from "users" where "name" = admin limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select * from \"users\" where \"name\" = admin limit 1) at /www/wwwroot/a.dream18.xyz/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: users at /www/wwwroot/a.dream18.xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: users at /www/wwwroot/a.dream18.xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61)
[stacktrace]

**Comment by liuziwen77** [comment]
Olaindex首页出现HTTP response code said error: The requested URL returned error: 400 Bad Request

**Comment by weilintao** [comment]
用该网盘作为分享盘供别人下载   下载次数过多 导致 无法下载提示 429 too many requests 怎么办

**Comment by piaoyun** [comment]
请问下在同一台服务器上面，搭建2个olaindex么？
搭建的时候，都是开了2个网站，来搭建，不同的域名前缀

a.xxx.xxx
b.xxx.xxx

这样访问，但是发现第二个始终会出现莫名其妙的错误呢。

**Comment by suyin-long** [comment]
世纪互联的怎么申请啊？
执行`php artisan od:switch`报
`  Command "od:switch" is not defined.  
                                       
  Did you mean one of these?           
      od:cache                         
      od:command                       
      od:cp                            
      od:direct                        
      od:download                      
      od:find                          
      od:info                          
      od:install                       
      od:login                         
      od:logout                        
      od:ls                            
      od:mkdir                         
      od:mv                            
      od:offline                       
      od:password                      
      od:refresh                       
      od:reset                         
      od:rm                            
      od:share                         
      od:upload                        
      od:whereis `
怎么回事？

**Comment by suyin-long** [comment]
希望出一个5.0版本的安装教程
