### ISSUE TITLE
其它配置 - OLAINDEX

### ISSUE THREAD

**Issue by WangNingkai** [WangNingkai/OLAINDEX#177]
https://wangningkai.github.io/OLAINDEX/#/other 

 Description

**Comment by qmys99** [comment]
列队刷新命令错误；
正确应该是：php artisan queue:work database --queue=olaindex --tries=3

**Comment by qmys99** [comment]
加密那里，设置加密后出现500错误 给文件777权限依旧。

**Comment by WangNingkai** [comment]
> @qmys99
> 列队刷新命令错误；
> 正确应该是：php artisan queue:work database --queue=olaindex --tries=3

列队刷新命令错误,确实拼写错误，已调整

**Comment by WangNingkai** [comment]
> @qmys99
> 加密那里，设置加密后出现500错误 给文件777权限依旧。

麻烦提供具体的报错日志

**Comment by dteen** [comment]
请问新版本是否删除了看图模式这个功能？

感觉普通主题的看图模式非常实用，可以缩略图预览，同时有类相册的点击切换下一张的功能。。
mdui主题自带看图模式缩略图。但是看图没办法点击切换下一张。。

请问除了切换回旧版本，有没有办法找回这个功能？

**Comment by WangNingkai** [comment]
@dteen 那个看图模式有一定的缺陷，目前的目录里的也是可以上下切换的
![image](https://user-images.githubusercontent.com/23030927/59958181-f4a5e080-94d4-11e9-8984-82dfeb218b52.png)
![image](https://user-images.githubusercontent.com/23030927/59958182-fb345800-94d4-11e9-8b1e-98e53efd431e.png)
![image](https://user-images.githubusercontent.com/23030927/59958187-04bdc000-94d5-11e9-90d4-5a48ca725722.png)

**Comment by Moexin** [comment]
怎么更改登录账户名

**Comment by foodphoenix** [comment]
我下载文件怎么把这个文件也下载下来了 cert.pfx

**Comment by imnmmc** [comment]
队列刷新时出错
ErrorException  : pcntl_signal() has been disabled for security reasons

  at /www/wwwroot/pan/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:531
    527|         pcntl_async_signals(true);
    528|
    529|         pcntl_signal(SIGTERM, function () {
    530|             $this->shouldQuit = true;
  > 531|         });
    532|
    533|         pcntl_signal(SIGUSR2, function () {
    534|             $this->paused = true;
    535|         });

  Exception trace:

  1   pcntl_signal(Object(Closure))
      /www/wwwroot/pan/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:531

  2   Illuminate\Queue\Worker::listenForSignals()
      /www/wwwroot/pan/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:88

  Please use the argument -v to see more details.

**Comment by Snowflake-Pink** [comment]
> 队列刷新时出错
> ErrorException : pcntl_signal() has been disabled for security reasons
> 
> at /www/wwwroot/pan/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:531
> 527| pcntl_async_signals(true);
> 528|
> 529| pcntl_signal(SIGTERM, function () {
> 530| $this->shouldQuit = true;
> 
> > 531|         });
> > 532|
> > 533|         pcntl_signal(SIGUSR2, function () {
> > 534|             $this->paused = true;
> > 535|         });
> 
> Exception trace:
> 
> 1 pcntl_signal(Object(Closure))
> /www/wwwroot/pan/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:531
> 
> 2 Illuminate\Queue\Worker::listenForSignals()
> /www/wwwroot/pan/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:88
> 
> Please use the argument -v to see more details.

需要额外取消禁用两个 `php` 函数，分别是 `pcntl_signal` 和 `pcntl_alarm` 。

**Comment by babywbx** [comment]
有什么办法可以1分钟刷新一次缓存的吗？

**Comment by ShaoPak** [comment]
大佬，请问OLAONDEX的队列刷新在宝塔面板的Supervisor插件里怎么设置呢

**Comment by SupremeLiam** [comment]
关于页面排序，请问如何在后台设置默认值？例如设置按name排序，页面项目数量limit为无上限？
