### ISSUE TITLE
部署安装 - OLAINDEX

### ISSUE THREAD

**Issue by WangNingkai** [WangNingkai/OLAINDEX#178]
https://wangningkai.github.io/OLAINDEX/#/install 

 Description

**Comment by tanzhenhong** [comment]
最新版安装过程出现问题，用的是bt安装方式。
执行composer install -vvv这行命令后，提示错误如下：
![1](https://user-images.githubusercontent.com/7790837/59576759-635cf580-90f3-11e9-9211-a26c51e23f63.png)
提示找不到数据库。

**Comment by WangNingkai** [comment]
@tanzhenhong 
![image](https://user-images.githubusercontent.com/23030927/59578833-ae2f3b00-90fc-11e9-91a8-c822d2d6a915.png)

确保执行此步骤，新建数据库文件

**Comment by tanzhenhong** [comment]
你好，这个地址上的教程（https://imwnk.cn/archives/bt-olaindex）缺了这一步操作，建议更新。

另外，执行最后一步的时候，chmod 777 storage/app/config.json，报错，应该是没有这个文件。
![2](https://user-images.githubusercontent.com/7790837/59592825-62dc5300-9123-11e9-9d39-e187023ad1e7.png)

**Comment by qmys99** [comment]
配置完所有打不开报错：HTTP response code said error: The requested URL returned error: 403 Forbidden

**Comment by qmys99** [comment]
安装过后，绑定账号界面是无法返更改绑定得。

**Comment by WangNingkai** [comment]
> @qmys99
> 安装过后，绑定账号界面是无法返更改绑定得。
> 

安装流程已更新，拉去更新删除数据库文件，重新安装即可

**Comment by WangNingkai** [comment]
> @tanzhenhong
> 你好，这个地址上的教程：https://imwnk.cn/archives/bt-olaindex
> 缺了这一步操作，建议更新。
> 
> 另外，执行最后一步的时候，chmod 777 storage/app/config.json，报错，应该是没有这个文件。
> ![2](https://user-images.githubusercontent.com/7790837/59592825-62dc5300-9123-11e9-9d39-e187023ad1e7.png)
> 

忘记更新教程了，可以参考这边安装

**Comment by YuutaDoNo** [comment]
执行`composer install -vvv`时  
如下图形式报错  
![](https://i.bmp.ovh/imgs/2019/07/d8523d708c794ea6.png)

**Comment by natural-ts** [comment]
这个有没有办法安装到虚拟主机空间上面，例如我的directadmin都支持这些环境，但是无法运行命令行，可以安装吗？

**Comment by 45005894** [comment]
> 执行`composer install -vvv`时
> 如下图形式报错
> ![](https://camo.githubusercontent.com/7548566a78dd06c850b88d97da7002543b3a1c75/68747470733a2f2f692e626d702e6f76682f696d67732f323031392f30372f643835323364373038633739346561362e706e67)
> 
> 问题已解决，解除禁用php函数

大佬 具体是哪几个函数？我删除了教程里说的函数，还是一样的错误。。

**Comment by WangNingkai** [comment]
@45005894 估计用的宝塔吧 又有禁用函数需要打开，这个`putenv()` 函数也得打开

**Comment by mainblog** [comment]
遇到一个bug，在最后提交如下图的时候，遇到空值。
![bug](https://ww1.yunjiexi.club/2019/10/10/aa8382b060c69f073b19e8c1bdb2088d.png "bug")

**Comment by AkeemMYU** [comment]
> 遇到一个bug，在最后提交如下图的时候，遇到空值。
> ![bug](https://camo.githubusercontent.com/eabe686f0ff395af2ed612b89e31ad9b70f7796d/68747470733a2f2f7777312e79756e6a696578692e636c75622f323031392f31302f31302f61613833383262303630633639663037336231396538633162646232303838642e706e67)

同样的bug

**Comment by pokima** [comment]
> @AkeemMYU
> > 遇到一个bug，在最后提交如下图的时候，遇到空值。
> > ![bug](https://camo.githubusercontent.com/eabe686f0ff395af2ed612b89e31ad9b70f7796d/68747470733a2f2f7777312e79756e6a696578692e636c75622f323031392f31302f31302f61613833383262303630633639663037336231396538633162646232303838642e706e67)
> 
> 同样的bug


> @AkeemMYU
> > 遇到一个bug，在最后提交如下图的时候，遇到空值。
> > ![bug](https://camo.githubusercontent.com/eabe686f0ff395af2ed612b89e31ad9b70f7796d/68747470733a2f2f7777312e79756e6a696578692e636c75622f323031392f31302f31302f61613833383262303630633639663037336231396538633162646232303838642e706e67)
> 
> 同样的bug

需要文件夹权限

**Comment by wind-cool** [comment]
> > @AkeemMYU
> > > 遇到一个bug，在最后提交如下图的时候，遇到空值。
> > > ![bug](https://camo.githubusercontent.com/eabe686f0ff395af2ed612b89e31ad9b70f7796d/68747470733a2f2f7777312e79756e6a696578692e636c75622f323031392f31302f31302f61613833383262303630633639663037336231396538633162646232303838642e706e67)
> > 
> > 
> > 同样的bug
> 
> > @AkeemMYU
> > > 遇到一个bug，在最后提交如下图的时候，遇到空值。
> > > ![bug](https://camo.githubusercontent.com/eabe686f0ff395af2ed612b89e31ad9b70f7796d/68747470733a2f2f7777312e79756e6a696578692e636c75622f323031392f31302f31302f61613833383262303630633639663037336231396538633162646232303838642e706e67)
> > 
> > 
> > 同样的bug
> 
> 需要文件夹权限



# 将 `storage` 权限改成777就可以了 ` chmod -Rf 777 storage `

**Comment by stoee** [comment]
> @Yofo-me
> > > @AkeemMYU
> > > > 遇到一个bug，在最后提交如下图的时候，遇到空值。
> > > > ![bug](https://camo.githubusercontent.com/eabe686f0ff395af2ed612b89e31ad9b70f7796d/68747470733a2f2f7777312e79756e6a696578692e636c75622f323031392f31302f31302f61613833383262303630633639663037336231396538633162646232303838642e706e67)
> > > 
> > > 
> > > 同样的bug
> > 
> > > @AkeemMYU
> > > > 遇到一个bug，在最后提交如下图的时候，遇到空值。
> > > > ![bug](https://camo.githubusercontent.com/eabe686f0ff395af2ed612b89e31ad9b70f7796d/68747470733a2f2f7777312e79756e6a696578692e636c75622f323031392f31302f31302f61613833383262303630633639663037336231396538633162646232303838642e706e67)
> > > 
> > > 
> > > 同样的bug
> > 
> > 需要文件夹权限
> 
> 
> 
> # 将 `storage` 权限改成777就可以了 ` chmod -Rf 777 storage `

已经将 `storage` 权限改了，但还是空值，什么情况？
