### ISSUE TITLE
音乐播放报错500

### ISSUE THREAD

**Issue by MacbClarke** [WangNingkai/OLAINDEX#180]
### 1. 该问题的重现步骤是什么？
全新安装
### 2. 你期待的结果是什么？实际看到的又是什么？
正常使用；500 Server Error
### 3. 问题出现的环境
尝试在线播放音乐
- 操作系统版本：CentOS 7.3
- Apache/NGINX 版本：NGINX 1.16.0
- PHP 版本：7.2.19
- OLAINDEX 版本：4.0
- 浏览器版本：Chrome 74.0.3729.169

[//]: # (如有图片请附上截图)

![Snipaste_2019-06-14_23-39-44](https://user-images.githubusercontent.com/23311991/59520998-d270f900-8efd-11e9-95cf-d3af43c7c257.png)

**Comment by WangNingkai** [comment]
感谢反馈问题 已修复
