### ISSUE TITLE
给文件夹设定密码后报错500，取消密码后正常

### ISSUE THREAD

**Issue by fxzxmicah** [WangNingkai/OLAINDEX#181]
我也不太懂是什么原因，就当是个bug吧。

**Comment by WangNingkai** [comment]
我这里按照要求设置没问题，出错请贴出设置具体参数 以及报错日志 否则无法给出进一步帮助

**Comment by fxzxmicah** [comment]
此外，我进行了多次重新安装，由于chmod赋予权限后仍存在权限问题导致无法绑定账号（表现为安装后直接使用公用账号进入绑定页无法返回重新绑定，或者进入绑定页输入信息后却在下一步确认中全部变为空白），开始未找到原因，后来全新安装完成后将全部文件重新修改为www755才解决问题。
对于上面我提出的问题：
操作系统版本：CentOS 7.6.1810
Apache/NGINX 版本：Apache 2.4.39
PHP 版本：7.2.19
OLAINDEX 版本：4.0
浏览器版本：Microsoft Edge dev 76.0.182.6(chromium)
错误信息如下：
![report.png](https://pic.at-s.top/view/At-site-pic/2019/06/15/3jjPBP8U/report.png)

**Comment by WangNingkai** [comment]
之前密码设置存在一定的问题，更新后就可以了
