### ISSUE TITLE
请问支持虚拟主机吗？

### ISSUE THREAD

**Issue by Insightfy** [WangNingkai/OLAINDEX#182]
首先感谢作者大大的无私奉献,(鞠躬
请问支持cpanel系统的虚拟主机吗？虚机比较稳定。可以一直放在上面跑 不知道支持与否，看了教程但是有些代码跑起来报错

**Comment by WangNingkai** [comment]
虚拟主机满足安装所需的扩展即可，如无法满足的话，建议还是使用小型的vps 或者heroku等托管服务
