### ISSUE TITLE
绑定网盘问题

### ISSUE THREAD

**Issue by samon6bl** [WangNingkai/OLAINDEX#183]
出现这个界面，然后绑定网盘就不行了
![image](https://user-images.githubusercontent.com/49110064/59655242-3cbebd80-91cc-11e9-89c8-1f8d27fc1350.png)

**Comment by liuweicheng14** [comment]
我也遇到了这个问题

**Comment by WangNingkai** [comment]
具体出现此问题的步骤

**Comment by samon6bl** [comment]
正常申请完填入id和secret之后提交就到了图片的样子
后来用wiki里的这个指令处理好了
![image](https://user-images.githubusercontent.com/49110064/59691258-4ae4fc00-9215-11e9-8a6d-021ab21f1e23.png)

**Comment by liuweicheng14** [comment]
我还是存在这个问题，操作是按照教程来的

**Comment by liuweicheng14** [comment]
![image](https://user-images.githubusercontent.com/47742890/59759819-7b836f00-92c3-11e9-8810-8a5fa85bae12.png)
就是在正常输入密钥，点保存之后出现的

**Comment by WangNingkai** [comment]
确保 storage 目录和数据库文件权限 以及数据库文件存在目录 `database/database.sqlite`

**Comment by liuweicheng14** [comment]
storage 目录权限问题，好像设置为0777以后可以
