### ISSUE TITLE
账户绑定，最后一步显示无法访问此网站 

### ISSUE THREAD

**Issue by newmanfung** [WangNingkai/OLAINDEX#184]
您好！我的问题与https://github.com/WangNingkai/OLAINDEX/issues/27 类似，但是我在DOCKER内安装，能进入安装界面，并且可以填写ID等信息，但是出现无法访问。域名没有单独做SSL，是在NOIP申请的，所以能用HTTPS，请问是否相关？
![微信截图_20190619050015](https://user-images.githubusercontent.com/51973208/59720200-d760e000-9250-11e9-95ca-da56db96ac28.png)

**Comment by WangNingkai** [comment]
浏览器界面上 看着应该是网络原因导致的，重新安装在试下呢
