### ISSUE TITLE
再反馈个bug，没有日志。

### ISSUE THREAD

**Issue by fxzxmicah** [WangNingkai/OLAINDEX#186]
### 1. 该问题的重现步骤是什么？
我在同一服务器同一环境下安装两个同版本olaindex
### 2. 你期待的结果是什么？实际看到的又是什么？
其中一个在图片详情页无法显示图片，而另一个则可以，两个的图片均可以在点击查看原图中打开。
### 3. 问题出现的环境

- 操作系统版本：CentOS Linux 7.6.1810 (Core)
- Apache/NGINX 版本：Apache 2.4.39
- PHP 版本：7.2.19
- OLAINDEX 版本：4.0
- 浏览器版本：Microsoft Edge 76.0.182.6 dev

[//]: # (如有图片请附上截图)

**Comment by fxzxmicah** [comment]
间断性的出现，也不是一直打不开

**Comment by WangNingkai** [comment]
同一环境下需要配置修改 `.env` 中 `APP_NAME` ，一般来说 图片资源直接拉取接口数据，除网络原因，都是正常的

**Comment by fxzxmicah** [comment]
更换了之后呢？需要重启服务器，还是怎么？

**Comment by fxzxmicah** [comment]
@WangNingkai  你好，我更换了app name，采用了和另一个相同的安装步骤进行了重装，然而依旧无法预览图片。由于无法预览的是世纪互联的账号，所以是否与这个有关？

**Comment by WangNingkai** [comment]
无法预览图片还有一种可能 nginx 配置禁用了图片查看 @fxzxmicah

**Comment by fxzxmicah** [comment]
我使用的是Apache  @WangNingkai
