### ISSUE TITLE
图床界面有些错位

### ISSUE THREAD

**Issue by 1349422030** [WangNingkai/OLAINDEX#187]
### 1. 该问题的重现步骤是什么？
打开图床，并访问图床
### 2. 你期待的结果是什么？实际看到的又是什么？
一个优雅美观的图床
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx/1.14.2
- PHP 版本：PHP 7.3.3
- OLAINDEX 版本：54343b1
- 浏览器版本：EDGE

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/35253997/59895182-26a43d80-9416-11e9-9779-58158ee27625.png)

如图，搜索框哪里出现了一些错位的现象
（顺便图床没有以前好看了😂
我是删掉旧版本从新部署的新版本

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/59895261-797df500-9416-11e9-93e7-44b5f8d827e7.png)

你这个有问题吧

**Comment by 1349422030** [comment]
哦(⊙o⊙)？我再部署一便看看

**Comment by 1349422030** [comment]
问题发现，这个问题出现在后开启用了开放搜索之后

**Comment by 1349422030** [comment]
还有这个

![image](https://user-images.githubusercontent.com/35253997/59895470-5142c600-9417-11e9-813f-f6f32649b71a.png)

格式：5,10，每10分钟最多上传5次；5 每分钟最多上传5次
有些不太明白

**Comment by WangNingkai** [comment]
5,10，每10分钟最多上传5次；5,1 每分钟最多上传5次 这样就明了了

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/f890689604f67111f17ef77595d7be57d44cea29
