### ISSUE TITLE
绑定账户失败

### ISSUE THREAD

**Issue by ggoog** [WangNingkai/OLAINDEX#189]
### 1. 该问题的重现步骤是什么？
输入client_id跟client_secret点击下一步，没有信息带过来

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.16
- PHP 版本：7.2
- OLAINDEX 版本：最新版
- 浏览器版本：74

[//]: # (如有图片请附上截图)
<img width="755" alt="image" src="https://user-images.githubusercontent.com/25149246/59958021-c7583300-94d2-11e9-98cd-c9371ca1b049.png">

**Comment by WangNingkai** [comment]
请提供一下 具体的安装操作流程说明  我只里查一下看看是哪里的问题

**Comment by WangNingkai** [comment]
给 storage 目录777 权限看一下

**Comment by qstzs** [comment]
> 给 storage 目录777 权限看一下

给777就可以了！

**Comment by WangNingkai** [comment]
一般是目录缓存写入的权限问题

**Comment by ggoog** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/25149246/60029859-7dd73600-96d4-11e9-830f-5c58407e59ee.png">
我是按照你的指南一步一步来的，这里755不够，给777就行了，建议更新一下指南 @WangNingkai

**Comment by fxzxmicah** [comment]
不需要777，将目录下所有非隐藏的文件夹重新改成755就好了。 @WangNingkai @ggoog @qstzs
