### ISSUE TITLE
按名称排序的一个现象 & 看图模式已经没有了吗QAQ

### ISSUE THREAD

**Issue by 1349422030** [WangNingkai/OLAINDEX#190]
### 1. 该问题的重现步骤是什么？
对序列化（如末尾为1~100+）的多个文件进行文件排序
### 2. 你期待的结果是什么？实际看到的又是什么？
期待的文件排序
1、2、3.....8、9、10、11...
实际的文件排序
1、10、100、101、102...

&&

请问看图模式是被砍了吗(´･ω･`)?
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：07b0829
- 浏览器版本：

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/35253997/60396227-1bb57f80-9b71-11e9-8c32-71fe1b23c01e.png)

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/60397054-4c021b80-9b7b-11e9-8c2b-a3c7f2c0f647.png)
![image](https://user-images.githubusercontent.com/23030927/60397056-58867400-9b7b-11e9-8543-5551f49f223a.png)
看图模式没问题 ，更换了一种方式 ，左右滑动即可

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/f66cf886e8f6191defae816f40d820f9e3af5a44

自然排序的问题，文件名自然排序 已解决

**Comment by 1349422030** [comment]
> 看图模式没问题 ，更换了一种方式 ，左右滑动即可

可能是我没表达清楚😂我想说的是以前那种缩略图预览的方式，因为有些比较大的图f啥的直接看原图会很卡(;´༎ຶД༎ຶ`)

**Comment by WangNingkai** [comment]
> > 看图模式没问题 ，更换了一种方式 ，左右滑动即可
> 
> 可能是我没表达清楚😂我想说的是以前那种缩略图预览的方式，因为有些比较大的图f啥的直接看原图会很卡(;´༎ຶД༎ຶ`)

![image](https://user-images.githubusercontent.com/23030927/60406158-185cdb00-9be7-11e9-8f0f-6d600b8642cc.png)
