### ISSUE TITLE
建议：统计文件夹内项目的时候排除（README.md和HEAD.md）

### ISSUE THREAD

**Issue by zern** [WangNingkai/OLAINDEX#192]
感谢作者这个开源项目，使用起来很方便。
有个小小的建议希望统计 文件夹内项目的时候排除（README.md和HEAD.md）
因为访问者看不到这两个文件，但是项目数量还统计在内

**Comment by WangNingkai** [comment]
对的，这里考虑欠妥，感谢反馈。还有隐藏文件，大概改了下 。https://github.com/WangNingkai/OLAINDEX/commit/b403dae0435a5adead02ad45aae8a8e90a365c78

**Comment by zern** [comment]
感谢采纳此意见~
已更新
