### ISSUE TITLE
建议：密码页的信息显示是否可以显示HEAD.md或README.md的内容

### ISSUE THREAD

**Issue by zern** [WangNingkai/OLAINDEX#193]
嗯，感谢解决了文件目录数量的问题。
还是一个小建议
目前的加密文件夹的信息提示是固定的
所以能否显示HEAD.md或**README.md**的内容（其中一个）作为密码页的提示内容。以方便用户访问带密码的文件夹时，简单的介绍能让用户知道为什么加密（或有渠道获取密码）。

**Comment by WangNingkai** [comment]
自定义密码页提示是吗？这个回头可以在后台加个配置

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/d261fa6caf41cc98087060005c374fa3397ccc82 这个建议觉得不错，已经加上

**Comment by zern** [comment]
解决问题的速度真快啊~感激不尽~
**已经升级**
其实按照我先前的想法是加密目录暴露README.md文件，这样可以在每个加密目录都有不同的提示。但是这样会影响到（暴露）加密内容的介绍。嗯，你这样单独设置也是不错。毕竟这种提示也基本是一样的讯息~
