### ISSUE TITLE
图床无法上传，提示“Error during upload”，而在管理面板文件操作可以正常上传，之前的版本也可以上传

### ISSUE THREAD

**Issue by fxzxmicah** [WangNingkai/OLAINDEX#194]
### 1. 该问题的重现步骤是什么？
打开图床，选择图片上传，报错，旧版可以上传。
### 2. 你期待的结果是什么？实际看到的又是什么？
上传成功，显示引用链接。  报错，无法上传
### 3. 问题出现的环境

- 操作系统版本：CentOS Linux 7.6.1810 (Core)
- Apache/NGINX 版本：Apache 2.4.39
- PHP 版本：7.2.19
- OLAINDEX 版本：v4.0_pre_2
- 浏览器版本：Microsoft Edge 77.0.197.1 dev(64 位)

[//]: # (如有图片请附上截图)
![report](https://pic.at-s.top/view/At-site-pic/Report/1.png)

**Comment by WangNingkai** [comment]
尽量贴一下后台报错日志

**Comment by fxzxmicah** [comment]
后台没报错，不清楚怎么回事，不过我在后台可以上传，图床那页就不行，是不是新的插件的关系？ @WangNingkai

**Comment by HoursX** [comment]
同样的问题，后台没有报错。上传失败

**Comment by HoursX** [comment]
另外500问题也无法解决

**Comment by fxzxmicah** [comment]
什么500问题？ @HoursX

**Comment by alinuxsa** [comment]
各位图床不能上传是不是前面套了cf的cdn?
我试了下有cdn的情况下无法上传
cf里禁用缓存并清理本地dns缓存，直连可以上传成功，具体什么原因未知

**Comment by fxzxmicah** [comment]
没有用cf，国内的服务器，在图床页无法上传，在后台可以正常上传。 @alinuxsa

**Comment by alinuxsa** [comment]
> 
> 
> 没有用cf，国内的服务器，在图床页无法上传，在后台可以正常上传。 @alinuxsa

看来咱俩的问题还不一样

**Comment by fxzxmicah** [comment]
你是最新版吗? 或者你是前台后台都不能上传？ @alinuxsa

**Comment by HoursX** [comment]
> 什么500问题？ @HoursX

上传完文件之后在前台无法找到文件，并且点击文件夹出现500错误，具体看我今天关闭的那个issue，我以为问题已经解决

**Comment by HoursX** [comment]
> 什么500问题？ @HoursX

我又看了一下，在上传文件的时候，前台显示上传失败，实际上在云盘已经存在文件，但是不能访问。

**Comment by HoursX** [comment]
> 各位图床不能上传是不是前面套了cf的cdn?
> 我试了下有cdn的情况下无法上传
> cf里禁用缓存并清理本地dns缓存，直连可以上传成功，具体什么原因未知

没有套cdn出现错误

**Comment by fxzxmicah** [comment]
更新一下缓存试试 @alinuxsa

**Comment by alinuxsa** [comment]
经过我的测试，开了CF的情况下，通过[API](https://wangningkai.github.io/OLAINDEX/#/api)也可以上传成功，清掉缓存通过图床上传不成功。要不你试一下通过API上传？

**Comment by fxzxmicah** [comment]
什么时候考虑解决一下这个问题呢，用之前的那个上传插件就没问题，现在这个就无法上传。后台用的应该还是旧插件，上传没问题。 @WangNingkai

**Comment by lgq1349422030** [comment]
同样的问题，后台上传成功，图床上传失败
