### ISSUE TITLE
绑定帐号 请确认以下信息  内容是空的。

### ISSUE THREAD

**Issue by piaoyun** [WangNingkai/OLAINDEX#198]
![QQ截图20190711223308](https://user-images.githubusercontent.com/3724475/61059679-fe639980-a42b-11e9-978b-afba8da434c0.png)
绑定帐号 请确认以下信息

**Comment by YuutaDoNo** [comment]
storage权限问题，如果是宝塔面板的话，用宝塔的文件管理器改权限

**Comment by fxzxmicah** [comment]
作者给的是storage文件夹改成777，然而我改完并没有用。我的解决办法是把除了.开头的文件夹之外其它文件夹的权限全部重新改为755就好了。你可以都试试。 @piaoyun @YuutaDoNo

**Comment by WangNingkai** [comment]
主要是缓存目录权限的问题，可以将文件缓存改为redis或者memcached缓存

**Comment by mn19941219** [comment]
我的方法是宝塔改storage权限为777，不用命令改

**Comment by kettly1260** [comment]
@mn19941219  @fxzxmicah @YuutaDoNo 请问你们怎么解决的啊？文件夹我改过755和777都没用，把文件缓存该问redis了还是这样

**Comment by fxzxmicah** [comment]
@kettly1260 我就是重新赋权755就解决了
