### ISSUE TITLE
開啟檔案時都會出現 serviceNotAvailable

### ISSUE THREAD

**Issue by maple3142** [WangNingkai/OLAINDEX#199]
### 1. 该问题的重现步骤是什么？

在目錄中點擊任何檔案

### 2. 你期待的结果是什么？实际看到的又是什么？

可以正常下載檔案

### 3. 问题出现的环境

- 操作系统版本： Win10 x64
- Apache/NGINX 版本：nginx/1.16.0
- PHP 版本：7.2.20
- OLAINDEX 版本： Git 上 master 的最新版 (#d261fa6caf41cc98087060005c374fa3397ccc82)
- 浏览器版本： Chrome 74

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/9370547/61430507-8c73de80-a95c-11e9-9621-b21352f5a9a6.png)

權限:
![image](https://user-images.githubusercontent.com/9370547/61430526-a3b2cc00-a95c-11e9-8353-2107fe4d8947.png)

**Comment by horizain** [comment]
我也是这种情况，前一天还可以，忽然就不行了
