### ISSUE TITLE
请问下是否可以取消分页呢，直接显示出来所有文件呢？

### ISSUE THREAD

**Issue by piaoyun** [WangNingkai/OLAINDEX#200]
![QQ截图20190720151857](https://user-images.githubusercontent.com/3724475/61575713-c7fbdd80-ab01-11e9-8a80-53ca5609172f.png)

默认就显示出来所有文件内容呢。不想有分页呢

**Comment by WangNingkai** [comment]
如果文件较多的话，不建议全部展开。全部的话可以在连接后面添加参数limit为每页显示的数量

**Comment by sakuramisaki** [comment]
> 如果文件较多的话，不建议全部展开。全部的话可以在连接后面添加参数limit为每页显示的数量

建议增加每页展示数目的选项，每次都要用?limit=数字的话，还是有点小麻烦。
