### ISSUE TITLE
请问下怎么调整文件名和修改时间，大小之间的距离呢

### ISSUE THREAD

**Issue by piaoyun** [WangNingkai/OLAINDEX#201]
文件名显示不完全呢。怎么修改下这几个的距离呢

![ola](https://user-images.githubusercontent.com/3724475/61923357-358e8a80-af96-11e9-987b-f9b31eccbaaf.png)

还有个，图中的修改时间，月份怎么弄成数字显示。不要字母显示呢

**Comment by piaoyun** [comment]
http://piaoyun.online/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/Windows10/yaya141319

**Comment by WangNingkai** [comment]
此处直接修改 `\resources\views\default\one.blade.php` 和`\resources\views\default\one.blade.php `目录下相应的代码即可
