### ISSUE TITLE
新功能建议，是否可以针对目录层次较深的，生成短网址名称

### ISSUE THREAD

**Issue by piaoyun** [WangNingkai/OLAINDEX#202]
http://piaoyun.online/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/Windows10/yaya141319/%E7%AE%80%E4%B8%AD%2018945.1001%20Windows%2010%20%E4%BC%81%E4%B8%9A%E7%89%88%20G%20Insider%20Preview%20%28x64%29

这个是一个访问地址

是否可以生成

文件夹：
http://piaoyun.online/s/123123

文件：
http://piaoyun.online/d/123123

这种访问地址。

后面的123123是随机生成。谢谢

**Comment by WangNingkai** [comment]
这个需要与数据库关联、可以考虑，后期可以加上，作为分享短链
