### ISSUE TITLE
宝塔安装的时候错误（之前有安装成功过）

### ISSUE THREAD

**Issue by 45005894** [WangNingkai/OLAINDEX#204]
宝塔SSH，求教作者，能知道我哪里出问题了吗

Last login: Mon Jul 29 13:19:10 2019 from localhost

[root@pch18-baota1 ~]#
[root@pch18-baota1 ~]# cd /www/wwwroot/ns.koit.xyz
[root@pch18-baota1 ns.koit.xyz]# git clone https://github.com/WangNingkai/OLAINDEX.git tmp
Cloning into 'tmp'...
remote: Enumerating objects: 8141, done.
remote: Total 8141 (delta 0), reused 0 (delta 0), pack-reused 8141
Receiving objects: 100% (8141/8141), 2.48 MiB | 595.00 KiB/s, done.
Resolving deltas: 100% (5219/5219), done.
[root@pch18-baota1 ns.koit.xyz]# mv tmp/.git .
[root@pch18-baota1 ns.koit.xyz]# rm -rf tmp
[root@pch18-baota1 ns.koit.xyz]# git reset --hard
HEAD is now at a6d5509 fix:缩略图bug
[root@pch18-baota1 ns.koit.xyz]# cp database/database.sample.sqlite database/database.sqlite
[root@pch18-baota1 ns.koit.xyz]# composer install -vvv
PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0
PHP Warning:  putenv() has been disabled for security reasons in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php on line 149

Warning: putenv() has been disabled for security reasons in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php on line 149
PHP Warning:  putenv() has been disabled for security reasons in phar:///usr/bin/composer/bin/composer on line 57

Warning: putenv() has been disabled for security reasons in phar:///usr/bin/composer/bin/composer on line 57
Reading ./composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid

  [ErrorException]
  putenv() has been disabled for security reasons

Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Util/Git.php:300
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 putenv() at phar:///usr/bin/composer/src/Composer/Util/Git.php:300
 Composer\Util\Git::cleanEnv() at phar:///usr/bin/composer/src/Composer/Package/Version/VersionGuesser.php:100
 Composer\Package\Version\VersionGuesser->guessGitVersion() at phar:///usr/bin/composer/src/Composer/Package/Version/VersionGuesser.php:67
 Composer\Package\Version\VersionGuesser->guessVersion() at phar:///usr/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:88
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/bin/composer/src/Composer/Factory.php:351
 Composer\Factory->createComposer() at phar:///usr/bin/composer/src/Composer/Factory.php:576
 Composer\Factory::create() at phar:///usr/bin/composer/src/Composer/Console/Application.php:345
 Composer\Console\Application->getComposer() at phar:///usr/bin/composer/src/Composer/Console/Application.php:458
 Composer\Console\Application->getPluginCommands() at phar:///usr/bin/composer/src/Composer/Console/Application.php:156
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:61
 require() at /usr/bin/composer:24

[root@pch18-baota1 ns.koit.xyz]#

**Comment by 45005894** [comment]
禁用函数 我都删了（按照教程里写的）

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/62941949-d50ea280-be09-11e9-8b9d-a0b491dcda22.png)
`putenv` 最近宝塔新禁用的函数，建议打开

**Comment by 45005894** [comment]
> ![image](https://user-images.githubusercontent.com/23030927/62941949-d50ea280-be09-11e9-8b9d-a0b491dcda22.png)
> `putenv` 最近宝塔新禁用的函数，建议打开

哈哈 谢谢大佬 前些天我找过你了 关于那个heroku部署的

**Comment by Mlxxs** [comment]
这里我把system打开就好了
