### ISSUE TITLE
Composer install 后500

### ISSUE THREAD

**Issue by oasis1ee** [WangNingkai/OLAINDEX#205]
### 1. 该问题的重现步骤是什么？
Composer install -vvv
删除vendor后再次composer install
### 2. 你期待的结果是什么？实际看到的又是什么？
安装界面；两次均500
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.15
- PHP 版本：7.2
- OLAINDEX 版本：latest
- 浏览器版本：chrome  75.0.3770.142

[//]: # (如有图片请附上截图)

**Comment by 45005894** [comment]
这个问题我遇到过，我用的宝塔，我也是网上看到的方法。

执行php artisan config:cache后即可正常在浏览器配置。可能可以解决你的问题。

**Comment by WangNingkai** [comment]
目前看 因该是刷新缓存，宝塔给storage目录的权限不足造成的 ，可以该缓存为memcahced或者redis

**Comment by oasis1ee** [comment]
已解决 谢谢
