### ISSUE TITLE
无法连续看图

### ISSUE THREAD

**Issue by ma3252788** [WangNingkai/OLAINDEX#207]
### 1. 该问题的重现步骤是什么？
一个目录下多个图片，想要连续看图，但是无法实现
### 2. 你期待的结果是什么？实际看到的又是什么？
希望有灯箱效果，或者点击上一张/下一张进行切换，现在是只能返回列表之后再点击查看
### 3. 问题出现的环境
最新版程序
- 操作系统版本：
CentOS Linux 7.6.1810 (Core)
- Apache/NGINX 版本：
Nginx 1.15.10
- PHP 版本：
7.3
- OLAINDEX 版本：
v3.2.1
- 浏览器版本：
版本 73.0.3683.103（正式版本） （64 位）

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/62941810-852fdb80-be09-11e9-93e2-84caf1c31bd6.png)

![image](https://user-images.githubusercontent.com/23030927/62941849-9a0c6f00-be09-11e9-854f-fda3b252ff64.png)


最新4.0支持预览 ，左右滑动查看
