### ISSUE TITLE
图片文件夹报错500

### ISSUE THREAD

**Issue by fxzxmicah** [WangNingkai/OLAINDEX#209]
### 1. 该问题的重现步骤是什么？
打开一个存放图片的文件夹。
### 2. 你期待的结果是什么？实际看到的又是什么？
正常显示。报错500
### 3. 问题出现的环境

- 操作系统版本：CentOS Linux 7.6.1810
- Apache/NGINX 版本：Apache 2.4.39
- PHP 版本：7.2
- OLAINDEX 版本：4.0
- 浏览器版本：Microsoft Edge (chromium)

[//]: # (如有图片请附上截图)
**报错信息：**
Undefined offset: 0 (View: /www/wwwroot/service/disk/resources/views/default/one.blade.php) {"userId":2,"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 (View: /www/wwwroot/service/disk/resources/views/default/one.blade.php) at /www/wwwroot/service/disk/storage/framework/views/fef7d651169d49e10fb852ebdf568790427427b9.php:267, ErrorException(code: 0): Undefined offset: 0 at /www/wwwroot/service/disk/storage/framework/views/fef7d651169d49e10fb852ebdf568790427427b9.php:267)

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/0ff0e5fb388992d0e1e73dbd082171ae06100636

**Comment by fxzxmicah** [comment]
此问题已解决
