### ISSUE TITLE
如何修改视频播放器默认尺寸

### ISSUE THREAD

**Issue by findwisdom** [WangNingkai/OLAINDEX#21]
默认尺寸为
 .dplayer-video-wrap .dplayer-video {
    width: 100%;
    height: 100%;
这个参数在源码里没有
希望能改为
 .dplayer-video-wrap .dplayer-video {
    width: 100%;
    height: 640px;
这样对竖屏的视频在电脑端有良好的显示

**Comment by WangNingkai** [comment]
这个可以直接添加的，我这里默认的，有时间我改一下吧

**Comment by WangNingkai** [comment]
@findwisdom 已改
