### ISSUE TITLE
新功能建议，是否有考虑增加多网盘同时绑定，以及普通用户注册访问权限等功能。

### ISSUE THREAD

**Issue by 45005894** [WangNingkai/OLAINDEX#211]
作者你好，OLAINDEX项目非常不错，以后是否会考虑增加多网盘同时绑定，以及普通用户注册登录访问权限等功能。

**Comment by WangNingkai** [comment]
你好 olaindex 定位简单 ，多网盘和用户系统目前暂时不会加进入，不过欢迎提交pull request ，新开分支、一起开发促进进步
