### ISSUE TITLE
下载相关

### ISSUE THREAD

**Issue by ghost** [WangNingkai/OLAINDEX#216]
Onedrive API 给的那个下载直链似乎是被墙的还是怎么的，反正有些网络不能正常访问，想知道是否可以实现类似CDN加速域名的方式，在给出下载直链的时候支持使用自定义的域名，这样我可以提供反代域名来提供下载
谢谢

**Comment by fxzxmicah** [comment]
这感觉超出了这个项目的范围了吧

**Comment by WangNingkai** [comment]
微软的接口倒是会是不是抽风的，不过也不排除接口限流
