### ISSUE TITLE
关于添加媒体文件调用本地播放器的按钮

### ISSUE THREAD

**Issue by marxvr** [WangNingkai/OLAINDEX#217]
- 原理：通过url schema调用本地播放器
<img width="497" alt="reg" src="https://user-images.githubusercontent.com/17882380/64093120-a4c37f80-cd89-11e9-8e4b-de168101f580.png">
- 例子：potplayer://http://sicko.com/test.mkv
<img alt="file" src="https://user-images.githubusercontent.com/17882380/64093701-fd941780-cd8b-11e9-928b-b82429d87735.gif">

- 布局：
<img width="856" alt="dir" src="https://user-images.githubusercontent.com/17882380/64093129-b442c880-cd89-11e9-8a17-12f29158bd21.png">
<img width="869" alt="file" src="https://user-images.githubusercontent.com/17882380/64093130-b573f580-cd89-11e9-8768-5199eb8b247f.png">

- 设计：
通过识别浏览器UA，调用对应的常用播放器。
例如安卓的调用mxplayer，ios的可以调用nplayer等

也可以在管理后台添加设置不同平台的选项，
提供常用播放器的url schema和自定义方式选择需要的播放器

- ps: 希望大佬有空的时候能更新一下OLAINDEX的docker镜像

**Comment by WangNingkai** [comment]
好想法 ，有空可以搞一下 😀 能协助提交修改更好
