### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by 5sir** [WangNingkai/OLAINDEX#219]
安装步骤 点击保存后 绑定账号界面栏目内都是空白
https://ae01.alicdn.com/kf/Ha85b84a9313f403e88f2b083817b7433g.png

**Comment by wmgx** [comment]
我也是这个问题，请问解决了吗？

**Comment by Smthie** [comment]
切到程序目录，执行`chmod 777 -R storage/* database/*`

**Comment by yimshing** [comment]
把除了.开头的文件夹之外其它文件夹的权限全部重新改为755就好了。你可以都试试。
@5sir @wmgx

**Comment by wmgx** [comment]
问题解决了，谢谢

**Comment by WangNingkai** [comment]
确实宝塔安装 会导致目录权限不足，这要涉及到database 和storage目录
