### ISSUE TITLE
debug模式无法关闭

### ISSUE THREAD

**Issue by yjiaz** [WangNingkai/OLAINDEX#223]
### 1. 该问题的重现步骤是什么？
.env文件中,APP_ENV=production, APP_DEBUG=false，但是网站右下角都有Tracy的信息栏，无论是否有登陆admin账户。在网页后台似乎也没有看到相关的设置项。

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Nginx 1.14.2
- PHP 版本：7.3.5
- OLAINDEX 版本：git clone最新的版本
- 浏览器版本：Chrome 77.0.03865.50

[//]: # (如有图片请附上截图)
![20191004235951](https://tva3.sinaimg.cn/large/005GRCB4ly1g7nc5loc9lj31f105twes.jpg)
![20191005000431](https://tvax3.sinaimg.cn/large/005GRCB4ly1g7nc6twykwj30se0jgjsj.jpg)

**Comment by WangNingkai** [comment]
执行 `php artisan config:cache` 重新生成缓存
