### ISSUE TITLE
test分支新改动

### ISSUE THREAD

**Issue by lmjzhizun** [WangNingkai/OLAINDEX#226]
看到test分支的commit很期待,而且默认数据库换回了mysql,但是自己部署完后登陆时报服务器内部错误,能透露一下大概是么时候能发布到master吗

**Comment by WangNingkai** [comment]
test 分支，目前仍在开发，不建议部署。
主要调整已下一个方面：
1.优化部署流程，更加自动化 
2.优化绑定流程
3.界面重写（前后端分离）更加美观 
4.添加docker 支持 
5.如果时间允许，会添加本地文件目录支持
 
初步预计年底吧

**Comment by lmjzhizun** [comment]
> test 分支，目前仍在开发，不建议部署。
> 主要调整已下一个方面：
> 1.优化部署流程，更加自动化
> 2.优化绑定流程
> 3.界面重写（前后端分离）更加美观
> 4.添加docker 支持
> 5.如果时间允许，会添加本地文件目录支持
> 
> 初步预计年底吧

hh,好的,等待~
