### ISSUE TITLE
不知道能不能用这个dplayer-p2p播放器

### ISSUE THREAD

**Issue by asleep2** [WangNingkai/OLAINDEX#23]
![1027121](https://user-images.githubusercontent.com/39230916/47599535-d8ec4800-d9e2-11e8-8f94-a4689c96b214.jpg)

**Comment by ferocknew** [comment]
的确，媒体文件应该搞个在线播放

**Comment by WangNingkai** [comment]
@asleep2 哪一种媒体播放

**Comment by WangNingkai** [comment]
@ferocknew 目前的功能支持文件夹内的视频播放

**Comment by asleep2** [comment]
@WangNingkai   感觉P2P加载速度会更快一点吧。我在意两种格式，一个是 .vob(我猜这个得转码为MP4吧） 还有一个是 .flac格式，请问aplayer支持吗？

**Comment by WangNingkai** [comment]
@asleep2 视频的来源都是来自OneDrive，速度取决于链接微软服务器的速度，这个是不支持p2p 的，关于格式的支持，查看相应播放器支持情况就知道了。
