### ISSUE TITLE
图片页面的引用链接用浏览器访问也会触发下载，而不是直接访问查看图片

### ISSUE THREAD

**Issue by lgq1349422030** [WangNingkai/OLAINDEX#231]
### 1. 该问题的重现步骤是什么？
打开一个图片页面，比如[这个](https://one.foolyou.top/show/%E8%A1%A8%E6%83%85%E5%8C%85/menhera%20chan%E8%A1%A8%E6%83%85%E5%8C%85/Menhera-chan/1.jpg)，然后点击[下载]会触发了下载操作，但是如果点击查看原图后的图片上右键在新标签页打开图片也会下载，而不是直接新开标签页显示图片。
也就是
```html
https://one.foolyou.top/down/%E8%A1%A8%E6%83%85%E5%8C%85/menhera%20chan%E8%A1%A8%E6%83%85%E5%8C%85/Menhera-chan/1.jpg
https://one.foolyou.top/view/%E8%A1%A8%E6%83%85%E5%8C%85/menhera%20chan%E8%A1%A8%E6%83%85%E5%8C%85/Menhera-chan/1.jpg
```
这两个`/down/***`和`/view/***`贴到浏览器上后实际上好像并没有什么区别。。。
用markdown来测试也都可以正常显示图片。。
### 2. 你期待的结果是什么？实际看到的又是什么？
`/view/***`开头的链接用浏览器访问能够直接查看图片而不是下载

**Comment by 2moe** [comment]
现在的版本的图片加载会出现404 Not Found  
比如demo站 https://share.imwnk.cn/show/Hosting/2019/05/11/JxXz1Nua/313091-512.png
我用的nginx1.17 也是404 Not Found，不是防盗链配置的问题。

**Comment by lgq1349422030** [comment]
> 现在的版本的图片加载会出现404 Not Found
> 比如demo站 https://share.imwnk.cn/show/Hosting/2019/05/11/JxXz1Nua/313091-512.png
> 我用的nginx1.17 也是404 Not Found，不是防盗链配置的问题。

我自己搭建的没有出现404问题。。。
