### ISSUE TITLE
求教，laravel这种框架如何在二级目录下正常使用呢？

### ISSUE THREAD

**Issue by fxzxmicah** [WangNingkai/OLAINDEX#232]
我想在同一域名的二级目录下安装多个olaindex，有没有什么可行的办法呢？

**Comment by fxzxmicah** [comment]
是不是只有反代一条路呢？

**Comment by fxzxmicah** [comment]
此外，为什么不支持直接访问public? 这样的话就没法在虚拟主机上用了。

**Comment by fxzxmicah** [comment]
已解决二级目录问题，需要方法的可以在这里继续回复。

**Comment by fxzxmicah** [comment]
自己修改后支持二级目录的版本:
https://dev.azure.com/Fxzx-Studio/OLINDEX_modify/

**Comment by mboyka** [comment]
大佬怎么解决的？

**Comment by luhanfei** [comment]
我放进二级目录访问就404

**Comment by JokerMas** [comment]
> 已解决二级目录问题，需要方法的可以在这里继续回复。

求解决方法

**Comment by fxzxmicah** [comment]
@JokerMas @luhanfei @mboyka 将目录下server.php改为index.php，另外在删除js函数deleteItem（位于one.blade.php）将window.open中/file/delete/改为/你的目录/file/delete/（这样改可以修复删除时的bug，但是删除后会提示500，但实际上已经删除成功了，这个问题出在哪我还不清楚）。

**Comment by JokerMas** [comment]
> @JokerMas @luhanfei @mboyka 将目录下server.php改为index.php，另外在删除js函数deleteItem（位于one.blade.php）将window.open中/file/delete/改为/你的目录/file/delete/（这样改可以修复删除时的bug，但是删除后会提示500，但实际上已经删除成功了，这个问题出在哪我还不清楚）。
谢谢，我用以下代码解决了
location /路径/public/ {
    if (!-e $request_filename){
        rewrite ^/路径/public/(.*)$ /路径/public/index.php?s=$1 last;
    }
