### ISSUE TITLE
在宝塔安装之后，没有什么特别的反映，但是打开网页就是 502.

### ISSUE THREAD

**Issue by elizen** [WangNingkai/OLAINDEX#235]
在宝塔 CentOS 上按照部署一步步完成，没有发现什么报错，但是打开网页就是 502...

`[root@elizen file.elizen.me]# php artisan od:install
   ____  __    ___    _____   ______  _______  __
  / __ \/ /   /   |  /  _/ | / / __ \/ ____/ |/ /
 / / / / /   / /| |  / //  |/ / / / / __/  |   / 
/ /_/ / /___/ ___ |_/ // /|  / /_/ / /___ /   |  
\____/_____/_/  |_/___/_/ |_/_____/_____//_/|_|
Application cache cleared!
Please make sure you have rights to configure!
chmod -R 755 storage/* && chown -R www:www *

 Bind Domain(For Authorize):
 > https://file.elizen.me

**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.
username:[ admin ] email:[ admin@admin.com ] password:[ 12345678 ]
All Done!`

这是不是表示成功了？

另外安装的时候，会有类似的问题：

  - Installing webmozart/path-util (2.3.0): Reading /root/.cache/composer/files/webmozart/path-util/23c60f5e89c94d6fd8d266b3361b068fcb77c24b.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/www/wwwroot/file.elizen.me/vendor/webmozart/path-util/6a4e10c51879d3de1863014701d52b0b' -d '/www/wwwroot/file.elizen.me/vendor/composer/7d6f1dd1'
    REASON: Required by the root package: Install command rule (install webmozart/path-util 2.3.0)

**Comment by fxzxmicah** [comment]
你运行目录指向public了吗？
