### ISSUE TITLE
世纪互联绑定失败，提示500，之后刷新就一直显示404

### ISSUE THREAD

**Issue by yahinstudio** [WangNingkai/OLAINDEX#238]
### 1. 该问题的重现步骤是什么？
绑定世纪互联（国内版）账号后
### 2. 你期待的结果是什么？实际看到的又是什么？
希望能绑定成功，但是第一次绑定后提示500，刷新就一直404了，之后重新绑定也一直是404
### 3. 问题出现的环境

- 操作系统版本：
- NGINX 版本：1.16.0
- PHP 版本：7.3
- OLAINDEX 版本：教程中使用git安装的版本
- 浏览器版本：chrome最新版

[//]: # (如有图片请附上截图)
![QQ截图20191219194022](https://user-images.githubusercontent.com/44126767/71170999-ad3bb980-2297-11ea-9d5f-1797671bb024.png)
![QQ截图20191219194122](https://user-images.githubusercontent.com/44126767/71171000-ad3bb980-2297-11ea-9e74-9e66e315ca21.png)
![QQ截图20191219194147](https://user-images.githubusercontent.com/44126767/71171001-ad3bb980-2297-11ea-894a-3e313f6118d9.png)

**Comment by yahinstudio** [comment]
还有一个问题，就是好像无法通过issue 40的方式切换到世纪互联版本，不知道是不是这个问题
![QQ图片20191219195937](https://user-images.githubusercontent.com/44126767/71171992-16243100-229a-11ea-9e58-202090b186a9.png)

**Comment by yahinstudio** [comment]
![QQ截图20191219201557](https://user-images.githubusercontent.com/44126767/71172896-656b6100-229c-11ea-8287-1c8daf50e5e6.png)
bang绑定后提示500错误，之后刷新都是404

**Comment by mn19941219** [comment]
错误500：将网站目录下的/storage权限设为777，如果用宝塔装的，建议用宝塔手动调整一次。
-switch开关：貌似这个开关在4.0版本中去掉了

**Comment by cjwddtc** [comment]
404怎么解决的？我用的3.2.1版本，switch会报错，循环包--yes的错误，把报错那一行（就是调reset哪一行）删掉，手动reset，然后选择国内版绑定就会报404。

**Comment by cjwddtc** [comment]
我服了，那个url应该是index.php/oauth，直接oauth不行，apache里面设置了默认文档也不行

**Comment by Latezly** [comment]
请问这个问题解决了吗
