### ISSUE TITLE
可以绕过密码访问加密目录

### ISSUE THREAD

**Issue by MrPangzhan** [WangNingkai/OLAINDEX#239]
### 1. 该问题的重现步骤是什么？
正常访问 pan.xxx.com/home 显示的根目录 ，根目录下的子目录加密，例如：/Movie是加密的。正常的通过首页点击链接访问这个加密的目录是需要输入密码，（pan.xxx.com/home/Movie）在浏览器的地址栏将加密的目录名称更改一个大写或小写即可绕过密码限制，（pan.xxx.com/home/MoviE）不管更改那个字母只要和加密目录有点区别就可以绕过密码。中文目录名未测试。还有在后台隐藏的目录，知道了目录名可以在浏览器直接访问，只是前端看不到。

### 2. 你期待的结果是什么？实际看到的又是什么？
这个绕过密码的问题不解决，加密就没有意义。

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx 1.6
- PHP 版本：7.3
- OLAINDEX 版本：master Latest  e27ff0e
- 浏览器版本：Safari 、Google Chrome

[//]: # (如有图片请附上截图)

**Comment by 19860413** [comment]
确实这样，暂时加密的文件夹用中文吧。

**Comment by MrPangzhan** [comment]
> 确实这样，暂时加密的文件夹用中文吧。

目前也只能暂时这样了，等大佬修复吧

**Comment by 2moe** [comment]
我遇到了相同的问题，正准备发issue，刚好看到你的帖子。  
- 操作系统版本：Debian 10 buster
- Apache/NGINX 版本：Nginx 1.17.7
- PHP 版本：7.3.13
- OLAINDEX 版本：Branch:[master](https://github.com/WangNingkai/OLAINDEX/tree/master) , Commit: [e27ff0e](https://github.com/WangNingkai/OLAINDEX/commit/e27ff0e2482da3b8f6028d7bd9df0c7507559ea4)
- 浏览器版本：Chrome 79.0.3945 stable

**Comment by 2moe** [comment]
隐藏目录也存在相同问题，比如收我隐藏了/images
直接访问xx.com/home/images 可以正常隐藏。
但是访问xx.com/home/imageS  却能绕开这种限制。
@WangNingkai 希望大佬能修复这个bug💕

**Comment by KawaiiZapic** [comment]
一个很临时很简单的解决方案:
在`app/Http/Middleware/HandleEncryptDir.php`里:
在Line 24左右,找到`$requestPath = $request->route()->parameter('query', '/');`
,修改为:`$requestPath = strtolower($request->route()->parameter('query', '/'));`
然后向下,在Line 31左右,找到`$encryptPath = explode('>', $path)[1];`,修改为:`$encryptPath = strtolower(explode('>', $path)[1]);`

这样可以解决绕过加密的问题.
可以照葫芦画瓢解决隐藏目录的问题.
*我这里隐藏目录出现了bug,没法验证.
