### ISSUE TITLE
文件显示不全

### ISSUE THREAD

**Issue by lulu1072502** [WangNingkai/OLAINDEX#24]
目录下有1300+文件,只显示了10个分页

**Comment by WangNingkai** [comment]
@lulu1072502 清理下缓存再试下呢

**Comment by lulu1072502** [comment]
https://nsp.oldkk.top
你可以看一下
我清理过缓存了
只显示了10页
![lily_screenshot_1540651167](https://user-images.githubusercontent.com/10289483/47605448-2dbaad80-da39-11e8-9937-288c98b4c5d8.png)

**Comment by WangNingkai** [comment]
@lulu1072502 已修复，微软超过200条数据 被分页了，我这里重新改了一下，更新一下源码master

**Comment by lulu1072502** [comment]
现在可以正常显示了,但是出现新问题,无法加密了.password文件存在

**Comment by WangNingkai** [comment]
@lulu1072502 我这边正常，查看你那边文件是否有问题
