### ISSUE TITLE
执行git reset --hard后，提示HEAD is now at e27ff0e update composer.lock

### ISSUE THREAD

**Issue by ulifuqiang** [WangNingkai/OLAINDEX#240]
### 1. 该问题的重现步骤是什么？
安装中，执行git reset --hard后，提示HEAD is now at e27ff0e update composer.lock
### 2. 你期待的结果是什么？实际看到的又是什么？
![QQ截图20200107155350](https://user-images.githubusercontent.com/25083314/71878168-f3cd5700-3165-11ea-8792-47ffcd3af370.png)

出现这个问题应该怎么处理呀，一直安装不上。

### 3. 问题出现的环境

- 操作系统版本：centos-7.7.1908

- PHP 版本：php7.3

[//]: # (如有图片请附上截图)

**Comment by 19860413** [comment]
没影响，继续进行下一步。
