### ISSUE TITLE
无法显示 README.md 内容

### ISSUE THREAD

**Issue by kongwy** [WangNingkai/OLAINDEX#250]
### 1. 该问题的重现步骤是什么？
按照文档安装后打开任何包含 README.md 的目录页面。

### 2. 你期待的结果是什么？实际看到的又是什么？
应该在文件列表下方显示 README 文件内容。实际显示为空。

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 18.04.2
- Apache/NGINX 版本：nginx/1.14.0
- PHP 版本：PHP 7.2.24
- OLAINDEX 版本：v4.0
- 浏览器版本：Safari / Brave

[//]: # (如有图片请附上截图)

<img width="513" alt="CleanShot 2020-01-28 at 23 22 11@2x" src="https://user-images.githubusercontent.com/9990631/73277383-0b5ba500-4225-11ea-8cbd-df724b84d3ea.png">

**Comment by RenBaoshuo** [comment]
同问

**Comment by RenBaoshuo** [comment]
已解决，解决方法：使用[https://github.com/WangNingkai/OLAINDEX/releases](https://github.com/WangNingkai/OLAINDEX/releases)里面的稳定版（3.2.1）即可

**Comment by kongwy** [comment]
v3.2.1 的安装好像和现在 v4.0 有点出入，而且如果是 v4.0 有这个问题那还是应该修复的吧……

**Comment by kongwy** [comment]
> 已解决，解决方法：使用 https://github.com/WangNingkai/OLAINDEX/releases 里面的稳定版（3.2.1）即可

v3.2.1 的安装好像和现在 v4.0 有点出入，而且如果是 v4.0 有这个问题那还是应该修复的吧……

**Comment by RenBaoshuo** [comment]
> > 已解决，解决方法：使用 https://github.com/WangNingkai/OLAINDEX/releases 里面的稳定版（3.2.1）即可
> 
> v3.2.1 的安装好像和现在 v4.0 有点出入，而且如果是 v4.0 有这个问题那还是应该修复的吧……

但4.0现在还在开发阶段，如果要追求稳定的话只能是选择 `v3.2.1` 。

不过这确实是个问题......

**Comment by renbaoshuo** [comment]
https://github.com/WangNingkai/OLAINDEX/pull/256
