### ISSUE TITLE
Test版 绑定时出错

### ISSUE THREAD

**Issue by huxubo** [WangNingkai/OLAINDEX#260]
### 1. 该问题的重现步骤是什么？
绑定时返回
{"code":500,"message":"array_merge(): Expected parameter 1 to be an array, string given","data":[]}
### 2. 你期待的结果是什么？实际看到的又是什么？
是什么原因造成的？
### 3. 问题出现的环境

- 操作系统版本：CentOS 7.6
- Apache/NGINX 版本：Nginx -Tengine2.2.4(2.3.2)
- PHP 版本：7.3
- OLAINDEX 版本：test
- 浏览器版本：Chrome 79.0.3945.130（正式版本） （64 位）

[//]: # (如有图片请附上截图)

**Comment by ulifuqiang** [comment]
@huxubo 能问下怎么安装的test版本吗

**Comment by huxubo** [comment]
> @huxubo 能问下怎么安装的test版本吗

cd web目录
git clone -b test https://github.com/WangNingkai/OLAINDEX.git tmp 
mv tmp/.git . 
rm -rf tmp 
git reset --hard 
composer install -vvv # 这里确保已成功安装 composer ，如果报权限问题，建议给予用户完整权限。
chmod -R 777 storage 
chown -R www:www * # 此处 www 根据服务器具体用户组而定
php artisan install # 此处绑定域名需根据实际域名谨慎填写（包含http/https）

**Comment by ulifuqiang** [comment]
@huxubo 执行 php artisan install 没有让写域名呢？
