### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by caly5144** [WangNingkai/OLAINDEX#27]
您好，我安装进行到最后一步，申请过id机密并且填好保存后，跳转提示登录office账户，然后就是“无法访问此网站”，请问是怎么回事呢

**Comment by WangNingkai** [comment]
@caly5144 截图，贴错误地方

**Comment by caly5144** [comment]
就是这一步填好之后（由于现在输入域名直接就到office登录界面，所以借用了你的图）

![image](https://user-images.githubusercontent.com/27693473/47786365-8e522f00-dd46-11e8-8665-8c54cc06e04e.png)

会跳转到登陆界面

![image](https://user-images.githubusercontent.com/27693473/47786334-724e8d80-dd46-11e8-9cc9-24223d797d91.png)

登录后就显示连接失败

![image](https://user-images.githubusercontent.com/27693473/47786460-d1ac9d80-dd46-11e8-8e32-6d1add1c46c5.png)

**Comment by WangNingkai** [comment]
回调地址是域名+oauth ，就是 https://ycyh.info/oauth 确定填写正确了吗

**Comment by WangNingkai** [comment]
我看到你这个报错是网络的原因，如果是我的应用有问题，会报错500，你尝试下php artisan reset:app 重置安装

**Comment by caly5144** [comment]
重新装了一遍不知道怎么就成功了，感谢您的指导

**Comment by caly5144** [comment]
对了还有一个问题，为什么我不能在浏览器中播放flv格式的视频啊，是浏览器的问题吗

**Comment by WangNingkai** [comment]
默认用的微软接口将视频转换为dash流，如果它不能转换就没办法了，flv现在不是主流的视频格式了

**Comment by caly5144** [comment]
又有一个问题……
点开缩略图后，不能显示大图
![image](https://user-images.githubusercontent.com/27693473/47802220-c4a1a580-dd6a-11e8-8236-e24f776badb1.png)
点查看按钮，会有这个提示
![image](https://user-images.githubusercontent.com/27693473/47802250-da16cf80-dd6a-11e8-8703-1a580ccc48f8.png)
