### ISSUE TITLE
heroku数据库迁移问题

### ISSUE THREAD

**Issue by Kwok1am** [WangNingkai/OLAINDEX#271]
按博客中教程对按.env文件配置heroku环境变量
![image](https://user-images.githubusercontent.com/51690055/80270296-39983600-86e9-11ea-9897-d160b18a5164.png)

迁移数据库时候报错
![image](https://user-images.githubusercontent.com/51690055/80270316-5df41280-86e9-11ea-9502-5c3358d2cd35.png)

如果使用msql数据库要怎么填写数据呢

**Comment by WangNingkai** [comment]
不建议heroku使用sqlite 会导致数据丢失
