### ISSUE TITLE
安装后一直403错误

### ISSUE THREAD

**Issue by sxgpyjg** [WangNingkai/OLAINDEX#28]
Something error:

403 Forbidden

You don't have permission to browse.

Please check or try again later.

hostname: leyun-free

Generated by kangle/3.5.10.1.

**Comment by WangNingkai** [comment]
不贴图我也不知道你哪里有问题

**Comment by sxgpyjg** [comment]
Something error:

403 Forbidden

You don't have permission to browse.

Please check or try again later.

hostname: leyun-free

Generated by kangle/3.5.10.1.

**Comment by WangNingkai** [comment]
我看到是你的面板报的错，请确定你的环境配置好了，包括nginx配置填写正确 @sxgpyjg

**Comment by sxgpyjg** [comment]
我是申请好域名空间，上传到乐云空间，

打开网址就是报错403

**Comment by sxgpyjg** [comment]
小白一个不懂怎样配置，只是按照装oneindex的方法装了一遍，请大佬明教

**Comment by WangNingkai** [comment]
wiki里已经很详细了 @sxgpyjg
