### ISSUE TITLE
请问下在同一台服务器上面，搭建2个olaindex么？

### ISSUE THREAD

**Issue by piaoyun** [WangNingkai/OLAINDEX#280]
搭建的时候，都是开了2个网站，来搭建，不同的域名前缀

a.xxx.xxx
b.xxx.xxx

这样访问，但是发现第二个始终会出现莫名其妙的错误呢。

**Comment by WangNingkai** [comment]
如果共用缓存系统（如redis，memcached）的话，修改env文件的app_name，其它不变
