### ISSUE TITLE
onedrive出现一直循环登陆的情况

### ISSUE THREAD

**Issue by Yuzheng-Chen** [WangNingkai/OLAINDEX#283]
### 1. 该问题的重现步骤是什么？
在输入密钥确定绑定之后，需要第二次登陆OneDrive（第一次是获取密钥）。
### 2. 你期待的结果是什么？实际看到的又是什么？
输入账号密码后，原本应该正常绑定成功，但是却跳回Microsoft的账号输入，无限循环。
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.18.0
- PHP 版本：7.2
- OLAINDEX 版本：v4.0
- 浏览器版本：试过很多设备的不同浏览器（火狐，ie，chrome）

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/63089990/83329744-cb352d80-a2bd-11ea-8bef-35c25d60f5ca.png)

**Comment by irainerc** [comment]
同

**Comment by xiaobei206** [comment]
一样的情况，国际版，世纪互联版没有问题
