### ISSUE TITLE
How to add a website favicon.ico?

### ISSUE THREAD

**Issue by senup** [WangNingkai/OLAINDEX#286]
- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：7.4
- OLAINDEX 版本：lasted
- 浏览器版本：chrome 78.0.3904

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
修改public目录下的favicon即可 @senup

**Comment by senup** [comment]
> 修改public目录下的favicon即可 @senup

谢谢！很有帮助！
