### ISSUE TITLE
5.0版没有设置默认密码的选项，首页500错误。

### ISSUE THREAD

**Issue by TUT123456** [WangNingkai/OLAINDEX#288]
### 1. 该问题的重现步骤是什么？
安装5.0版本
### 2. 你期待的结果是什么？实际看到的又是什么？
首页显示500错误
### 3. 问题出现的环境

- 操作系统版本：ununtu
- Apache/NGINX 版本：Nginx 1.16.1
- PHP 版本：7.4
- OLAINDEX 版本：5.0
- 浏览器版本：edge 83

[//]: # (如有图片请附上截图)
以下是500错误的日志
The HTTP client sent back an invalid response [{"file":"/www/wwwroot/onedrive.domain.xyz/app/Service/GraphClient.php","line":94,"function":"execute","class":"App\\Service\\GraphRequest","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/app/Service/OneDrive.php","line":45,"function":"execute","class":"App\\Service\\GraphClient","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/app/Service/OneDrive.php","line":109,"function":"_request","class":"App\\Service\\OneDrive","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/app/Http/Controllers/HomeController.php","line":60,"function":"fetchItem","class":"App\\Service\\OneDrive","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Cache/Repository.php","line":383,"function":"App\\Http\\Controllers\\{closure}","class":"App\\Http\\Controllers\\HomeController","type":"::"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php","line":383,"function":"remember","class":"Illuminate\\Cache\\Repository","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php","line":261,"function":"__call","class":"Illuminate\\Cache\\CacheManager","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/app/Http/Controllers/HomeController.php","line":61,"function":"__callStatic","class":"Illuminate\\Support\\Facades\\Facade","type":"::"},{"function":"__invoke","class":"App\\Http\\Controllers\\HomeController","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Controller.php","line":54,"function":"call_user_func_array"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php","line":45,"function":"callAction","class":"Illuminate\\Routing\\Controller","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php","line":239,"function":"dispatch","class":"Illuminate\\Routing\\ControllerDispatcher","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php","line":196,"function":"runController","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":685,"function":"run","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":128,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php","line":41,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Routing\\Middleware\\SubstituteBindings","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php","line":76,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php","line":49,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\View\\Middleware\\ShareErrorsFromSession","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php","line":116,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php","line":62,"function":"handleStatefulRequest","class":"Illuminate\\Session\\Middleware\\StartSession","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Session\\Middleware\\StartSession","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php","line":37,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php","line":66,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Cookie\\Middleware\\EncryptCookies","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":687,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":662,"function":"runRouteWithinStack","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":628,"function":"runRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":617,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":165,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":128,"function":"Illuminate\\Foundation\\Http\\{closure}","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php","line":58,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Barryvdh\\Debugbar\\Middleware\\InjectDebugbar","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php","line":27,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php","line":63,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/fideloper/proxy/src/TrustProxies.php","line":57,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Fideloper\\Proxy\\TrustProxies","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":140,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":109,"function":"sendRequestThroughRouter","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/www/wwwroot/onedrive.domain.xyz/public/index.php","line":55,"function":"handle","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"}]

**Comment by suyin-long** [comment]
老哥，有5.0版本的安装教程吗？

**Comment by TUT123456** [comment]
> 老哥，有5.0版本的安装教程吗？

我猜的，直接用php artisan install 安装的，其他地方和以前的一样。

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/blob/5.0/docs/install.md

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/86547071-43041100-bf6a-11ea-8099-1ded3103a4db.png)

**Comment by suyin-long** [comment]
> > 老哥，有5.0版本的安装教程吗？
> 
> 我猜的，直接用php artisan install安装的，其他地方和以前的一样。

哦，我用他的那个宝塔安装教程试了下，不行。没试手动安装教程，回头试试。

**Comment by suyin-long** [comment]
老哥，你的500错误是这样的吗？
`SQLSTATE[HY000]: General error: 1 no such table: accounts (SQL: select "id", "remark" from "accounts" where "status" = 1)`

**Comment by TUT123456** [comment]
> 老哥，你的500错误是这样的吗？
> `SQLSTATE[HY000]: General error: 1 no such table: accounts (SQL: select "id", "remark" from "accounts" where "status" = 1)`

不是，看我贴的日志

**Comment by suyin-long** [comment]
> > 老哥，你的500错误是这样的吗？
> > `SQLSTATE[HY000]: General error: 1 no such table: accounts (SQL: select "id", "remark" from "accounts" where "status" = 1)`
> 
> 不是，看我贴的日志

我试着用手动安装的方法试了两次，都是在首页报我说的这个500错误。。。

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/86565842-2c29e280-bf9b-11ea-8fe7-2fbb8efb6296.png)
此处步骤执行的结果显示什么？

**Comment by suyin-long** [comment]
> ![图片](https://user-images.githubusercontent.com/23030927/86565842-2c29e280-bf9b-11ea-8fe7-2fbb8efb6296.png)
> 此处步骤执行的结果显示什么？

```
[root@VM-0-7-centos suyin-tools.cn]# composer run install-app
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> php artisan install
   ____  __    ___    _____   ______  _______  __
  / __ \/ /   /   |  /  _/ | / / __ \/ ____/ |/ /
 / / / / /   / /| |  / //  |/ / / / / __/  |   /
/ /_/ / /___/ ___ |_/ // /|  / /_/ / /___ /   |
\____/_____/_/  |_/___/_/ |_/_____/_____//_/|_|

v5.0.0
- Designed by IMWNK | Powered by OLAINDEX

Configuration cache cleared!
Configuration cached successfully!
Database not found,Creating...
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > Command Canceled!
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > Command Canceled!
Configuration cache cleared!
Configuration cached successfully!
default name: [ admin ]
default password: [ 123456 ]
Install Complete!
```

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/357f795d87595a18d520128f1a13c36c99f1e807 已修复
