### ISSUE TITLE
支持字幕吗？

### ISSUE THREAD

**Issue by weiyidu** [WangNingkai/OLAINDEX#3]
可以参考这篇文章
https://www.234du.com/1185.html

**Comment by WangNingkai** [comment]
感谢指导，考虑将其加入Todo

**Comment by weiyidu** [comment]
> 感谢指导，考虑将其加入Todo

在OD使用字幕会有跨域的问题

**Comment by Tiw1590** [comment]
作者可以看一下这个 不知道能不能实现https://github.com/Dador/JavascriptSubtitlesOctopus @WangNingkai

**Comment by yubanmeiqin9048** [comment]
> 感谢指导，考虑将其加入Todo

请问作者，现在已经实现这个功能了吗？
