### ISSUE TITLE
windows环境下可以安装吗？

### ISSUE THREAD

**Issue by duansheyu** [WangNingkai/OLAINDEX#30]
windows环境下可以安装吗？大佬

**Comment by WangNingkai** [comment]
可以啊，windows 本地环境吗，确保安装了php（配置好openssl扩展） + composer 环境，按照安装步骤安装，最后执行php artisan serve 就可以在127.0.0.1:8000运行

**Comment by duansheyu** [comment]
谢谢您能回复，但是用Linux安装成功后，登录Microsoft显示这个，是什么原因呢
![tim 20181102005804](https://user-images.githubusercontent.com/43491913/47866746-95f30000-de3a-11e8-8210-aee94706665a.png)

**Comment by WangNingkai** [comment]
@duansheyu 可能连接微软服务器问题也可能是账号问题，建议过后再试一下或者是重置账号再进行登录

**Comment by jiffei** [comment]
> windows环境下可以安装吗？大佬

可以安装，这是我安装成功的：https://file.jiffei.com
安装教程：https://www.jiffei.com/notes/olaindex.html
