### ISSUE TITLE
安装5.0版本 后台无法保存任何信息 500错误

### ISSUE THREAD

**Issue by 77208149** [WangNingkai/OLAINDEX#303]
### 1. 该问题的重现步骤是什么？
安装完成之后，进入后台 修改基本信息报500 添加账号报500 基本保存就是500
### 2. 你期待的结果是什么？实际看到的又是什么？
能正常修改成功
### 3. 问题出现的环境

- 操作系统版本：windows10
- Apache/NGINX 版本：1.16
- PHP 版本：7.2
- OLAINDEX 版本：5.0
- 浏览器版本：googel

[//]: # (如有图片请附上截图)
![微信截图_20200707155218](https://user-images.githubusercontent.com/37090830/86741961-5c8c8200-c06a-11ea-8819-edc6e168ec97.png)

**Comment by WangNingkai** [comment]
权限问题，文件无法读取，确保数据库路径可写 `storage/install/data`

**Comment by 77208149** [comment]
storage目录全部777权限

**Comment by 77208149** [comment]
已解决 storage/install/data/database.sample.sqlite 需要给777权限

**Comment by 77208149** [comment]
配置国内世纪互联之后 首页提示账号不存在 后台显示账号正常


![微信截图_20200707161008](https://user-images.githubusercontent.com/37090830/86744663-59929100-c06c-11ea-8dc2-3b6143bfc18d.png)

**Comment by WangNingkai** [comment]
后台将其设为主账号

**Comment by 77208149** [comment]
> 后台将其设为主账号

后台将账号设置为主账号之后 报500错误 Call to a member function getError() on null
![微信截图_20200707161900](https://user-images.githubusercontent.com/37090830/86746375-9ad77080-c06d-11ea-8c4b-2e6ebf4ce502.png)

**Comment by WangNingkai** [comment]
日志提供下呢

**Comment by 77208149** [comment]
> 日志提供下呢

![微信截图_20200707162625](https://user-images.githubusercontent.com/37090830/86747917-ad05de80-c06e-11ea-93a9-bbe4a3713c82.png)

**Comment by WangNingkai** [comment]
需要对应报错的日志

**Comment by 77208149** [comment]
> 需要对应报错的日志

![微信截图_20200707163444](https://user-images.githubusercontent.com/37090830/86749397-ce1aff00-c06f-11ea-8cc8-d9f1bd6d8674.png)

**Comment by WangNingkai** [comment]
提供的日志缺少较多，建议将管理账号私人发我，排查日志

**Comment by 77208149** [comment]
> 提供的日志缺少较多，建议将管理账号私人发我，排查日志

怎么私发给你呢

**Comment by WangNingkai** [comment]
i@ningkai.wang

**Comment by 77208149** [comment]
> [i@ningkai.wang](mailto:i@ningkai.wang)

已发送， 收到请回复

**Comment by 77208149** [comment]
请问怎么解决呢？

**Comment by WangNingkai** [comment]
初步判断缺少依赖，我减少了开发依赖，建议重新安装再看下呢

**Comment by 77208149** [comment]
> 初步判断缺少依赖，我减少了开发依赖，建议重新安装再看下呢

好的 谢谢

**Comment by 77208149** [comment]
是否是composer.json 里的依赖版本有问题呢？我PHP7.2测试 composer install -vvv 这一步报错 后来重新换成PHP7.3.19版本还是报错

![QQ截图20200708091737](https://user-images.githubusercontent.com/37090830/86862522-f05a5e80-c0fb-11ea-96bd-97260653f96a.png)

**Comment by WangNingkai** [comment]
此依赖最小版本php7.4，版本5.0去掉了，更新下就好了
