### ISSUE TITLE
安装5.0版本 全站502

### ISSUE THREAD

**Issue by 77208149** [WangNingkai/OLAINDEX#304]
### 1. 该问题的重现步骤是什么？
根据5.0安装手册执行，最后一步 composer run install-app 报错 再次执行 成功安装；
伪静态已经配置，运行目录为public 
### 2. 你期待的结果是什么？实际看到的又是什么？
成功安装
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.16
- PHP 版本：7.4.7
- OLAINDEX 版本：5.0.0
- 浏览器版本：谷歌浏览器
![微信截图_20200708094547](https://user-images.githubusercontent.com/37090830/86864746-50530400-c100-11ea-97f5-99abd75c71e5.png)
![微信截图_20200708094938](https://user-images.githubusercontent.com/37090830/86864781-5b0d9900-c100-11ea-8ebb-89be10fa77f2.png)

[//]: # (如有图片请附上截图)

**Comment by suyin-long** [comment]
你这个是数据库问题，修改下env文件配置，重新安装即可。

**Comment by WangNingkai** [comment]
检查下env配置文件数据库配置，默认sqlite，如果使用其他数据库，建议先修改env文件后再安装

**Comment by 77208149** [comment]
请问世纪互联配置成功了 也设置主账号了 首页提示这个是什么原因？

![微信截图_20200708102909](https://user-images.githubusercontent.com/37090830/86867712-e2a9d680-c105-11ea-86ea-860c1cc16526.png)

**Comment by suyin-long** [comment]
这个问题跟我遇到的一样，现在作者应该正在解决，敬请期待吧！

**Comment by 77208149** [comment]
> 这个问题跟我遇到的一样，现在作者应该正在解决，敬请期待吧！

敬请期待

**Comment by suyin-long** [comment]
> > 这个问题跟我遇到的一样，现在作者应该正在解决，敬请期待吧！
> 
> 敬请期待

亲测，现在问题已解决，现在可以正常使用了

**Comment by 77208149** [comment]
> > > 这个问题跟我遇到的一样，现在作者应该正在解决，敬请期待吧！
> > 
> > 
> > 敬请期待
> 
> 亲测，现在问题已解决，现在可以正常使用了

需要重装吗，我的还是老样子

**Comment by suyin-long** [comment]
> > > > 这个问题跟我遇到的一样，现在作者应该正在解决，敬请期待吧！
> > > 
> > > 
> > > 敬请期待
> > 
> > 
> > 亲测，现在问题已解决，现在可以正常使用了
> 
> 需要重装吗，我的还是老样子

我是创装的，当然你也可以试着用更新命令更新一下：
```
git pull 
composer install # 安装依赖更新包
```

**Comment by 77208149** [comment]
> > > > > 这个问题跟我遇到的一样，现在作者应该正在解决，敬请期待吧！
> > > > 
> > > > 
> > > > 敬请期待
> > > 
> > > 
> > > 亲测，现在问题已解决，现在可以正常使用了
> > 
> > 
> > 需要重装吗，我的还是老样子
> 
> 我是创装的，当然你也可以试着用更新命令更新一下：
> 
> ```
> git pull 
> composer install # 安装依赖更新包
> ```

亲测 更新没有用

**Comment by suyin-long** [comment]
> > > > > > 这个问题跟我遇到的一样，现在作者应该正在解决，敬请期待吧！
> > > > > 
> > > > > 
> > > > > 敬请期待
> > > > 
> > > > 
> > > > 亲测，现在问题已解决，现在可以正常使用了
> > > 
> > > 
> > > 需要重装吗，我的还是老样子
> > 
> > 
> > 我是创装的，当然你也可以试着用更新命令更新一下：
> > ```
> > git pull 
> > composer install # 安装依赖更新包
> > ```
> 
> 亲测 更新没有用

那就只能重装了

**Comment by 77208149** [comment]
14：40 更新后 可以用了

**Comment by SunSi12138** [comment]
![image](https://user-images.githubusercontent.com/54728594/87650736-b4bb3680-c784-11ea-968f-90631664c88a.png)
安装5.0时出现问题，不知道怎么解决。
（另外给个建议，新版本安装的时候不知道要设置数据库，还是在另外一个朋友的博文里找到的，建议文档更新下）

**Comment by misaka123456** [comment]
> 请问世纪互联配置成功了 也设置主账号了 首页提示这个是什么原因？
> 
> ![微信截图_20200708102909](https://user-images.githubusercontent.com/37090830/86867712-e2a9d680-c105-11ea-86ea-860c1cc16526.png)

想问一下你这个问题怎么解决的，我也出现了你这个问题，composer run install-app 报错 再次执行 成功安装
之后是绑定国际版帐号能正常使用，绑定世纪互联帐号出现你上图的问题

**Comment by 77208149** [comment]
> > 请问世纪互联配置成功了 也设置主账号了 首页提示这个是什么原因？
> > ![微信截图_20200708102909](https://user-images.githubusercontent.com/37090830/86867712-e2a9d680-c105-11ea-86ea-860c1cc16526.png)
> 
> 想问一下你这个问题怎么解决的，我也出现了你这个问题，composer run install-app 报错 再次执行 成功安装
> 之后是绑定国际版帐号能正常使用，绑定世纪互联帐号出现你上图的问题

重装或更新就可以了
