### ISSUE TITLE
收集关于新版的一些问题和建议

### ISSUE THREAD

**Issue by suyin-long** [WangNingkai/OLAINDEX#305]
### 新功能preview

- 后台重建缓存
- 文件加密、隐藏
- etc.

非官方 5.0版本安装教程：https://suyin-blog.club/2020/2VH10V0/

**Comment by WangNingkai** [comment]
1.文件名称过长导致的500错误，可通过修改short_urls字段类型完成
2.后续会完善部分功能，不过有些功能会适当精简

**Comment by suyin-long** [comment]
> 1.文件名称过长导致的500错误，可通过修改short_urls更改类型完成
> 2.后续会议完善部分功能，不过有些功能会适当精简

好的，期待OLAINDEX越来越好！

**Comment by irainerc** [comment]
新版本无法安装啊

**Comment by WangNingkai** [comment]
@irainerc 确保按照步骤要求执行

**Comment by 77208149** [comment]
1.后台修改网站名称title不能改变
2.希望能够增加批量下载的功能
![QQ截图20200710142859](https://user-images.githubusercontent.com/37090830/87123693-d5cde400-c2b9-11ea-8de3-596c6a6b605f.png)

**Comment by 77208149** [comment]
> 1.后台修改网站名称title不能改变
> 2.希望能够增加批量下载的功能
> ![QQ截图20200710142859](https://user-images.githubusercontent.com/37090830/87123693-d5cde400-c2b9-11ea-8de3-596c6a6b605f.png)

3.后台登陆之后路由有问题 
![QQ截图20200710143207](https://user-images.githubusercontent.com/37090830/87123854-27766e80-c2ba-11ea-8afe-1694182d2242.png)

**Comment by suyin-long** [comment]
> 1.后台修改网站名称标题不能更改
> 2.希望能够增加批量下载的功能
> ![QQ截图20200710142859](https://user-images.githubusercontent.com/37090830/87123693-d5cde400-c2b9-11ea-8de3-596c6a6b605f.png)

这个在最新版已经可以后台修改

**Comment by suyin-long** [comment]
有关主题的小问题：
cyborg主题和darkly主题会导致README和HEAD文件文字看不清楚，如下图：
Cyborg
![1](https://user-images.githubusercontent.com/49554285/87217927-09277600-c381-11ea-913f-1c459ea84d32.png)
Darkiy
![2](https://user-images.githubusercontent.com/49554285/87217938-1b091900-c381-11ea-949e-24e6cc2c7c1f.png)

**Comment by MIKU-N** [comment]
很意外发现OLAINDEX居然仍旧保持着更新，甚至已经到了5.0版本。迫不及待开始安装。
利用了宝塔进行安装5.0版本。PHP版本使用了7.4，已删除了那些宝塔默认禁用的函数。
**这是我在安装过程中碰到的一些问题:**
**首先**，在执行到composer install -vvv的时候，composer返回报错:Your requirements could not be resolved to an installable set of packages.
Google以后附加了--ignore-platform-reqs解决，成功安装。
似乎一切正常，很轻松的进入了后台，配置好SSL，绑定账号。
**但我很快发现，似乎无法写入数据库文件，**无论我是修改后台设置，还是绑定账号。都在反复报同一个500错误:SQLSTATE[HY000]: General error: 8 attempt to write a readonly database.
但5.0似乎移除了之前的datebase文件，在配置教程里也没有这一步。
请问一下这个问题如何解决？

**Comment by nodesire7** [comment]
我在安装的时候老是出错 网上的步骤操作到 od:install提示od未定义
用了本页面的操作提示错误代码1
**install-app event returned with error code 1**
始终无法正确安装，结果找到一个魔改版的反而安装成功了，请问一下是什么原因
我是Php7.3版本 权限都是777 CentOS 7.8.2003(Py3.7.8)系统
Nginx1.16 其他步骤都正常 就到安装网页这一步始终无法成功。

**Comment by suyin-long** [comment]
> 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> 用了本页面的操作提示错误代码1
> **install-app事件返回，错误代码1**
> 始终无法正确安装，结果找到一个魔改版的反而安装成功了，
> 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。

按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：https://suyin-blog.club/2020/2VH10V0/

**Comment by suyin-long** [comment]
> 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> 用了本页面的操作提示错误代码1
> **install-app事件返回，错误代码1**
> 始终无法正确安装，结果找到一个魔改版的反而安装成功了，
> 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。

按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：https://suyin-blog.club/2020/2VH10V0/

> 很意外发现OLAINDEX居然仍旧保持着更新，甚至已经到了5.0版本。迫不及待开始安装。
> 利用了宝塔进行安装5.0版本。PHP版本使用了7.4，已删除了那些宝塔默认禁用的函数。
> **这是我在安装过程中碰到的一些问题:**
> **首先**，在执行到composer install -vvv的时候，composer返回报错:Your requirements could not be resolved to an installable set of packages.
> Google以后附加了--ignore-platform-reqs解决，成功安装。
> 似乎一切正常，很轻松的进入了后台，配置好SSL，绑定账号。
> **但我很快发现，似乎无法写入数据库文件，**无论我是修改后台设置，还是绑定账号。都在反复报同一个500错误:SQLSTATE[HY000]: General error: 8 attempt to write a readonly database.
> 但5.0似乎移除了之前的datebase文件，在配置教程里也没有这一步。
> 请问一下这个问题如何解决？

修改`.env`文件中有关数据库的配置

**Comment by D-Myself** [comment]
@WangNingkai 现在图片文件点击下载会调到预览的页面，生成的短链接打开也无法下载

**Comment by WangNingkai** [comment]
@D-Myself 没有遇到此问题呢，查看配置是否正确

**Comment by nodesire7** [comment]
> > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > 用了本页面的操作提示错误代码1
> > **install-app事件返回，错误代码1**
> > 始终无法正确安装，结果找到一个魔改版的反而安装成功了，
> > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> 
> 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：https://suyin-blog.club/2020/2VH10V0/

就是按的5.0的安装步骤 composer run install-app 不行 会提示
install-app event returned with error code 1
我用的这个博客的方法成功的
https://www.hayami.cn/?post=47
按5.0的步骤来总是会报这个错

**Comment by suyin-long** [comment]
> > > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > > 用了本页面的操作提示错误代码1 
> > > **install-app事件返回，错误代码1** 
> > > 始终无法正确安装，结果找到了一个魔改版的反而安装成功了，
> > > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> > 
> > 
> > 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：[https](https://suyin-blog.club/2020/2VH10V0/) ://suyin-blog.club/2020/2VH10V0/[](https://suyin-blog.club/2020/2VH10V0/)
> 
> 就是按的5.0的安装步骤composer run install-app不行会提示
> install-app事件返回，错误代码为1
> 我用的这个博客的方法成功的
> https://www.hayami.cn/?post=47
> 按5.0的步骤来总是会报这个错

首先查看`.evn`数据库配置有没有问题，然后在看看你的宝塔是不是安装了MySQL，如果安装MySQL那么3306这个端口会备占用，解决方法2种：
1.关闭MySQL
2.修改`.evn`数据库配置文件

**Comment by nodesire7** [comment]
> > > > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > > > 用了本页面的操作提示错误代码1
> > > > **install-app事件返回，错误代码1**
> > > > 始终无法正确安装，结果找到了一个魔改版的反而安装成功了，
> > > > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > > > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> > > 
> > > 
> > > 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：[https](https://suyin-blog.club/2020/2VH10V0/) ://suyin-blog.club/2020/2VH10V0/
> > 
> > 
> > 就是按的5.0的安装步骤composer run install-app不行会提示
> > install-app事件返回，错误代码为1
> > 我用的这个博客的方法成功的
> > https://www.hayami.cn/?post=47
> > 按5.0的步骤来总是会报这个错
> 
> 首先查看`.evn`数据库配置有没有问题，然后在看看你的宝塔是不是安装了MySQL，如果安装MySQL那么3306这个端口会备占用，解决方法2种：
> 1.关闭MySQL
> 2.修改`.evn`数据库配置文件

数据库关了也还是这样
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> php artisan install
   ____  __    ___    _____   ______  _______  __
  / __ \/ /   /   |  /  _/ | / / __ \/ ____/ |/ /
 / / / / /   / /| |  / //  |/ / / / / __/  |   /
/ /_/ / /___/ ___ |_/ // /|  / /_/ / /___ /   |
\____/_____/_/  |_/___/_/ |_/_____/_____//_/|_|

v5.0.0
- Designed by IMWNK | Powered by OLAINDEX

Database not found,Creating...
Env file not found,Creating...
Configuration cache cleared!
Configuration cached successfully!

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

      +36 vendor frames 
  37  app/Console/Commands/InstallCommand.php:92
      Illuminate\Console\Command::call("migrate", [])

      +14 vendor frames 
  52  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script php artisan install handling the install-app event returned with error code 1

**Comment by nodesire7** [comment]
> > > > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > > > 用了本页面的操作提示错误代码1
> > > > **install-app事件返回，错误代码1**
> > > > 始终无法正确安装，结果找到了一个魔改版的反而安装成功了，
> > > > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > > > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> > > 
> > > 
> > > 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：[https](https://suyin-blog.club/2020/2VH10V0/) ://suyin-blog.club/2020/2VH10V0/
> > 
> > 
> > 就是按的5.0的安装步骤composer run install-app不行会提示
> > install-app事件返回，错误代码为1
> > 我用的这个博客的方法成功的
> > https://www.hayami.cn/?post=47
> > 按5.0的步骤来总是会报这个错
> 
> 首先查看`.evn`数据库配置有没有问题，然后在看看你的宝塔是不是安装了MySQL，如果安装MySQL那么3306这个端口会备占用，解决方法2种：
> 1.关闭MySQL
> 2.修改`.evn`数据库配置文件

.evn要改哪里啊

**Comment by nodesire7** [comment]
> > > > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > > > 用了本页面的操作提示错误代码1
> > > > **install-app事件返回，错误代码1**
> > > > 始终无法正确安装，结果找到了一个魔改版的反而安装成功了，
> > > > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > > > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> > > 
> > > 
> > > 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：[https](https://suyin-blog.club/2020/2VH10V0/) ://suyin-blog.club/2020/2VH10V0/
> > 
> > 
> > 就是按的5.0的安装步骤composer run install-app不行会提示
> > install-app事件返回，错误代码为1
> > 我用的这个博客的方法成功的
> > https://www.hayami.cn/?post=47
> > 按5.0的步骤来总是会报这个错
> 
> 首先查看`.evn`数据库配置有没有问题，然后在看看你的宝塔是不是安装了MySQL，如果安装MySQL那么3306这个端口会备占用，解决方法2种：
> 1.关闭MySQL
> 2.修改`.evn`数据库配置文件

数据库的名字跟密码都改好了 端口也是一样的 也不行 关掉数据库安装也不行

**Comment by suyin-long** [comment]
> > > > > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > > > > 用了本页面的操作提示错误代码1 
> > > > > **install-app事件返回，错误代码1** 
> > > > > 始终无法正确安装，结果找到了一个魔改版的反而安装成功了，
> > > > > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > > > > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> > > > 
> > > > 
> > > > 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：[https](https://suyin-blog.club/2020/2VH10V0/)：//suyin-blog.club/2020/2VH10V0/
> > > 
> > > 
> > > 就是按的5.0的安装步骤composer run install-app不行会提示
> > > install-app事件返回，错误代码为1 
> > > 我用的这个博客的方法成功的
> > > https://www.hayami.cn/?post=47 
> > > 按5.0的步骤来总是会报这个错
> > 
> > 
> > 首先查看`.evn`数据库配置有没有问题，然后在看看你的宝塔是不是安装了MySQL，如果安装MySQL那么3306这个端口会准备占用，解决方法2种：
> > 1.关闭MySQL 
> > 2.修改`.evn`数据库配置文件
> 
> 数据库的名字跟密码都改好了进口也是一样的也不行关掉数据库安装也不行

我刚刚又重装了一遍，没有一点问题！
修改一下文件：
```
＃sqlite / mysql
DB_CONNECTION = sqlite
＃DB_HOST = 127.0.0.1
＃DB_PORT = 3306
＃DB_DATABASE =宅基地
＃DB_USERNAME =宅基地
＃DB_PASSWORD =秘密

＃缓存配置
＃file / memcached / redis
CACHE_DRIVER =文件
QUEUE_CONNECTION =同步
SESSION_DRIVER =文件
SESSION_LIFETIME = 120

＃redis配置
REDIS_HOST = 127.0.0.1
REDIS_PASSWORD =空
REDIS_PORT = 6379
```
这几个你用了那个就修改那个，database、username、password一定能要对！
如果你想用mysql，那么最好在你添加网站的时候随便把数据库一起建立了！

**Comment by nodesire7** [comment]
> > > > > > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > > > > > 用了本页面的操作提示错误代码1
> > > > > > **install-app事件返回，错误代码1**
> > > > > > 始终无法正确安装，结果找到了一个魔改版的反而安装成功了，
> > > > > > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > > > > > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> > > > > 
> > > > > 
> > > > > 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：[https](https://suyin-blog.club/2020/2VH10V0/)：//suyin-blog.club/2020/2VH10V0/
> > > > 
> > > > 
> > > > 就是按的5.0的安装步骤composer run install-app不行会提示
> > > > install-app事件返回，错误代码为1
> > > > 我用的这个博客的方法成功的
> > > > https://www.hayami.cn/?post=47
> > > > 按5.0的步骤来总是会报这个错
> > > 
> > > 
> > > 首先查看`.evn`数据库配置有没有问题，然后在看看你的宝塔是不是安装了MySQL，如果安装MySQL那么3306这个端口会准备占用，解决方法2种：
> > > 1.关闭MySQL
> > > 2.修改`.evn`数据库配置文件
> > 
> > 
> > 数据库的名字跟密码都改好了进口也是一样的也不行关掉数据库安装也不行
> 
> 我刚刚又重装了一遍，没有一点问题！
> 修改以下文件：
> 
> ```
> ＃sqlite / mysql
> DB_CONNECTION = sqlite
> ＃DB_HOST = 127.0.0.1
> ＃DB_PORT = 3306
> ＃DB_DATABASE =宅基地
> ＃DB_USERNAME =宅基地
> ＃DB_PASSWORD =秘密
> 
> ＃缓存配置
> ＃file / memcached / redis
> CACHE_DRIVER =文件
> QUEUE_CONNECTION =同步
> SESSION_DRIVER =文件
> SESSION_LIFETIME = 120
> 
> ＃redis配置
> REDIS_HOST = 127.0.0.1
> REDIS_PASSWORD =空
> REDIS_PORT = 6379
> ```
> 
> 这几个你用了那个就修改那个，database、username、password一定要填对！
> 如果你想用mysql，那么最好在你添加网站的时候随便把数据库一起建立了！
> 参考下图：我使用MySQL+Redis，[参考链接](https://suyin-blog.club/2020/2VH10V0/#%E5%88%9D%E5%A7%8B%E5%8C%96OLAINDEX)
> ![示例](https://user-images.githubusercontent.com/49554285/87297887-bfcf5600-c53b-11ea-83ed-31c4a941538f.png)

跟你填的一模一样 也是跳这个错 关了MySQL也是

**Comment by suyin-long** [comment]
> @WangNingkai 现在图片文件点击下载会调到预览的页面，生成的短链接打开也无法下载

我这测试的没问题，你看看是不是配置文件中要注释的内容你没有注释

**Comment by suyin-long** [comment]
> > > > > > > 我在安装的时候老是出错网上的步骤操作到od：install提示od未定义
> > > > > > > 用了本页面的操作提示错误代码1
> > > > > > > **install-app事件返回，错误代码1**
> > > > > > > 始终无法正确安装，结果找到了一个魔改版的反而安装成功了，
> > > > > > > 请问一下是什么原因我是Php7.3版本权限都是777 CentOS 7.8.2003（Py3.7.8）系统
> > > > > > > Nginx1.16其他步骤都正常就到安装网页这一步始终无法成功。
> > > > > > 
> > > > > > 
> > > > > > 按照5.0步骤安装啊，你那是4.0的安装步骤：安装教程：[https](https://suyin-blog.club/2020/2VH10V0/)：//suyin-blog.club/2020/2VH10V0/
> > > > > 
> > > > > 
> > > > > 就是按的5.0的安装步骤composer run install-app不行会提示
> > > > > install-app事件返回，错误代码为1
> > > > > 我用的这个博客的方法成功的
> > > > > https://www.hayami.cn/?post=47
> > > > > 按5.0的步骤来总是会报这个错
> > > > 
> > > > 
> > > > 首先查看`.evn`数据库配置有没有问题，然后在看看你的宝塔是不是安装了MySQL，如果安装MySQL那么3306这个端口会准备占用，解决方法2种：
> > > > 1.关闭MySQL
> > > > 2.修改`.evn`数据库配置文件
> > > 
> > > 
> > > 数据库的名字跟密码都改好了进口也是一样的也不行关掉数据库安装也不行
> > 
> > 
> > 我刚刚又重装了一遍，没有一点问题！
> > 修改以下文件：
> > ```
> > ＃sqlite / mysql
> > DB_CONNECTION = sqlite
> > ＃DB_HOST = 127.0.0.1
> > ＃DB_PORT = 3306
> > ＃DB_DATABASE =宅基地
> > ＃DB_USERNAME =宅基地
> > ＃DB_PASSWORD =秘密
> > 
> > ＃缓存配置
> > ＃file / memcached / redis
> > CACHE_DRIVER =文件
> > QUEUE_CONNECTION =同步
> > SESSION_DRIVER =文件
> > SESSION_LIFETIME = 120
> > 
> > ＃redis配置
> > REDIS_HOST = 127.0.0.1
> > REDIS_PASSWORD =空
> > REDIS_PORT = 6379
> > ```
> > 
> > 
> > 这几个你用了那个就修改那个，database、username、password一定要填对！
> > 如果你想用mysql，那么最好在你添加网站的时候随便把数据库一起建立了！
> > 参考下图：我使用MySQL+Redis，[参考链接](https://suyin-blog.club/2020/2VH10V0/#%E5%88%9D%E5%A7%8B%E5%8C%96OLAINDEX)
> > ![示例](https://user-images.githubusercontent.com/49554285/87297887-bfcf5600-c53b-11ea-83ed-31c4a941538f.png)
> 
> 跟你填的一模一样 也是跳这个错 关了MySQL也是

在我网站上加我qq，qq给你解决！

**Comment by D-Myself** [comment]
> @ D-Myself没有遇到此问题呢，查看配置是否正确

配置是正确的，只有图片会这样，重新安装后登陆就跳到/admin 404
请先登录绑定账号！

**Comment by D-Myself** [comment]
> @ D-Myself没有遇到此问题呢，查看配置是否正确

网站为disk.mzrme.com

**Comment by D-Myself** [comment]
> @ D-Myself没有遇到此问题呢，查看配置是否正确

现在打开又是访问令牌已经过期，但是别的都可以下载
![2020-07-15 07-54-32 的屏幕截图](https://user-images.githubusercontent.com/62274834/87487716-ffe42500-c670-11ea-957b-cc534b6e2c67.png)

**Comment by SunSi12138** [comment]
![image](https://user-images.githubusercontent.com/54728594/87652071-54c58f80-c786-11ea-9625-158a858ca310.png)
安装的时候env文件总是会生成一个appkey，好像是这个key过长，然而修改env_example里会被加上，请问怎么解决呢

**Comment by SunSi12138** [comment]
> ![image](https://user-images.githubusercontent.com/54728594/87652071-54c58f80-c786-11ea-9625-158a858ca310.png)
> 安装的时候env文件总是会生成一个appkey，好像是这个key过长，然而修改env_example里会被加上，请问怎么解决呢

问题解决，更换mysql数据库为更高版本就可以了，laravel 的文档里说了，MySQL 数据库的编码应为 utf8mb4，且要求 MySQL 版本在 5.7.7 以上或 MariaDB 版本在 10.2.2 以上。（原先使用的是5.6版本）

**Comment by Masterain98** [comment]
![20200721001813](https://user-images.githubusercontent.com/10614984/88024836-37772500-cae8-11ea-8710-00340e4cf525.png)

在后台输入redirect_uri点击申请后跳转的页面显示这个错误

**Comment by windyhun** [comment]
Script php artisan install handling the install-app event returned with error code 255
为什么我是报错255呀，.evn的那个文件我也修改好了，换上了我的数据库账号密码

**Comment by windyhun** [comment]
> 脚本php artisan install处理安装应用事件，返回错误代码255
> 为什么我是报错255呀，.evn的那个文件我也修改好了，换上了我的数据库账号密码

...........我升级了数据库版本，和把php7.2换成php7.4就好了

**Comment by nodesire7** [comment]
挂载两个网盘以后就各种报错 主盘不能访问
![](https://macgn.superbed.cn/item/5f1f93a814195aa5946aaa7f.png)
https://od.kangli.online

**Comment by Wanxi-00** [comment]
> ![20200721001813](https://user-images.githubusercontent.com/10614984/88024836-37772500-cae8-11ea-8710-00340e4cf525.png)
> 
> 在后台输入redirect_uri点击申请后跳转的页面显示这个错误

你的解决了吗 我也遇到了这种情况

**Comment by WangNingkai** [comment]
> 挂载两个网盘以后就各种报错 主盘不能访问
> https://macgn.superbed.cn/item/5f1f93a814195aa5946aaa7f.png
> https://od.kangli.online

这里报错是账号的问题，尝试单独挂载出错的网盘呢

**Comment by WangNingkai** [comment]
> ![20200721001813](https://user-images.githubusercontent.com/10614984/88024836-37772500-cae8-11ea-8710-00340e4cf525.png)
> 
> 在后台输入redirect_uri点击申请后跳转的页面显示这个错误

@Masterain98 官方申请的地址修改了，需要手动申请了，登录portal azure控制面板手动申请就可

**Comment by Wanxi-00** [comment]
> > ![20200721001813](https://user-images.githubusercontent.com/10614984/88024836-37772500-cae8-11ea-8710-00340e4cf525.png)
> > 在后台输入redirect_uri点击申请后跳转的页面显示这个错误
> 
> @Masterain98 官方申请的地址修改了，需要手动申请了，登录portal azure控制面板手动申请就可

可以了 谢谢

**Comment by Wanxi-00** [comment]
5.0版本是不是删除了mdui的文件，我在.env中改成mdui后500报错，提示找不到mdui.one
![image](https://user-images.githubusercontent.com/65232501/88874356-74ae8600-d251-11ea-8884-d7ca2a0816ae.png)

**Comment by ShaoPak** [comment]
> 1.文件名称过长导致的500错误，可通过修改short_urls字段类型完成
> 2.后续会完善部分功能，不过有些功能会适当精简

还是希望可以加上起始显示目录，这个功能很好用

**Comment by KawaiiZapic** [comment]
貌似不支持PHP 7.2
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mockery/mockery 1.4.1 -> satisfiable by mockery/mockery[1.4.1].
    - mockery/mockery 1.4.1 requires php ^7.3 || ^8.0 -> your PHP version (7.2.32) does not satisfy that requirement.

```

**Comment by suyin-long** [comment]
> 貌似不支持PHP 7.2
> 
> ```
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for mockery/mockery 1.4.1 -> satisfiable by mockery/mockery[1.4.1].
>     - mockery/mockery 1.4.1 requires php ^7.3 || ^8.0 -> your PHP version (7.2.32) does not satisfy that requirement.
> ```

建议使用php7.4

**Comment by WangNingkai** [comment]
😄  隐藏和加密功能会慢慢加入 只是想以更好的方式展现 稍安勿躁

**Comment by D-Myself** [comment]
>  隐藏和加密功能会慢慢加入 只是想以更好的方式展现 稍安勿躁
图片点击下载，还是会跳到预览页面，而且标题变成OLAINDEX

**Comment by D-Myself** [comment]
>  隐藏和加密功能会慢慢加入 只是想以更好的方式展现 稍安勿躁

图片点击下载，还是会跳到预览页面，而且标题变成OLAINDEX

**Comment by KawaiiZapic** [comment]
> > 貌似不支持PHP 7.2
> > ```
> > Your requirements could not be resolved to an installable set of packages.
> > 
> >   Problem 1
> >     - Installation request for mockery/mockery 1.4.1 -> satisfiable by mockery/mockery[1.4.1].
> >     - mockery/mockery 1.4.1 requires php ^7.3 || ^8.0 -> your PHP version (7.2.32) does not satisfy that requirement.
> > ```
> 
> 建议使用php7.4

已解决,删除composer.lock重新执行composer install即可.
使用PHP7.2是因为我自己写的东西都是基于PHP7.2的.

**Comment by JellyCooker** [comment]
建议: 希望类似oneindex,环境的检测,数据库的选择,redis的选择等设置，放在install.app里来配置,而不是在命令行里

**Comment by feiwujia** [comment]
> > 最新版本加密好像出现了之前的问题，我加密了主目录，但是用主目录中文件/文件夹的链接直接可以访问主目录中的文件/文件夹，直接跳过了密码。
> 
> 5.0版本的加密一直都不管用

啊这，那还是等作者大佬更新吧

**Comment by aotuitx** [comment]
![2](https://user-images.githubusercontent.com/45528676/93237622-f4b58e80-f7b2-11ea-845a-ed6c87471f07.jpg)
![1](https://user-images.githubusercontent.com/45528676/93237630-f67f5200-f7b2-11ea-94b5-5917d42433ec.jpg)
目前报错这两种，一个是只能看到文件占用量，还有一个是看网盘信息的时候什么也看不到。重装了好几次也不行，我这是少了哪个步骤么？

**Comment by aotuitx** [comment]
![1](https://user-images.githubusercontent.com/45528676/93408980-6fbc9900-f8c8-11ea-83c1-575cad549d0d.jpg)
![2](https://user-images.githubusercontent.com/45528676/93409048-97136600-f8c8-11ea-8638-d98c2387bb1e.jpg)
请问，界面我想改成如图2的界面，要修改哪里啊。就是多盘符挂载的话，不用手动去选择盘符，而是全部列出来。

**Comment by hejiadong0608** [comment]
希望可以优化一下搜索，我这边搜索有很大的问题，不管输入什么，都要搜索很久，最后展示的结果好像是把所有的文件都列出来了，我搜什么都是从00什么开始的一堆文件。

**Comment by suyin-long** [comment]
> 最新版加密好像出现了之前的问题，我加密了主目录，但是用主目录中文件/文件夹的链接直接就能访问主目录中的文件/文件夹，直接跳过了密码。

后台管理里可以设置加密

**Comment by DamonNie** [comment]
> > 最新版加密好像出现了之前的问题，我加密了主目录，但是用主目录中文件/文件夹的链接直接就能访问主目录中的文件/文件夹，直接跳过了密码。
> 
> 后台管理里可以设置加密
很棒，按照你的教程安装都通关了。但是绑定账号秘钥后 报错400.请问知道什么原因吗？
环境：php 7.4  mysql 5.6,配置都是依照你的配

**Comment by DamonNie** [comment]
> > > 最新版加密好像出现了之前的问题，我加密了主目录，但是用主目录中文件/文件夹的链接直接就能访问主目录中的文件/文件夹，直接跳过了密码。
> > 
> > 
> > 后台管理里可以设置加密
> > 很棒，按照你的教程安装都通关了。但是绑定账号秘钥后 报错400.请问知道什么原因吗？
> > 环境：php 7.4  mysql 5.6,配置都是依照你的配
@suyin-long  Error requesting access token. 400: HTTP/1.1 400 Bad Request,这个错误信息清楚哪里出错了吗

**Comment by euukey** [comment]
静态文件的cdn联通默认dns无法解析，建议换成bootcdn的

**Comment by Wanxi-00** [comment]
新的5.0版本为什么要删除mdui主题呢，我认为这个主题非常好用，也是我选择oaindex的一大原因。现在把.env改成mdui后提示View [mdui.one] not found.

**Comment by Fizznoc** [comment]
老大 能不能新增一个在后台可以设置主页地址的功能，就是比如说 我不想让别人访问我的域名直接就到达了网盘主界面，想让他们访问主页显示404界面或者其他，这个功能怎么实现啊  我现在用的是那个修改版支持世纪互联的

**Comment by office365E5** [comment]
大佬可以加入挂载SharePoint嘛

**Comment by Orokapei** [comment]
### 功能建议

列表显示文件名称似乎限定了32个字符，不知可否改成跑马灯形式显示，鼠标悬停显示全称= =

**Comment by ShaoPak** [comment]
5.0版本的OLAINDEX链接样式太长了，不论是下载链接还是页面链接，中间都会生成一个8位随机字符串。
### 1. 4.0和5.0版本页面链接对比截图
![](https://user-images.githubusercontent.com/62377236/100407911-a5d68000-30a4-11eb-83b4-7f27e37ca34d.png)
![](https://user-images.githubusercontent.com/62377236/100407919-ab33ca80-30a4-11eb-9075-9a8a0cd88be4.png)

### 2. 还有下载链接也是一样很长，视频除外，但是一般文件如zip、txt等也会添加随机字符串和?download=1判断，因为想提取直链，所以下载链接越短越好，能否优化一下？或者怎么设置伪静态修改呢？

**Comment by misaka123456** [comment]
新版主题有点问题


以前的

![QQ截图20201127221846](https://user-images.githubusercontent.com/38593541/100461050-2f1c9f80-3103-11eb-88cb-4d9648f583f6.png)

现在的

![QQ截图20201127221858](https://user-images.githubusercontent.com/38593541/100461058-304dcc80-3103-11eb-98e4-c8ac2c14ab64.png)





并且现在的鼠标放在连接上不会变成“手”的形状

**Comment by ShaoPak** [comment]
### 5.0版本因为支持多帐号挂载所以每个帐号都有一个8位识别码，但是对于用不到多账号的用户来说，这样的就导致网页链接变长，没有4.0版本简洁，希望可以加一个判断，单账户时网页链接隐藏8位识别码，像4.0版本一样

### 5.0版本截图
![5.0版本截图](https://user-images.githubusercontent.com/62377236/100593436-5eb1ee80-3333-11eb-988b-4811db6dc4a8.png)

### 4.0版本截图
![4.0版本截图](https://user-images.githubusercontent.com/62377236/100593463-67a2c000-3333-11eb-9211-49a0bb92f9fd.png)
