### ISSUE TITLE
新版本OLAINDEX后台问题

### ISSUE THREAD

**Issue by MIKU-N** [WangNingkai/OLAINDEX#306]
### 1. 该问题的重现步骤是什么？
使用宝塔面板安装最新的5.0版本LOAINDEX即可
### 2. 你期待的结果是什么？实际看到的又是什么？
可以设置后台内容/绑定账号
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：NGINX 1.18.0
- PHP 版本：7.4.7
- OLAINDEX 版本：5.0
- 浏览器版本：Chrome 83.0.4103.106

//
很意外发现OLAINDEX居然仍旧保持着更新，甚至已经到了5.0版本。迫不及待开始安装。
利用了宝塔进行安装5.0版本。PHP版本使用了7.4，已删除了那些宝塔默认禁用的函数。
这是我在安装过程中碰到的一些问题:
首先，在执行到composer install -vvv的时候，composer返回报错:Your requirements could not be resolved to an installable set of packages.
Google以后附加了--ignore-platform-reqs解决，成功安装。
似乎一切正常，很轻松的进入了后台，配置好SSL，绑定账号。
但我很快发现，似乎无法写入数据库文件,无论我是修改后台设置，还是绑定账号。都在反复报同一个500错误:SQLSTATE[HY000]: General error: 8 attempt to write a readonly database.
但5.0似乎移除了之前的datebase文件，在配置教程里也没有这一步。
请问一下这个问题如何解决？

**Comment by MIKU-N** [comment]
补充一个在安装过程中出现的错误，此错误只会出现在第一次执行composer run install-app时出现，再次执行composer run install-app则正常安装成功。

> php artisan install
   ____  __    ___    _____   ______  _______  __
  / __ \/ /   /   |  /  _/ | / / __ \/ ____/ |/ /
 / / / / /   / /| |  / //  |/ / / / / __/  |   /
/ /_/ / /___/ ___ |_/ // /|  / /_/ / /___ /   |
\____/_____/_/  |_/___/_/ |_/_____/_____//_/|_|

v5.0.0
- Designed by IMWNK | Powered by OLAINDEX

Database not found,Creating...
Env file not found,Creating...
Configuration cache cleared!
Configuration cached successfully!

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

      +33 vendor frames
  34  app/Console/Commands/InstallCommand.php:87
      Illuminate\Console\Command::call()

      +14 vendor frames
  49  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script php artisan install handling the install-app event returned with error code 1

**Comment by MIKU-N** [comment]
我意外发现了问题所在，是由于/storage/install/data/database.sqlite的默认权限设置错误，手动更改为777权限即可正常写入。
5.0版本将database.sqlite移动到了此目录中，但在安装教程中并没有说明设置权限，这会导致数据库文件只可读取，很奇怪。

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/87267603-b70a6000-c4fa-11ea-998b-15e20f4868f8.png)

https://github.com/WangNingkai/OLAINDEX/commit/09597487ff4fa498b839a6de4ae8a7cd55132fc8

 已优化安装脚本

**Comment by MIKU-N** [comment]
OK，另外能否在前端增加一个看图模式？目前图片只能点击文件进行单图预览，有时候会异常麻烦（同一文件夹的情况下）

**Comment by WangNingkai** [comment]
后面会根据反馈逐渐加入新功能
