### ISSUE TITLE
忘记了密码请问如何重置

### ISSUE THREAD

**Issue by SunSi12138** [WangNingkai/OLAINDEX#307]
### 1. 该问题的重现步骤是什么？
登陆提示输入了错误的账户或者密码，但是我忘记了密码，用的都是chrome保存的密码，发现没有办法重置密码或者找回密码
### 2. 你期待的结果是什么？实际看到的又是什么？
希望有找回或者修改密码的方法
不想重装/(ㄒoㄒ)/~~

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/3737b98d9f1b394257834bd4714540b80647414f

操作重置密码 `php artisan helper:reset-password`
