### ISSUE TITLE
回调后出现invalid state

### ISSUE THREAD

**Issue by D-Myself** [WangNingkai/OLAINDEX#309]
### 1. 该问题的重现步骤是什么？
部署最新的5.0分支的版本，绑定账户
### 2. 你期待的结果是什么？实际看到的又是什么？
绑定成功。invaild state
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.19.1
- PHP 版本：7.4.2
- OLAINDEX 版本：5.0
- 浏览器版本：chrome 82
![2020-07-15 14-32-55 的屏幕截图](https://user-images.githubusercontent.com/62274834/87511872-a4358e00-c6a8-11ea-98a9-27a727f7333b.png)

**Comment by D-Myself** [comment]
同时，master的版本部署后登陆跳转到/admin出现请绑定账户

**Comment by D-Myself** [comment]
最新版本依旧如此

**Comment by D-Myself** [comment]
回调后失败
![2020-07-15 14-32-55 的屏幕截图](https://user-images.githubusercontent.com/62274834/87617589-5cffd980-c74a-11ea-96f4-f13ffa64b502.png)

**Comment by WangNingkai** [comment]
@D-Myself 回调地址填写的什么 ，提供下操作步骤呢

**Comment by D-Myself** [comment]
> @ D-Myself某些地址填写的什么，提供下操作步骤呢

按照绑定步骤啊，回调地址就是https://disk.mzrme.com/callback

**Comment by D-Myself** [comment]
> @ D-Myself某些地址填写的什么，提供下操作步骤呢

最新版还是如此

**Comment by D-Myself** [comment]
> @D-Myself 回调地址填写的什么 ，提供下操作步骤呢

换回了5.0？

**Comment by WangNingkai** [comment]
看样子是无法读取缓存啊 ，日志有记录其他报错信息吗，方便的话 搭建账号和clientid发我 i@ningkai.wang 邮箱我，手动debug看下

**Comment by D-Myself** [comment]
> 看样子是无法读取缓存啊 ，日志有记录其他报错信息吗，方便的话 搭建账号和clientid发我 [i@ningkai.wang](mailto:i@ningkai.wang) 邮箱我，手动debug看下

已经发送
