### ISSUE TITLE
上传文件最大只能是4M吗？

### ISSUE THREAD

**Issue by yikaiba** [WangNingkai/OLAINDEX#311]
### 1. 该问题的重现步骤是什么？
上传文件大小
### 2. 你期待的结果是什么？实际看到的又是什么？
可以设置上传文件的大小，现在最大才4M

并且有的文件上传会上传不完整，这个怎么解决？？上传3M文件，实际显示500K

**Comment by WangNingkai** [comment]
上传4M是由于微软接口限制，大于4M建议使用客户端上传
