### ISSUE TITLE
菜鸟求助 5.0的文件加密和隐藏的问题

### ISSUE THREAD

**Issue by CNBOY239** [WangNingkai/OLAINDEX#313]
首先，真心感谢你的分享，能让我有机会白嫖使用。

**### 1. 该问题的重现步骤是什么？**
安装完olaindex 5.0，正常使用中

**### 2. 你期待的结果是什么？实际看到的又是什么？**
**期待：**
怎么加密文件夹，怎么隐藏文件夹，这两个功能还支持吗？或是需要自己改文件设置，怎么修改？

**实际看到：**
4.0版本中有明确的隐藏文件、加密文件的选项。5.0里找了半天没找到在哪，只有一个文件夹加密提示选项，按照4.0的设置方法设置后无法实现加密，另，通过自己设置.password文件也实现不了加密。

**### 3. 问题出现的环境**
操作系统版本：
Apache/NGINX 版本：nginx/1.18.1
PHP 版本：php7.3
OLAINDEX 版本：5.0
浏览器版本：Chrome

**Comment by zztbill** [comment]
同问，在查看了sqlite数据库后并没有找到相关的存储加密和隐藏的字段。

**Comment by suyin-long** [comment]
同问！

**Comment by WangNingkai** [comment]
稍安勿躁，功能会陆续加入

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："CNBOY239 "<notifications@github.com&gt;;
发送时间：2020年8月4日(星期二) 中午11:03
收件人："WangNingkai/OLAINDEX" <OLAINDEX@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[WangNingkai/OLAINDEX] 菜鸟求助 5.0的问题 (#313)
-----------------------------------

 

 
首先，真心感谢你的分享，能让我有机会白嫖使用。
 
正题如下：
 4.0版本有明确的隐藏文件、加密文件的选项。5.0我找了半天没找到在哪，这两个功能还支持吗？或是需要自己改文件设置，怎么修改？请老王同学指教下，或是来这里的其他大神们指导下！
 
万分感谢！

**Comment by CNBOY239** [comment]
> 稍安勿躁，功能会陆续加入
> […](#)
> ----------该邮件从移动设备发送
> --------------原始邮件--------------发件人：“ CNBOY239” <notifications@github.com> ;; 发送时间：2020年8月4日（星期二）中午11:03收件人：“ WangNingkai / OLAINDEX” <OLAINDEX@noreply.github.com> ;; 抄送：“ Subscribed” <subscribed@noreply.github.com> ;; 主题：[WangNingkai / OLAINDEX]菜鸟求助5.0的问题（[＃313](https://github.com/WangNingkai/OLAINDEX/issues/313)）---------------------------------- -首先，真心感谢你的分享，实现我有机会白嫖使用。正题如下：4.0版本有明确的隐藏文件，加密文件的选项。5.0我找了半天没找到在哪，这两个功能还支持吗？或者需要自己改文件设置，如何修改？请老王同学指教下，或者来这里的其他大神们指导下！万分感谢！-您正在接受此消息，因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

万分感谢，怕你不经常看这个，就给你发个邮件。

**Comment by CNBOY239** [comment]
> 稍安勿躁，功能会陆续加入
> […](#)
> ----------该邮件从移动设备发送
> --------------原始邮件--------------发件人：“ CNBOY239” <notifications@github.com> ;; 发送时间：2020年8月4日（星期二）中午11:03收件人：“ WangNingkai / OLAINDEX” <OLAINDEX@noreply.github.com> ;; 抄送：“ Subscribed” <subscribed@noreply.github.com> ;; 主题：[WangNingkai / OLAINDEX]菜鸟求助5.0的问题（[＃313](https://github.com/WangNingkai/OLAINDEX/issues/313)）---------------------------------- -首先，真心感谢你的分享，实现我有机会白嫖使用。正题如下：4.0版本有明确的隐藏文件，加密文件的选项。5.0我找了半天没找到在哪，这两个功能还支持吗？或者需要自己改文件设置，如何修改？请老王同学指教下，或者来这里的其他大神们指导下！万分感谢！-您正在接受此消息，因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

万分感谢，怕你不经常看这个，就给你发个邮件。
