### ISSUE TITLE
菜鸟求助 5.0的图片查看的问题

### ISSUE THREAD

**Issue by CNBOY239** [WangNingkai/OLAINDEX#314]
### 1. 该问题的重现步骤是什么？
安装完olaindex 5.0，正常使用中

### 2. 你期待的结果是什么？实际看到的又是什么？
期待：
图片在线点击后可以直接查看（即时浏览），而不是直接下载？
如果是可以通过修改文件实现，怎么修改？
如果现在不能实现，期待后期可以实现！

实际看到：
点击图片，直接进行下载，而不是在线查看。

### 3. 问题出现的环境
操作系统版本：
Apache/NGINX 版本：nginx/1.18.1
PHP 版本：php7.3
OLAINDEX 版本：5.0
浏览器版本：Chrome

**Comment by suyin-long** [comment]
修改后台配置中的**显示设置**即可，如图：
![p](https://user-images.githubusercontent.com/49554285/89352616-21bc4f00-d6e7-11ea-89dc-2146b3898cdc.png)

**Comment by CNBOY239** [comment]
> 修改后台配置中的**显示设置**即可，如下：
> ![p](https://user-images.githubusercontent.com/49554285/89352616-21bc4f00-d6e7-11ea-89dc-2146b3898cdc.png)

噢噢，明白了，已经好了，谢谢嗷。
