### ISSUE TITLE
关于解决页面Error 500的问题

### ISSUE THREAD

**Issue by Cyame** [WangNingkai/OLAINDEX#315]
### 1. 该问题的重现步骤是什么？

按照现有(2020/8/6 Released)进行部署，显示页面500Error的问题

### 2. 问题出现的环境

- 操作系统版本：Ubuntu 18.04

### 3. 目前发现的解决方案

需要在项目根目录对缓存进行刷新，
```
php artisan config:clear
php artisan view:clear
php artisan config:cache
```

刷新缓存后即可正常访问

**Comment by Cyame** [comment]
鼓捣了一整天……也问了不少人 查了不少东西

最后询问了懂php的朋友 跟我说是laravel常见错误 试着刷新一下

刷新过后确实可以正常访问了 这里贴一个issue 希望有帮助

**Comment by vzone** [comment]
这个方法也是没解决！！
