### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such table: accounts

### ISSUE THREAD

**Issue by KJZH001** [WangNingkai/OLAINDEX#316]
### 1. 该问题的重现步骤是什么？

1.使用此处的命令进行手动安装http://ningkai.wang/OLAINDEX/#/install
2.访问根目录时出现500错误

浏览器显示地址：http://od.moeworld.top:30200/
绑定目录对应：./pubilc

### 2. 你期待的结果是什么？实际看到的又是什么？
出现正常安装的界面，但实际返回的是
500
SQLSTATE[HY000]: General error: 1 no such table: accounts (SQL: select "id", "remark" from "accounts" where "status" = 1)
### 3. 问题出现的环境

- 操作系统版本：Windows Server 2019
- Apache/NGINX 版本：Apache 2.4.39
- PHP 版本：php7.3.4nts_p
- OLAINDEX 版本：使用手动安装中的命令进行git克隆，因此版本应为最新
- 浏览器版本：QQ浏览器 | 10.6.4208.400

### 附加信息
经过我自己的检查
发现storage\install\data\database.sqlite虽然已经生成，但是是空的
此外，我尝试使用Navicat Premium将该目录下的sql文件导入其中，但是没有成功

在安装时，使用到指令我是在git的命令行中执行，但是composer的命令我是在根目录下开启powershell执行的
此外，由于操作系统为windows，并且登录的是Administrator账户，所以我省去了chmod的这两行命令

###返回错误的网页图片
https://cdn.jsdelivr.net/gh/KJZH001/For_PicGO@master/jsDelivr_static_files/img/large/20200807092947.png

**Comment by WangNingkai** [comment]
通过 `composer` 依赖安装成功后，可以执行 `php artisan migrate && php artisan db:seed` 执行命令导入数据库数据

**Comment by KJZH001** [comment]
你好，我输入了php artisan migrate
php artisan db:seed
这两行命令在网站根目录下的powershell中执行
虽然没有返回错误，但是问题仍旧没有解决
返回的错误和之前是一样的
