### ISSUE TITLE
最新版安装问题

### ISSUE THREAD

**Issue by suyin-long** [WangNingkai/OLAINDEX#317]
### 1. 该问题的重现步骤是什么？
安装最新版
### 2. 你期待的结果是什么？实际看到的又是什么？
成功安装；报错
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx 1.18.0
- PHP 版本：7.4
- OLAINDEX 版本：5.0
- 浏览器版本：Chrome 84.0.4147.105

[//]: # (如有图片请附上截图)

# 总结一下新版本安装出现的的问题

## 1. 安装时报错 `No such file or directory`

```
Already have database file,Re-creating...

   ErrorException 

  rename(/www/wwwroot/suyin-tools.cn/storage/install/data/database.sqlite,20200809100048./www/wwwroot/suyin-tools.cn/storage/install/data/database.sqlite.bak): No such file or directory

  at app/Console/Commands/InstallCommand.php:61
    57|             $this->warn('Database not found,Creating...');
    58|             copy($sqlSampleFile, $sqlFile);
    59|         } else {
    60|             $this->warn('Already have database file,Re-creating...');
  > 61|             rename($sqlFile, date('YmdHis') . '.' . $sqlFile . '.bak');
    62|             copy($sqlSampleFile, $sqlFile);
    63|         }
    64|         chmod($sqlFile, 0777);
    65|

  1   app/Console/Commands/InstallCommand.php:61
      rename()

      +14 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script php artisan install handling the install-app event returned with error code 1
```
> 说明：在修改完 `.env` 文件中关于数据库的配置后，安装报该错误
> 解决方法：
> 1.重新给CLAINDEX项目文件权限777 
> 2.执行`composer run uninstall-app`清除缓存
> 2.执行`composer run install-app`重新安装

## 2. 安装成功后配置onedrive账号时报错，说没有生成日志文件的权限
> 解决方法：重新给权限777

## 3. 配置完onedrive账号报错
![claindex](https://user-images.githubusercontent.com/49554285/89723934-894c0480-da2f-11ea-8a45-b824294e98d5.png)
日志截图：
![1](https://user-images.githubusercontent.com/49554285/89723938-94069980-da2f-11ea-82be-8445616bad58.png)
> 看日志上说好像是数据库连接问题，我用的 **MySQL + Redis** ，目前没有解决该问题，希望CLAINDEX作者帮忙解决一下，谢谢。

## 顺带提个4.0版本的问题 [#300](https://github.com/WangNingkai/OLAINDEX/issues/300) 
这个问题在5.0版本中已修复，但是4.0版本中依旧存在，希望可以修复！

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/1e61fb9f0e1df7c6f4fc7cc10e4fcec27770315d
