### ISSUE TITLE
5.0安装出现问题

### ISSUE THREAD

**Issue by BurgerTown** [WangNingkai/OLAINDEX#322]
### 1. 该问题的重现步骤是什么？

`composer run install-app`

### 2. 你期待的结果是什么？实际看到的又是什么？

![image](https://user-images.githubusercontent.com/19660419/90334758-7f636c00-e002-11ea-92f7-8f9ab99538ad.png)

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：7.4
- OLAINDEX 版本：5.0
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by vzone** [comment]
我也是遇到一样的问题，最新版5.0安装总是提示这个！！！

**Comment by DamonNie** [comment]
1、not such file仔细看，只有sample文件！所以，尝试着把文件名改下就好
2、接下来还是会有问题，rename的第二个参数，作者这里应该没有自测 把时间放到后面拼接，OK 搞定！
3、但是。。。问题还是来了：
![image](https://user-images.githubusercontent.com/16314117/90411567-8eb7e780-e0de-11ea-8514-04aaeb991abc.png)

请问下，是不是仍少了哪些步骤

**Comment by vzone** [comment]
看来是用不上5.0，等作者有空更新吧！！

**Comment by suyin-long** [comment]
5.0分支可以正常使用，主分支不行，建议想用5.0版本的安装5.0分支上的版本。

**Comment by BurgerTown** [comment]
> 1、not such file仔细看，只有sample文件！所以，尝试着把文件名改下就好
> 2、接下来还是会有问题，rename的第二个参数，作者这里应该没有自测 把时间放到后面拼接，OK 搞定！
> 3、但是。。。问题还是来了：
> ![image](https://user-images.githubusercontent.com/16314117/90411567-8eb7e780-e0de-11ea-8514-04aaeb991abc.png)
> 
> 请问下，是不是仍少了哪些步骤

你也仔细看一下，这里明明是有if的，存在就备份，不存在就创建

**Comment by Kinodi** [comment]
在参照作者的博客的宝塔安装OLAINDEX教程时，发现5.0版本中没有database.sample.sqlite，于是从4.0版本中复制database.sample.sqlite到/www/wwwroot/域名/database目录下   再执行教程中的 
   cp database/database.sample.sqlite database/database.sqlite    命令。能解决Script php artisan install handling the install-app event returned with error code 1 报错

**Comment by Kinodi** [comment]
> > 在参照作者的博客的宝塔安装OLAINDEX教程时，发现5.0版本中没有database.sample.sqlite，于是从4.0版本中复制database.sample.sqlite到/ www / wwwroot /域名/ database目录下再执行教程中的
> > cp工匠安装脚本，处理返回的错误代码为1的install-app事件
> > ![图片](https://user-images.githubusercontent.com/44763845/90774294-d41c2500-e329-11ea-9e7b-2870f86bc0ad.png)
> 
> 5.0和4.0的安装教程不一样，你看的4.0的教程安装5.0的版本，能不报错？

就这一步是添加database.sample.sqlite文件  执行cp 命令   其他按照5.0的命令

**Comment by Kinodi** [comment]
> > > 在参照作者的博客的宝塔安装OLAINDEX教程时，发现5.0版本中没有database.sample.sqlite，于是从4.0版本中复制database.sample.sqlite到/ www / wwwroot /域名/ database目录下再执行教程中的
> > > cp工匠安装脚本，处理返回的错误代码为1的install-app事件
> > > ![图片](https://user-images.githubusercontent.com/44763845/90774294-d41c2500-e329-11ea-9e7b-2870f86bc0ad.png)
> > 
> > 
> > 5.0和4.0的安装教程不一样，你看的4.0的教程安装5.0的版本，能不报错？
> 
> 就这一步是添加database.sample.sqlite文件 执行cp 命令 其他按照5.0的命令

即：
git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
mv tmp/.git . 
rm -rf tmp 
git reset --hard 
cp database/database.sample.sqlite database/database.sqlite
composer install -vvv  
chmod -R 777 storage 
chown -R www:www * 
composer run install-app

**Comment by suyin-long** [comment]
> > > > 在参照作者的博客的宝塔安装OLAINDEX教程时，发现5.0版本中没有database.sample.sqlite，于是从4.0版本中复制database.sample.sqlite到/ www / wwwroot /域名/ database目录下再执行教程中的
> > > > cp工匠安装脚本，处理返回的错误代码为1的install-app事件
> > > > ![图片](https://user-images.githubusercontent.com/44763845/90774294-d41c2500-e329-11ea-9e7b-2870f86bc0ad.png)
> > > 
> > > 
> > > 5.0和4.0的安装教程不一样，你看的4.0的教程安装5.0的版本，能不报错？
> > 
> > 
> > 就这一步是添加database.sample.sqlite文件执行cp命令其他按照5.0的命令
> 
> 即：
> git clone https://github.com/WangNingkai/OLAINDEX.git tmp
> mv tmp / .git。
> rm -rf tmp
> git reset --hard
> cp database / database.sample.sqlite database / database.sqlite
> composer install -vvv
> chmod -R 777 storage
> chown -R www：www *
> composer run install-app

5.0安装步骤：
```
cd web-project
git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
mv tmp/.git . 
rm -rf tmp 
git reset --hard 
composer install -vvv  # Install Dependencies
chmod -R 777 storage # Important！！！Ensure that the cache directory has read and write permissions
chown -R www:www * # this 'www' refer to the serve user group
composer run install-app # installation app
```

**Comment by Kinodi** [comment]
> > > > > 在参照作者的博客的宝塔安装OLAINDEX教程时，发现5.0版本中没有database.sample.sqlite，于是从4.0版本中复制database.sample.sqlite到/ www / wwwroot /域名/ database目录下再执行教程中的
> > > > > cp工匠安装脚本，处理返回的错误代码为1的install-app事件
> > > > > ![图片](https://user-images.githubusercontent.com/44763845/90774294-d41c2500-e329-11ea-9e7b-2870f86bc0ad.png)
> > > > 
> > > > 
> > > > 5.0和4.0的安装教程不一样，你看的4.0的教程安装5.0的版本，能不报错？
> > > 
> > > 
> > > 就这一步是添加database.sample.sqlite文件执行cp命令其他按照5.0的命令
> > 
> > 
> > 即：
> > git clone https://github.com/WangNingkai/OLAINDEX.git tmp
> > mv tmp / .git。
> > rm -rf tmp
> > git reset --hard
> > cp database / database.sample.sqlite database / database.sqlite
> > composer install -vvv
> > chmod -R 777 storage
> > chown -R www：www *
> > composer run install-app
> 
> 5.0安装步骤：
> 
> ```
> cd web-project
> git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
> mv tmp/.git . 
> rm -rf tmp 
> git reset --hard 
> composer install -vvv  # Install Dependencies
> chmod -R 777 storage # Important！！！Ensure that the cache directory has read and write permissions
> chown -R www:www * # this 'www' refer to the serve user group
> composer run install-app # installation app
> ```
> 
> 兄弟，仔细看看网站

我知道   在这个基础上就多执行了一条cp命令

**Comment by suyin-long** [comment]
> > > > > > 在参照作者的博客的宝塔安装OLAINDEX教程时，发现5.0版本中没有database.sample.sqlite，于是从4.0版本中复制database.sample.sqlite到/ www / wwwroot /域名/ database目录下再执行教程中的
> > > > > > cp工匠安装脚本，处理返回的错误代码为1的install-app事件
> > > > > > ![图片](https://user-images.githubusercontent.com/44763845/90774294-d41c2500-e329-11ea-9e7b-2870f86bc0ad.png)
> > > > > 
> > > > > 
> > > > > 5.0和4.0的安装教程不一样，你看的4.0的教程安装5.0的版本，能不报错？
> > > > 
> > > > 
> > > > 就这一步是添加database.sample.sqlite文件执行cp命令其他跟随5.0的命令
> > > 
> > > 
> > > 即：
> > > git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
> > > mv tmp / .git。rm 
> > > -rf tmp 
> > > git reset --hard 
> > > cp数据库
> > > /database.sample.sqlite 数据库/database.sqlite作曲家安装-vvv 
> > > chmod -R 777存储器
> > > chown -R www：www * 
> > > composer run install-app
> > 
> > 
> > 5.0安装步骤：
> > ```
> > cd web-project
> > git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
> > mv tmp/.git . 
> > rm -rf tmp 
> > git reset --hard 
> > composer install -vvv  # Install Dependencies
> > chmod -R 777 storage # Important！！！Ensure that the cache directory has read and write permissions
> > chown -R www:www * # this 'www' refer to the serve user group
> > composer run install-app # installation app
> > ```
> > 
> > 
> > 兄弟，仔细看看网站
> 
> 我知道在这个基础上就多执行了一条cp命令

:+1: 你开心就好

**Comment by BurgerTown** [comment]
![image](https://user-images.githubusercontent.com/19660419/92087184-cc668100-edfd-11ea-9d6d-b9aaba0bd009.png)
![image](https://user-images.githubusercontent.com/19660419/92087211-d1c3cb80-edfd-11ea-8ebc-e785996f899f.png)
由于5.0使用了sqlite，所以需要php-sqlite的扩展，装上可以了

**Comment by DamonNie** [comment]
是有安装sqlite3扩展的

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BurgerTownLuo <notifications@github.com&gt;
发送时间: 2020年9月3日 15:55
收件人: WangNingkai/OLAINDEX <OLAINDEX@noreply.github.com&gt;
抄送: DamonNie <601696245@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[WangNingkai/OLAINDEX] 5.0安装出现问题 (#322)





 

 
 由于5.0使用了sqlite，所以需要php-sqlite的扩展，装上可以了

**Comment by DamonNie** [comment]
分支：master
环境：编译版本php7.4，扩展已装(包括sqlite3及pdo-sqlite) 注意事项已按照文档操作





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BurgerTownLuo <notifications@github.com&gt;
发送时间: 2020年9月3日 15:55
收件人: WangNingkai/OLAINDEX <OLAINDEX@noreply.github.com&gt;
抄送: DamonNie <601696245@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[WangNingkai/OLAINDEX] 5.0安装出现问题 (#322)





 

 
 由于5.0使用了sqlite，所以需要php-sqlite的扩展，装上可以了
