### ISSUE TITLE
图床不能正常上传图片

### ISSUE THREAD

**Issue by i-Vanbi** [WangNingkai/OLAINDEX#326]
### 1. 该问题的重现步骤是什么？
上传图片失败
图片格式png

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/62582216/91519716-f6afce80-e925-11ea-9737-4f4b68513ffe.png)

**Comment by fxzxmic** [comment]
这个问题好久了，还没修复吗？

**Comment by i-Vanbi** [comment]
已经修复

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rabithua** [comment]
你好，我最近使用发现图床上传小图片可以上传成功，稍微大一点就提示上传失败，其实文件在缓存刷新后已经上传上了。😥
