### ISSUE TITLE
支持世纪互联吗？

### ISSUE THREAD

**Issue by swanchia** [WangNingkai/OLAINDEX#33]
oneindex不支持世纪互联的，这个支持吗

**Comment by luminouskk** [comment]
> 目前不支持

OneIndex V2是可以通过修改支持世纪互联的，hostloc有过实践当然我也在用
https://www.hostloc.com/thread-451084-1-1.html
但是V3的Microsoft Graph接口是无论如何修改都无法认证成功的

**Comment by WangNingkai** [comment]
![image.png](https://i.loli.net/2018/11/08/5be37ecfef063.png) 改一下这里的参数，应该就可以了 @swanchia

**Comment by WangNingkai** [comment]
@swanchia @luminouskk 目前已支持
