### ISSUE TITLE
绑定世纪互联帐号无法使用

### ISSUE THREAD

**Issue by misaka123456** [WangNingkai/OLAINDEX#333]
### 1. 该问题的重现步骤是什么？
5.0安装好后绑定世纪互联
### 2. 你期待的结果是什么？实际看到的又是什么？
绑定成功，并且能在网站打开，绑定国际版帐号没有出现问题，并且能正常显示和使用，但是绑定世纪互联账号时，能绑定成功，但是点击首页会显示错误。报的是这个错：Unable to retrieve user's mysite URL.
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：7.4
- OLAINDEX 版本：
- 浏览器版本：

日志：
SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') at /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
[stacktrace]
#0 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#1 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run()
#2 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select()
#3 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#4 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(608): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#5 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(93): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#6 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(64): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#7 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(541): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#8 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#9 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#10 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#11 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#15 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#16 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#17 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#18 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(56): Illuminate\\Console\\Command->run()
#19 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#20 /www/wwwroot/pan.xiakai.online/app/Console/Commands/InstallCommand.php(92): Illuminate\\Console\\Command->call()
#21 [internal function]: App\\Console\\Commands\\InstallCommand->handle()
#22 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#23 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#27 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#28 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#29 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#30 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#31 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#33 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#34 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#35 /www/wwwroot/pan.xiakai.online/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' at /www/wwwroot/pan.xiakai.online/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)
[stacktrace]
#0 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#1 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(926): call_user_func()
#6 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(961): Illuminate\\Database\\Connection->getPdo()
#7 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->getReadPdo()
#8 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Illuminate\\Database\\Connection->getPdoForSelect()
#9 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#10 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#11 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run()
#12 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select()
#13 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#14 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(608): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#15 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(93): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#16 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(64): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#17 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(541): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#18 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#19 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#20 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#21 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#23 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#24 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#25 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#26 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#27 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#28 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(56): Illuminate\\Console\\Command->run()
#29 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#30 /www/wwwroot/pan.xiakai.online/app/Console/Commands/InstallCommand.php(92): Illuminate\\Console\\Command->call()
#31 [internal function]: App\\Console\\Commands\\InstallCommand->handle()
#32 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#33 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#34 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#35 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#36 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#37 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#38 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#39 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#40 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#41 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#42 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#43 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#44 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#45 /www/wwwroot/pan.xiakai.online/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#46 {main}

[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' at /www/wwwroot/pan.xiakai.online/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /www/wwwroot/pan.xiakai.online/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
#1 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#2 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#3 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(926): call_user_func()
#7 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(961): Illuminate\\Database\\Connection->getPdo()
#8 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->getReadPdo()
#9 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Illuminate\\Database\\Connection->getPdoForSelect()
#10 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#11 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#12 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run()
#13 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select()
#14 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#15 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(608): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#16 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(93): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#17 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(64): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#18 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(541): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#19 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#20 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#21 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#22 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#24 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#25 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#26 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#27 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#28 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#29 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(56): Illuminate\\Console\\Command->run()
#30 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#31 /www/wwwroot/pan.xiakai.online/app/Console/Commands/InstallCommand.php(92): Illuminate\\Console\\Command->call()
#32 [internal function]: App\\Console\\Commands\\InstallCommand->handle()
#33 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#34 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#36 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#37 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#38 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#39 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#40 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#41 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#42 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#43 /www/wwwroot/pan.xiakai.online/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#44 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#45 /www/wwwroot/pan.xiakai.online/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#46 /www/wwwroot/pan.xiakai.online/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#47 {main}
"}

**Comment by L1H0n9Jun** [comment]
```R
library(pheatmap)
#创建数据集test测试矩阵
test = matrix(rnorm(200), 20, 10)
test[1:10, seq(1, 10, 2)] = test[1:10, seq(1, 10, 2)] + 3
test[11:20, seq(2, 10, 2)] = test[11:20, seq(2, 10, 2)] + 2
test[15:20, seq(2, 10, 2)] = test[15:20, seq(2, 10, 2)] + 4
colnames(test) = paste("Test", 1:10, sep = "")
rownames(test) = paste("Gene", 1:20, sep = "")
# 用pheatmap函数画热图
pheatmap(test)
```
