### ISSUE TITLE
删除网盘的时候不是删除选中的那个，而是直接从第一个开始删除

### ISSUE THREAD

**Issue by irainerc** [WangNingkai/OLAINDEX#335]
### 1. 该问题的重现步骤是什么？
删除网盘
### 2. 你期待的结果是什么？实际看到的又是什么？
删除网盘的时候不是删除选中的那个，而是直接从第一个开始删除
### 3. 问题出现的环境
后台管理
- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：7.4
- OLAINDEX 版本：5.0
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/tree/6.0
