### ISSUE TITLE
无法下载图片

### ISSUE THREAD

**Issue by imzrme** [WangNingkai/OLAINDEX#336]
### 1. 该问题的重现步骤是什么？
安装绑定网盘后，点击网盘内的图片下载按钮
### 2. 你期待的结果是什么？实际看到的又是什么？
浏览器下载图片，但是调转到[链接](https://disk.mzrme.com/d/a90Ov8DR/q/%E6%B5%8B%E8%AF%95%E5%9B%BE%E7%89%87.png?download=1)就无反应了，文件是可以下载的。也是跳转到文件地址&download=1
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx1.19
- PHP 版本：7.4
- OLAINDEX 版本：5.0
- 浏览器版本：chrome83

[//]: # (如有图片请附上截图)

**Comment by mzrmecom** [comment]
音乐视频都不可以

**Comment by WangNingkai** [comment]
新版暂未发现此问题
