### ISSUE TITLE
oneinstack环境下安装报错

### ISSUE THREAD

**Issue by 138907168** [WangNingkai/OLAINDEX#337]
错误代码：
> php artisan install
PHP Warning:  require(/home/wwwroot/disk.duyuntao.com/vendor/autoload.php): failed to open stream: No such file or directory in /home/wwwroot/disk.duyuntao.com/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/home/wwwroot/disk.duyuntao.com/vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/disk.duyuntao.com/artisan on line 18
Script php artisan install handling the install-app event returned with error code 255

**Comment by WangNingkai** [comment]
需要composer安装依赖 可以看下文档
