### ISSUE TITLE
排序问题

### ISSUE THREAD

**Issue by MingGeGeZhenShuai** [WangNingkai/OLAINDEX#340]
那个读取的文件顺序，如何改成从新到旧

**Comment by YuhaoTang** [comment]
sortBy=-lastModifiedDateTime

**Comment by ShaoPak** [comment]
> 那个读取的文件顺序，如何改成从新到旧

**作者还没给5.0版本加入排序功能，耐心等一等吧**

**Comment by YuhaoTang** [comment]
> > 那个读取的文件顺序，如何改成从新到旧
> 
> **作者还没给5.0版本加入排序功能，耐心等一等吧**

已经有了啊，按照文件名排序确实有问题，但是按照日期排序可以的啊，url结尾加上?sortBy=-lastModifiedDateTime

**Comment by ShaoPak** [comment]
> > > 那个读取的文件顺序，如何改成从新到旧
> > 
> > 
> > **作者还没给5.0版本加入排序功能，耐心等一等吧**
> 
> 已经有了啊，按照文件名排序确实有问题，但是按照日期排序可以的啊，url结尾加上?sortBy=-lastModifiedDateTime

我指的排序是简单的像4.0一样通过点击来排序
