### ISSUE TITLE
首页的样式有点问题

### ISSUE THREAD

**Issue by misaka123456** [WangNingkai/OLAINDEX#342]
![QQ截图20201127215554](https://user-images.githubusercontent.com/38593541/100456519-7868f100-30fb-11eb-96c4-68b25e10fe7b.png)
![QQ截图20201127215604](https://user-images.githubusercontent.com/38593541/100456524-7a32b480-30fb-11eb-95a9-8357cbb9966f.png)

例如设置成sketchy（其它主题同理），首页页面会缺失部分样式，并且光标选中按钮时，不会显示“手”的图标，仍然是编辑的光标的样子，但是在设置页面就是正常

**Comment by WangNingkai** [comment]
由于调整了显示组件，点击整行表格即可跳转
