### ISSUE TITLE
新版主题有点问题

### ISSUE THREAD

**Issue by misaka123456** [WangNingkai/OLAINDEX#343]
以前的

![QQ截图20201127221846](https://user-images.githubusercontent.com/38593541/100458765-42c60700-30ff-11eb-8dc7-7c772eeb9f6e.png)

现在的

![QQ截图20201127221858](https://user-images.githubusercontent.com/38593541/100458768-435e9d80-30ff-11eb-84d1-a117b6739e41.png)

并且现在的鼠标放在连接上不会变成“手”的形状

**Comment by WangNingkai** [comment]
由于调整了显示组件，点击整行表格即可跳转
