### ISSUE TITLE
5.0加密逻辑好像有些问题，期待作者大大的改进

### ISSUE THREAD

**Issue by ShaoPak** [WangNingkai/OLAINDEX#344]
### 1.该问题的重现步骤是什么？

假设：**根目录为A/B，使用5.0版本并加密A目录**

### 2.你期待的结果是什么？实际看到的又是什么？

此时浏览器输入https://xxxxxx/d/xxx/q/A 正常，需要密码才能访问，但是如果别人知道A目录后还有一个目录名为B的话，在浏览器输入https://xxxxxx/d/xxx/q/A/B 后出问题了，**此时无需密码便可访问，会直接绕过A的密码限制**。

虽然B目录还可再单独设置密码，但是访问时一个个输入就太麻烦了，希望作者大大改进一下加密逻辑：访问后面**未加密的目录**需要解密前面已加密的目录，访问后面**已加密的目录**，只需解密本目录即可访问。

可能我的想法还不太缜密，期待作者大大更成熟的改进。

用olaindex时间也不短了，很喜欢，作者大大的功底令人折服，感谢您的开发，期待OLAINDEX越来越好！

**Comment by ShaoPak** [comment]
现在这个项目是不维护了吗？

**Comment by WangNingkai** [comment]
> 现在这个项目是不维护了吗？
重构 WIP
https://github.com/WangNingkai/OLAINDEX/commit/83bb2cb1f90af7dfb5a64be9ffddbd5012d43c23

**Comment by ShaoPak** [comment]
> > 现在这个项目是不维护了吗？
> 
> ### 筹备重构 WIP
> [83bb2cb](https://github.com/WangNingkai/OLAINDEX/commit/83bb2cb1f90af7dfb5a64be9ffddbd5012d43c23)

那就拭目以待大大的6.0了

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/3f7075e76efa54f2c1a3d60bd69505211952e445
