### ISSUE TITLE
ios端下载文件有问题

### ISSUE THREAD

**Issue by ShaoPak** [WangNingkai/OLAINDEX#347]
### 1. 该问题的重现步骤是什么？
测试时android端和win端正常，ios端下载epub、zip和txt等等格式会出错，具体表现为：
1.下载后文件名不全；
2.下载时“文件名”被修改为“download.aspx”，格式正常
3.下载时”文件名+格式“被修改为”download.aspx“，格式后缀被删除。

### 2. 你期待的结果是什么？实际看到的又是什么？
我没有mac，不知道mac端怎么样，但是ios端和iPados端均存在这种问题，而且这种问题也不是所有这种格式的都有，好像和文件名有关，有的存在有的正常。

还有一个问题是：设置显示格式后，实际许多格式都显示不了，比如大一点的txt，所以建议给各种常用文件格式添加缩略图，无法显示时显示缩略图，这样更美观，而有的时候后台设置显示一种文件格式只是为了获取文件永久直链，也并不是显示文件内容。

**Comment by WangNingkai** [comment]
更多功能建议可以到讨论区参与讨论 https://github.com/WangNingkai/OLAINDEX/discussions
