### ISSUE TITLE
菜鸟疑惑：为什么MySQL数据库不写入任何数据

### ISSUE THREAD

**Issue by ShaoPak** [WangNingkai/OLAINDEX#349]
### 1. 该问题的重现步骤是什么？
使用MySQL数据库安装
### 2. 你期待的结果是什么？实际看到的又是什么？
在使用MySQL安装前，我以为数据库会写入后台配置信息以及生成的链接信息，但是实际在使用MySQL数据库安装5.0后，数据库内容一直为空白，这是为什么？程序可以正常用，但是这样的话MySQL数据库有什么意义呢？求解惑

**Comment by WangNingkai** [comment]
首先需要修改 `.env` 文件，修改数据库位mysql，然后清理缓存，执行数据库迁移，插入数据再使用

**Comment by ShaoPak** [comment]
> 首先需要修改 `.env` 文件，修改数据库位mysql，然后清理缓存，执行数据库迁移，插入数据再使用

是新建的网站，之前没有数据库，修改了.env文件，您说的数据库迁移是如何操作呢？请问有教程吗？

**Comment by WangNingkai** [comment]
```
cd web目录
git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
mv tmp/.git . 
rm -rf tmp 
git reset --hard 
composer install -vvv # 这里确保已成功安装 composer ，如果报权限问题，建议给予用户完整权限。
chmod -R 777 storage 
chown -R www:www * # 此处 www 根据服务器具体用户组而定
```
前提已通过上面步骤，使用 `composer` 安装依赖，确保 `storage` 目录有写入权限

1. 复制根目录 `.env.example` 为 `.env`
2. 修改了 `.env` 文件的数据库配置及其它配置
3. 执行 `php artisan key:generate` 生成运行所需配置
4. 执行数据库迁移 `php artisan migrate --seed`
5. 访问网站，设置其它数据

**Comment by ShaoPak** [comment]
> ```
> cd web目录
> git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
> mv tmp/.git . 
> rm -rf tmp 
> git reset --hard 
> composer install -vvv # 这里确保已成功安装 composer ，如果报权限问题，建议给予用户完整权限。
> chmod -R 777 storage 
> chown -R www:www * # 此处 www 根据服务器具体用户组而定
> ```
> 
> 
> 前提已通过上面步骤，使用 `composer` 安装依赖，确保 `storage` 目录有写入权限
> 
> 
> 
> 1. 复制根目录 `.env.example` 为 `.env`
> 
> 2. 修改了 `.env` 文件的数据库配置及其它配置
> 
> 3. 执行 `php artisan key:generate` 生成运行所需配置
> 
> 4. 执行数据库迁移 `php artisan migrate --seed`
> 
> 5. 访问网站，设置其它数据

感谢大佬这么详细的回复，非常感谢👍

**Comment by WangNingkai** [comment]
如有其他疑问可以直接在讨论区里讨论 https://github.com/WangNingkai/OLAINDEX/discussions

**Comment by liuqianqi** [comment]
新建olaindex使用mysql迁移正常，但是旧站，执行数据库迁移没有任何数据迁移到mysql，包括初始数据库表都没有
