### ISSUE TITLE
自带图床貌似有问题啊。markdown里添加不显示。用别的图床就可以

### ISSUE THREAD

**Issue by minitru1014** [WangNingkai/OLAINDEX#35]
自带图床貌似有问题啊。markdown里添加不显示。用别的图床就可以

**Comment by WangNingkai** [comment]
@minitru1014 详细看wiki，我这边图床按照我说的设置没出过错

**Comment by minitru1014** [comment]
@WangNingkai 大佬 看了下wiki，也并没有图床设置的说明 。开启之后没有其他设置了吧？无从下手了

**Comment by minitru1014** [comment]
注释掉了wiki里所说的内容了，依旧不行。

**Comment by WangNingkai** [comment]
@minitru1014 
![image](https://user-images.githubusercontent.com/23030927/48197639-4c9e3580-e391-11e8-8933-99e760ac12f8.png)
