### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by kissaa6** [WangNingkai/OLAINDEX#36]
安装不上呢，提示HTTP ERROR 500怎么解决呢？

**Comment by kissaa6** [comment]
解决了。用的是lnmp1.5。
//在虚拟主机指定的目录里执行
chattr -i .user.ini    //去掉文件保护
rm .user.ini    //删除文件
//注释掉fastcgi.conf文件的最后一行
# fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/";

**Comment by WangNingkai** [comment]
关掉lnmp跨站点目录保护就可以了

**Comment by kissaa6** [comment]
> 关掉lnmp跨站点目录保护就可以了

谢谢 这个问题已经解决了，现在有个新问题，就是点下载图标后跳转到403页面，这个是什么问题呢

**Comment by kissaa6** [comment]
> > 关掉lnmp跨站点目录保护就可以了
> 
> 谢谢 这个问题已经解决了，现在有个新问题，就是点下载图标后跳转到403页面，这个是什么问题呢

这个也解决了，后台关闭防盗链

**Comment by WangNingkai** [comment]
能不能仔细阅读wiki 😂
