### ISSUE TITLE
6.0 版本安装最后一步出现问题

### ISSUE THREAD

**Issue by stcharlesc** [WangNingkai/OLAINDEX#361]
### 1. 该问题的重现步骤是什么？
6.0 版本
执行 `composer install -vvv` 后提示 `database.sqlite` 不存在，手动复制后解决

执行最后一步安装
`composer run install-app` 出现错误
### 2. 你期待的结果是什么？实际看到的又是什么？
提示数据库问题，按照文档里的部署步骤，修改 `.env`文件后仍出现这样的问题 
同样的步骤，5.0版本 修改 `.env` 文件后可以正常部署
```
Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 8 attempt to write a readonly database (SQL: insert into "migrations" ("migration", "batch") values (2014_10_12_000000_create_users_table, 1))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
 ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 
      +37 vendor frames 
  38  app/Console/Commands/InstallCommand.php:92
      Illuminate\Console\Command::call()

      +13 vendor frames 
  52  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script php artisan install handling the install-app event returned with error code 1
```
### 3. 问题出现的环境

- 操作系统版本：Debian 10
- Apache/NGINX 版本：Nginx 1.18.0
- PHP 版本：7.4
- OLAINDEX 版本：6.0

**Comment by WangNingkai** [comment]
报错来看，数据库文件没有写入权限，请确保 `database.sqlite`  文件的写入权限

**Comment by stcharlesc** [comment]
给了完整的权限，但是刚刚发现只要一执行命令，`database.sqlite` 用户组就会变为 `root`，用非 `root`账户也会变成其他的账户

**Comment by baysonfox** [comment]
同上，遇到了相同的错误，但是在用`sudo -u www`执行`composer run install-app`后依然提示无权限，
在执行之前已经确认`database.sqlite`的权限为`777`且所有者为`www`.

**Comment by WangNingkai** [comment]
> 执行 composer install -vvv 后提示 database.sqlite 不存在

https://github.com/WangNingkai/OLAINDEX/commit/b2db4a30d5846738045260e01d46fd44a11f9cfa 此问题已修复

另外需确保 `database.sqlite` 文件的用户权属（www）和读写权限，这里推荐的还是按照教程执行 

```
chmod -R 777 storage 
chown -R www:www *
```
然后再执行 `composer run install-app`

**Comment by stcharlesc** [comment]
感谢大佬解决，`database.sqlite` 文件自动生成后直接就部署成功了。
但是现在访问出现 `500` 错误，提示`No application encryption key has been specified.` 网站目录也更改了，权限也都给了，不知道是不是新的bug。

**Comment by WangNingkai** [comment]
这个一般不会出现，除非 `.env` 文件配置无法修改，如出现此问题的话，手动执行 `php artisan key:generate` 即可

**Comment by stcharlesc** [comment]
已解决，再次感谢大佬耐心解答！
