### ISSUE TITLE
6.0版本文件夹加密问题 

### ISSUE THREAD

**Issue by MYLF** [WangNingkai/OLAINDEX#362]
### 1. 该问题的重现步骤是什么？
6.0版本中,为文件夹设置加密后出现访问错误
### 2. 你期待的结果是什么？实际看到的又是什么？
为根目录( / )设置加密后，即使输入正确密码也不会进入文件列表
为位于根目录下的文件夹设置加密，其中子文件夹未设置加密的情况下，访问子文件夹出现需要密码才能访问，并且输入父文件夹密码无法解密
为非根目录下的文件夹设置加密后，暂未发现上述情况
起始目录设置为 /
### 3. 问题出现的环境

- 操作系统版本：CentOS 7.8
- Apache/NGINX 版本：Nginx 1.16.1
- PHP 版本： 7.4
- OLAINDEX 版本：6.0
- 浏览器版本：Chrome 87.0.4280.88

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
已兼容根目录加密
