### ISSUE TITLE
希望增加文件隐藏/加密功能

### ISSUE THREAD

**Issue by misaka123456** [WangNingkai/OLAINDEX#363]
希望作者大佬在开发6.0的时候添加之前4.0已经有的文件隐藏/加密的功能，以及图片在文件夹目录即可打开（可以通过上一张下一章切换），视频和音乐也希望有类似的功能。
当然只是希望。大佬已经很幸苦了

**Comment by WangNingkai** [comment]
1. 文件加密隐藏功能已存在，账户设置即可
2. 图片等媒体翻页可以纳入考虑

**Comment by misaka123456** [comment]
我还有一个小问题，就是世纪互联的SharePoint配置里面的索引开始目录是指什么？  我设置一些可能的结果都是报500找不到资源

**Comment by WangNingkai** [comment]
`SharePoint` 索引开始目录是根据你的 `SharePoint` 文件目录来设置的，设置空或 `/` 可以展示整个目录的，比如我下面的设置是可以展示 `SharePoint` 目录的，另外开启 `SharePoint` 挂载需要设置后清理缓存生效
![image](https://user-images.githubusercontent.com/23030927/103330836-34705f80-4a9e-11eb-9a10-00fcc39cf9e7.png)

**Comment by misaka123456** [comment]
这样啊，我说怎么不起作用，另外已经创建的账号似乎删不掉
![QQ截图20201230130222](https://user-images.githubusercontent.com/38593541/103331097-47cffa80-4a9f-11eb-97cd-950bf81a2669.png)
第一个是世纪互联OneDrive
下面两个是上面世纪互联账号的两个相同的SharePoint站点（测试上面出现的问题）
但是现在这三个账号均删不掉

**Comment by WangNingkai** [comment]
更新下，然后清理路由缓存 `php artisan route:clear`

**Comment by misaka123456** [comment]
又发现一个小bug，如果文件名包含#，我这里是文件名的第一个字符是#，那么如果点击该文件，则不会跳转（毕竟#是url的保留字），是不是应该将# UrlEncode为%23

**Comment by misaka123456** [comment]
完了，我怎么感觉我一直在挑刺。

文件隐藏功能：目前只能设置第一级文件夹，如果是设置两级文件夹（例如 文件夹1/文件夹11）则文件夹1下的文件夹11仍然可见。
并且隐藏文件夹的话，虽然文件夹不可见，但是如果通过地址直接访问该文件夹，那么文件夹下的目录仍然都可以看到。希望隐藏文件夹应该加密的逻辑一样是指隐藏该文件夹以及内部的所有文件/文件夹都不可见

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/discussions 有什么需求提到这里吧，用空闲时间会考虑
