### ISSUE TITLE
readme.md文件无法正常显示转换为base64编码的图片

### ISSUE THREAD

**Issue by rangerwill** [WangNingkai/OLAINDEX#364]
### 3. 问题出现的环境

- 操作系统版本：CentOS 7
- Apache/NGINX 版本：Nginx 1.18.0
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：84.0.1 (64 位)

[//]: # (如有图片请附上截图)
![图片](https://user-images.githubusercontent.com/19543803/103745913-3eb0d180-503b-11eb-983d-49061af9fd46.png)

**Comment by WangNingkai** [comment]
目前markdown组件暂不支持base64图片显示
