### ISSUE TITLE
6.0版本如何取消搜索功能？

### ISSUE THREAD

**Issue by suyin-long** [WangNingkai/OLAINDEX#365]
### 1. 该问题的重现步骤是什么？
安装6.0版本

### 2. 你期待的结果是什么？实际看到的又是什么？
可以在后台设置是否显示搜索功能；没有这个设置，默认开启了搜索功能

### 3. 问题出现的环境

- 操作系统版本：Windows 10
- Apache/NGINX 版本： 1.18.0
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：Chrome 87.0.4280.88

[//]: # (如有图片请附上截图)
![QQ截图20210111231757](https://user-images.githubusercontent.com/49554285/104200143-41f4f480-5463-11eb-84e3-6ced8b6e07b1.png)
![QQ截图20210111232315](https://user-images.githubusercontent.com/49554285/104200867-19212f00-5464-11eb-8ec7-174795e76039.png)

### 补充说明
我这不知道怎么回事，搜索功能并不能达到想要的效果，就是说网盘里有的文件搜索不出来，不知道是我搜索的关键词不对还是onedrive应用需要给什么权限的原因，所以就想着能不能在后台手动关闭搜索功能，就如同olaindex5.0版本那样。

**Comment by WangNingkai** [comment]
搜索是针对当前目录文件的搜索，非api全局搜索。

**Comment by suyin-long** [comment]
> 搜索是针对当前目录文件的搜索，非api全局搜索。

行吧，那该如何取消这个功能？

**Comment by WangNingkai** [comment]
暂未加入设置隐藏功能 后面会加上

**Comment by WangNingkai** [comment]
@suyin-long https://github.com/WangNingkai/OLAINDEX/commit/694701e8359326643370bfa359778528c460a836
