### ISSUE TITLE
安装时碰到这个错误。。是不是我的PHP版本太高了？

### ISSUE THREAD

**Issue by duanyunlun** [WangNingkai/OLAINDEX#366]
![image](https://user-images.githubusercontent.com/15923235/104334844-ce6be980-552d-11eb-9a85-5066f18c8691.png)

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/104400731-de1b1a80-558d-11eb-86f2-338f7160278f.png)
这里两个两个问题
1.php版本过高
2.未安装fileinfo扩展

**Comment by Orokapei** [comment]
试试
