### ISSUE TITLE
6.0 出现错误日志

### ISSUE THREAD

**Issue by FFTU** [WangNingkai/OLAINDEX#367]
6.0版本 出现错误日志 
![QQ截图20210114140019](https://user-images.githubusercontent.com/27883482/104550981-eac46f00-5670-11eb-8410-e3304d3fa901.png)

**Comment by WangNingkai** [comment]
这是默认的访问资源不存在的报错，非框架报错

**Comment by FFTU** [comment]
那直接无视这个日志就行吗？还是说可以解决这个

**Comment by WangNingkai** [comment]
本身网盘不存在的文件，无视即可
