### ISSUE TITLE
当在线预览docx/pptx/pdf文档时，显示File Not Found。

### ISSUE THREAD

**Issue by Surface0Tension** [WangNingkai/OLAINDEX#369]
###1. 该问题的重现步骤是什么？
打开任意一个docx/pptx/pdf文档就会显示“File Not Found. The URL of the original file is not valid or the document is not publicly accessible. Verify the URL is correct, then contact the document owner.", 但xlsx可正常打开。

###2. 你期待的结果是什么？实际看到的又是什么？
期待正常打开文档，结果显示“File Not Found. The URL of the original file is not valid or the document is not publicly accessible. Verify the URL is correct, then contact the document owner."

###3. 问题出现的环境

- 操作系统版本：Debian 10
- Apache/NGINX 版本：NGINX 1.18.0
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：87.0.4280.141
![image](https://user-images.githubusercontent.com/52021580/104778876-0dfa3600-57b9-11eb-954a-b53988670588.png)
[//]: # (如有图片请附上截图)

**Comment by feiwujia** [comment]
我测试.ppt .pptx .docx是可以正常打开的，但是pdf好像不支持
