### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Yofo-me** [WangNingkai/OLAINDEX#371]
### 1. 该问题的重现步骤是什么？
在网站根目录文件夹下的`pan`文件夹下，执行相关命令
```Shell
sudo -u www-data git clone https://github.com/WangNingkai/OLAINDEX.git tmp 
sudo -u www-data mv tmp/.git . 
sudo -u www-data rm -rf tmp 
sudo -u www-data git reset --hard 
sudo -u www-data composer install -vvv 
sudo -u www-data chmod -R 777 storage 
sudo -u www-data composer run install-app 
```
后出现以下错误:

![image](https://user-images.githubusercontent.com/55388087/104833325-b2bc6680-58d2-11eb-9894-b38b9ab4690e.png)

### 2. 部署环境
- Ubuntu 20.04 LTS
- Apache 2.4.41
- Php 7.4 (相关插件都已经安装)
- Redis
- Mariadb 10

**Comment by WangNingkai** [comment]
是修改了其他配置参数吗，如果设置了redis等配置，参考单独安装方法 https://olaindex.js.org/#/install
