### ISSUE TITLE
明明绑定了账号但是访问时提升404

### ISSUE THREAD

**Issue by Yofo-me** [WangNingkai/OLAINDEX#372]
### 问题

明明绑定了账号但是访问时提升404

![image](https://user-images.githubusercontent.com/55388087/104836105-6f6bf300-58e6-11eb-9d07-38f38bc27c3e.png)

### 环境

- 操作系统版本：ubuntu 20.04 lts
- Apache/NGINX 版本：2.4.41
- PHP 版本：7.4

![image](https://user-images.githubusercontent.com/55388087/104836075-1dc36880-58e6-11eb-980b-54dda9e4da85.png)

**Comment by long1215** [comment]
设为主账号

**Comment by WangNingkai** [comment]
需要将账号设置为主账号
