### ISSUE TITLE
无API的世纪互联可以用吗？

### ISSUE THREAD

**Issue by simplove** [WangNingkai/OLAINDEX#375]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：5.0
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
目前还不支持无api的账号，如果拥有分享权限的话，后续可能会加入支持

**Comment by simplove** [comment]
也没有分享权限，囧Zz......
