### ISSUE TITLE
账号绑定的时候直接跳转到回调地址，且绑定失败

### ISSUE THREAD

**Issue by mctds** [WangNingkai/OLAINDEX#377]
绑定onedrive账号的时候，授权操作玩抽自动跳转到回调页面，并显示“404尚未设置账号！”。登陆后台发现并未绑定成功。请问如何操作？

**Comment by lumaster** [comment]
![image](https://user-images.githubusercontent.com/76263025/145938088-b917eab8-63e2-4202-aa2f-1e98d3375078.png)

https://mydomain/oauth?code=M.R3_BAY.b115c158-bd38-cab4-dceb-d2fa96bf7719&state=ILXciHhH8EnLUsbC

同样问题，可以允许跳转授权账户，但是最后跳回404页面。

已经将www下所有目录777授权

**Comment by lumaster** [comment]
@WangNingkai 

### 1. 该问题的重现步骤是什么？

按步骤绑定账号，一直出现微软授权的步骤，最后允许后跳到《 404
尚未设置账号！》的页面

### 2. 你期待的结果是什么？实际看到的又是什么？

允许授权后应该成功绑定账号

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.20.1
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：Edge 96

[//]: # (如有图片请附上截图)

![image](https://user-images.githubusercontent.com/76263025/145938584-ede4ae4e-2229-43f2-b364-ea268890697d.png)

**Comment by fgc0109** [comment]
@lumaster @mctds 
为啥没有人回复这个问题呢

回调的路径必须是 /callback 
把 oauth 改成 callback 就可以了

**Comment by lumaster** [comment]
> @lumaster @mctds 为啥没有人回复这个问题呢
> 
> 回调的路径必须是 /callback 把 oauth 改成 callback 就可以了

![image](https://user-images.githubusercontent.com/76263025/146673022-2dca472d-3a26-43a8-abcf-6874683835e1.png)

谢谢！！ 改了callback后，但是貌似又出现了新的问题 _**Error requesting access token. 401: HTTP/1.1 401 Unauthorized**_ ，请教下你的正常流程是怎样呢

**Comment by fgc0109** [comment]
> > @lumaster  @mctds为啥没有人回复问题呢
> > 目的的路径必须是/callback 把oauth改成callback就可以了
> 
> ![图片](https://user-images.githubusercontent.com/76263025/146673022-2dca472d-3a26-43a8-abcf-6874683835e1.png)
> 
> 谢谢！ 改了回调之后，看似又出现了新的问题_**请求访问令牌时出错。401: HTTP/1.1 401 Unauthorized**_，请教下你的正常流程是怎样呢

额 ... 令牌没有授权成功啊 我换了之后就正常绑定了
你微软那边改了回调地址吗 ? 或者检查一下你的参数之类的

如果那边没改,还是oauth的话,有个简单的方法
你在olaindex这边还填写 oauth
然后绑定会404
然后你把404那个页面地址的 oauth 改成 callback 刷新以下就能正常绑定了
