### ISSUE TITLE
使用ubuntu2020.04+oneinstack安装OLAINDEX出现错误

### ISSUE THREAD

**Issue by dingpengyu** [WangNingkai/OLAINDEX#378]
### 1. 该问题的重现步骤是什么？
首先使用 oneinstack 从服务器新建虚拟主机
然后克隆最新代码
最后按照安装.md的说明进行操作
### 2. 你期待的结果是什么？实际看到的又是什么？
期待安装成功
但实际出现了错误。
### 3. 问题出现的环境

- 操作系统版本： ubuntu 20.04.1
- /NGINX 版本： nginx version 1.18
- PHP 版本： php8.0.1
- OLAINDEX 版本： 最新6.0分知
- 浏览器版本： Google Chrome 版本 89.0.4389.9开发板

[//]: # (如有图片请附上截图)
![反馈](https://user-images.githubusercontent.com/26911141/105684920-8044e600-5f30-11eb-8c7a-1f96b79eaf04.png)

**Comment by WangNingkai** [comment]
从截图看无法获取详细的安装步骤，提供下具体的安装步骤呢

**Comment by dingpengyu** [comment]
问题已解决。
