### ISSUE TITLE
切换完了世纪互联后要如何绑定账号呢？

### ISSUE THREAD

**Issue by minitru1014** [WangNingkai/OLAINDEX#38]
rt。大佬求助

**Comment by minitru1014** [comment]
切换后。到绑定页面报错500  ，od:reset 后又是国际版的页面了

**Comment by WangNingkai** [comment]
请附上截图（具体操作流程和报错界面）

**Comment by minitru1014** [comment]
![image](https://user-images.githubusercontent.com/28612397/48529147-d176db00-e8cc-11e8-8ad8-a0508f045583.png)
ssh里切换完成后，想进域名就报错了

**Comment by WangNingkai** [comment]
ssh切换报错吗，尝试清理缓存，进入的哪个页面

**Comment by minitru1014** [comment]
ssh显示切换成功，然后到密钥绑定那个页面 也就是域名。就报错了

**Comment by minitru1014** [comment]
对了。请问 od:reset是否就是恢复到国际版
