### ISSUE TITLE
请问，在多帐号的形式下，如何对某个帐号进行加密，而不是文件夹

### ISSUE THREAD

**Issue by aotuitx** [WangNingkai/OLAINDEX#380]
### 2. 你期待的结果是什么？实际看到的又是什么？

请问，在多帐号的形式下，如何对某个帐号进行加密，而不是文件夹

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.18
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：chrome 84

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
目前还没有加入对账号的加密，后续有空可以考虑一下

**Comment by aotuitx** [comment]
> 目前还没有加入对账号的加密，后续有空可以考虑一下

5.0在多帐号的时候，进行文件管理时，在每个帐号那里，会有个对此目录加密，那个功能在6.0里能用么？

**Comment by JohnnyHermes** [comment]
> > 目前还没有加入对账号的加密，后续有空可以考虑一下
> 
> 5.0在多帐号的时候，进行文件管理时，在每个帐号那里，会有个对此目录加密，那个功能在6.0里能用么？

想对某个账号进行加密可以对其根目录进行加密，在对应的帐号里设置即可
在账号设置的加密路径里写/:password

**Comment by aotuitx** [comment]
> > > 目前还没有加入对账号的加密，后续有空可以考虑一下
> > 
> > 
> > 5.0在多帐号的时候，进行文件管理时，在每个帐号那里，会有个对此目录加密，那个功能在6.0里能用么？
> 
> 想对某个账号进行加密可以对其根目录进行加密，在对应的帐号里设置即可
> 在账号设置的加密路径里写/:password

谢谢，我试了一下，设置的密码要输好几次才能打开，啥原因？

**Comment by JohnnyHermes** [comment]
> > > > 目前还没有加入对账号的加密，后续有空可以考虑一下
> > > 
> > > 
> > > 5.0在多帐号的时候，进行文件管理时，在每个帐号那里，会有个对此目录加密，那个功能在6.0里能用么？
> > 
> > 
> > 想对某个账号进行加密可以对其根目录进行加密，在对应的帐号里设置即可
> > 在账号设置的加密路径里写/:password
> 
> 谢谢，我试了一下，设置的密码要输好几次才能打开，啥原因？

这我就不清楚了，我用的mdui主题没有遇到这个问题，或者你可以试试设置别的密码看能否复现
