### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by stcharlesc** [WangNingkai/OLAINDEX#384]
### 1. 该问题的重现步骤是什么？
几个使用中的小问题，不知道是不是个例

### 2. 你期待的结果是什么？实际看到的又是什么？
-  如果不设置主账号，进入网站会报错
- 使用空全局挂载同济世纪互联，提示无权限，删除其他盘后清除缓存，第一个挂载，挂载成功

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by Jack-Roc** [comment]
博主 mac环境可以吗

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/3ed9ac8890637bfa1ca3a3624c7765cef2ce456d
https://github.com/WangNingkai/OLAINDEX/commit/f232b5f65e4e913b996e0ea9d36a899cd2fc682a
