### ISSUE TITLE
错误500，找不到资源

### ISSUE THREAD

**Issue by qcppl5** [WangNingkai/OLAINDEX#385]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx 1.18
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：谷歌浏览器版本 88.0.4324.152

[//]: # (如有图片请附上截图)
![Screenshot_20210207-185340](https://user-images.githubusercontent.com/61025967/107144386-d294f680-6975-11eb-8ba1-96adeb6eff7e.jpg)
日志:
请求MsGraph响应错误 [{"error":{"code":"itemNotFound","message":"The resource could not be found.","innerError":{"date":"2021-02-07T10:47:33","request-id":"c569f232-c6bb-4db0-913e-e34e257e4062","client-request-id":"c569f232-c6bb-4db0-913e-e34e257e4062"}}},{"Date":["Sun, 07 Feb 2021 10:47:32 GMT"],"Content-Type":["application/json"],"Cache-Control":["no-cache"],"Transfer-Encoding":["chunked"],"Strict-Transport-Security":["max-age=31536000"],"request-id":["c569f232-c6bb-4db0-913e-e34e257e4062"],"client-request-id":["c569f232-c6bb-4db0-913e-e34e257e4062"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Korea Central\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"000\",\"RoleInstance\":\"SE1PEPF000007AB\"}}"]}]
求大佬帮我看看怎么解决

**Comment by brucegao77** [comment]
我也有同样的问题，{"error":{"code":"itemNotFound","message":"The resource could not be found."
刚才在 Onedrive 里添加了两个文件夹，只有前台访问这两个文件夹的时候报错，在“控制台-账号管理-文件管理”中可以看到这两个文件夹的内容。其他之前添加的文件夹没有问题，已经清理过了缓存。

**Comment by qcppl5** [comment]
> 我也有同样的问题，{“ error”：{“ code”：“ itemNotFound”，“ message”：“找不到资源。”
> 刚才在Onedrive里添加了两个文件夹，只有前台访问这两个文件夹的时候报错，在“控制台-账号管理-文件管理”中可以看到这两个文件夹的内容。其他之前添加的文件夹没有问题，已经清理过了缓存。
> 
> * 操作系统版本：docker操作系统：trafex / alpine-nginx-php7
> * Apache / NGINX版本：nginx / 1.18.0
> * PHP版本：PHP 7.4.14
> * OLAINDEX版本：6.0
> * 浏览器版本：Chrome 88.0.4324.146（正式版本）（64位）

我把路径兼容模式关了就好了，要不你也试试

**Comment by brucegao77** [comment]
好的，谢谢

**Comment by leavesking** [comment]
> 好的，谢谢

我是把路径兼容打开就好了奇怪
