### ISSUE TITLE
ts 视频文件点击名称后报错 500 [6.0版本]

### ISSUE THREAD

**Issue by GloryBoy239** [WangNingkai/OLAINDEX#386]
### 1. 该问题的重现步骤是什么？
视频ts文件，点击视频名称后，进入下一页，显示：500
Undefined index: content (View: /www/wwwroot/pan.glorycn.org/resources/views/mdui/components/preview/code.blade.php)
（1）更换主题，浏览器、PC or 手机后仍报错。
（2）已在后台 视频 或 流视频 添加了ts文件，不论添加到这两项里哪一项，都会报错。

### 2. 你期待的结果是什么？实际看到的又是什么？
期望：视频ts文件，点击名称后进入下一页展示预览功能、短连接及正常播放。
实际：全页报错，看不到预览、看不到短连接、无法播放。

**Comment by WangNingkai** [comment]
后台设置ts后缀文件预览项目，再测试下，如还不能播放的话则为播放器原因，暂不支持预览

**Comment by GloryBoy239** [comment]
[https://pan.glorycn.org/t/inL0G8](url)
[https://pan.glorycn.org/t/LqnDq5](url)

在后台 显示设置 的  **视频** 或是 **Dash视频** 中添加了 ts，但是均会报错。

报错页标题是：**服务器错误**，具体内容为：
500 | Undefined index: content (View: /www/wwwroot/pan.glorycn.org/resources/views/mdui/components/preview/code.blade.php)

服务器配置：
Nginx 1.18.0
PHP-7.4

**Comment by GloryBoy239** [comment]
另外，后台查看日志，有对应报错记录，截图如下：

![1](https://user-images.githubusercontent.com/68975045/107205291-aee6b480-6a38-11eb-84d5-6ceb742d3670.jpg)
![2](https://user-images.githubusercontent.com/68975045/107205299-b27a3b80-6a38-11eb-90fa-940e497e0293.jpg)
![3](https://user-images.githubusercontent.com/68975045/107205325-b6a65900-6a38-11eb-8759-57427e79c5c7.jpg)
![4](https://user-images.githubusercontent.com/68975045/107205336-b908b300-6a38-11eb-8018-b638b70cf914.jpg)

**Comment by GloryBoy239** [comment]
@WangNingkai 老王，我把5.0又装了1个，在同一个服务器上，5.0版本可以正常播放，没有报错

**Comment by WangNingkai** [comment]
看看是不是其它的预览选项也加入了ts ，这里从报错看的话，预览选项是预览代码了，无法解析
