### ISSUE TITLE
默认主题，文件名无法完全显示 [6.0版本]

### ISSUE THREAD

**Issue by GloryBoy239** [WangNingkai/OLAINDEX#387]
### 1. 该问题的重现步骤是什么？
在默认主题下：
PC端：文件名过长，无法完全显示
手机端：仅可显示文件名前6个汉字或10多个字符

### 2. 你期待的结果是什么？实际看到的又是什么？
期待：能够完全显示文件名称：是否可以通过修改代码，实现名称自动换行，以满足显示。或为保证板式不乱，换行不超过2-3行应该就能满足大部分需求？

请老王指点！

**Comment by GloryBoy239** [comment]
补一张手机浏览效果图，以便说明：

![微信图片_20210208180026](https://user-images.githubusercontent.com/68975045/107204446-a5108180-6a37-11eb-8ff2-d79e0c3f26ff.jpg)

**Comment by WangNingkai** [comment]
目前已优化显示
