### ISSUE TITLE
功能建议：将 OLAINDEX 的 aplayer html5 播放器替换为 video.js 或是 plyr

### ISSUE THREAD

**Issue by xingkong0113** [WangNingkai/OLAINDEX#388]
当前，aplayer html5播放器不支持 accessible，屏幕阅读器操作起来十分不便。
推荐使用[plyr](https://github.com/sampotts/plyr)或[video.js](https://github.com/videojs/video.js/)
### 1. 该问题的重现步骤是什么？
首先打开[demo](https://d.imydd.top/demo.mp3?hash=nGQ1NLXj)测试文件页面。
然后可以看到，播放器窗口的按钮是没有标题的，并且使用屏幕阅读器是无法点机播放的。
### 2. 你期待的结果是什么？实际看到的又是什么？
期待OLAINDEX的音视频播放器可以支持accessible。
实际上现在的aplayer html5播放器是不支持accessible的。
### 3. 问题出现的环境

- 操作系统版本：ubuntu2020.04.2
- Apache/NGINX 版本：nginx1.18.0
- PHP 版本：php7.4
- OLAINDEX 版本：OLAINDEX v6.0最新master branch
- 浏览器版本： google chrome90 开发板
Microsoft Edge90 开发板
Microsoft Edge稳定版

[//]: # (如有图片请附上截图)
![反馈2](https://user-images.githubusercontent.com/26911141/107590848-318f8f80-6c44-11eb-8170-7f0e30b58dd9.png)
ps
最后祝开发者新年快乐，感谢您维护这个项目。

**Comment by dingpengyu** [comment]
新增解决方按[react-player](https://www.npmjs.com/package/react-player)

**Comment by aotuitx** [comment]
> 新增解决方按[react-player](https://www.npmjs.com/package/react-player)

请问你安装上了吗？这个要怎么用啊？有文章么。英文看不太懂。

**Comment by xingkong0113** [comment]
> > 新增解决方按[react-player](https://www.npmjs.com/package/react-player)
> 
> 请问你安装上了吗？这个要怎么用啊？有文章么。英文看不太懂。

这个要开发者处理。
