### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by okatu-loli** [WangNingkai/OLAINDEX#391]
如图
![Screenshot_2021-02-13-13-58-57-777_com android browser](https://user-images.githubusercontent.com/53247097/107845102-b2fb3500-6d9e-11eb-8efd-06726355f795.jpg)
请问我该如何解决?

**Comment by okatu-loli** [comment]
还有安装时的错误代码
![Uploading Screenshot_2021-02-13-16-38-08-596_com.sonelli.juicessh.jpg…]()

**Comment by WangNingkai** [comment]
根据报错信息，未达到php版本要求，看下 [安装文档](https://olaindex.js.org) 调整相应的配置再试下看看
