### ISSUE TITLE
图床上传的图片404

### ISSUE THREAD

**Issue by QiuMone** [WangNingkai/OLAINDEX#393]
### 1. 该问题的重现步骤是什么？
图床上传图片
### 2. 你期待的结果是什么？实际看到的又是什么？
可以正常访问
OLAINDEX提供的链接显示404，onedrive中正常
### 3. 问题出现的环境

- 操作系统版本：win10
- Apache/NGINX 版本：NGINX 1.17
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：chrome

[//]: # (如有图片请附上截图)

![1613969841344](https://user-images.githubusercontent.com/57786879/108665312-9b931900-750f-11eb-9fb4-fd3169f5a419.gif)

**Comment by nut-geek** [comment]
我也遇到了这个情况，这应该是nginx配置的问题。试试注释掉这段配置
```
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log off;
    }
```

**Comment by QiuMone** [comment]
> 我也遇到了这个情况，这应该是nginx配置的问题。试试注释掉这段配置
> 
> ```
> location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
>     {
>         expires      30d;
>         error_log /dev/null;
>         access_log off;
>     }
> ```

感谢，注释掉后就行了
