### ISSUE TITLE
添加账号时的申请问题

### ISSUE THREAD

**Issue by 2523955396** [WangNingkai/OLAINDEX#394]
暂时出现问题
权限不足，无法执行此操作。请让你的管理员允许用户注册应用。
Tue, 23 Feb 2021 12:56:03 GMT | PFWp5 | z/B/v

**Comment by 2523955396** [comment]
![image](https://user-images.githubusercontent.com/44113373/108847447-aa1a2700-761a-11eb-8543-07d4f3e49cc3.png)

**Comment by WangNingkai** [comment]
应该是账号没有开启api权限 目前无法使用
