### ISSUE TITLE
经常性的报500错误，多次刷新又可能正常

### ISSUE THREAD

**Issue by misaka123456** [WangNingkai/OLAINDEX#396]
### 1. 该问题的重现步骤是什么？
一个世纪互联，一个同账号的sp

日志：

error | production | 2021-02-28 15:05:55 | Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Http/Controllers/DriveController.php:107)
-- | -- | -- | --
error | production | 2021-02-28 15:05:53 | Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Http/Controllers/DriveController.php:107)
error | production | 2021-02-28 15:05:43 | Undefined index: value {"exception":"[object] (ErrorException(code: 0): Undefined index: value at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Service/OneDrive.php:441)
error | production | 2021-02-28 15:05:27 | Undefined index: value {"exception":"[object] (ErrorException(code: 0): Undefined index: value at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Service/OneDrive.php:441)
error | production | 2021-02-28 15:05:25 | Undefined index: value {"exception":"[object] (ErrorException(code: 0): Undefined index: value at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Service/OneDrive.php:441)
error | production | 2021-02-28 15:05:19 | Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Http/Controllers/DriveController.php:107)
error | production | 2021-02-28 15:05:17 | Undefined index: value {"exception":"[object] (ErrorException(code: 0): Undefined index: value at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Service/OneDrive.php:441)
error | production | 2021-02-28 15:05:13 | Undefined index: value {"exception":"[object] (ErrorException(code: 0): Undefined index: value at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Service/OneDrive.php:441)
error | production | 2021-02-28 15:05:11 | Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Http/Controllers/DriveController.php:107)
error | production | 2021-02-28 15:05:10 | Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /usr/local/lighthouse/softwares/btpanel/wwwroot/p/app/Http/Controllers/DriveController.php:107

![image](https://user-images.githubusercontent.com/38593541/109410593-d77a2280-79d6-11eb-8f5d-198d5d5a9a06.png)

报错页面
![image](https://user-images.githubusercontent.com/38593541/109410597-e82a9880-79d6-11eb-84b9-0ec9d7460a8a.png)

**Comment by misaka123456** [comment]
刷新缓存后正常，但是过一段时间又有问题，是不是缓存超时时间出错了

**Comment by aotuitx** [comment]
同样日志。。。

**Comment by 662** [comment]
+1

**Comment by misaka123456** [comment]
#397

**Comment by misaka123456** [comment]
点错了
