### ISSUE TITLE
世纪互联访问时报错

### ISSUE THREAD

**Issue by hiCasper** [WangNingkai/OLAINDEX#397]
在访问首页/管理文件时均出错，检查过ClientID和Secret都没有问题，世纪互联的OneDrive也可以正常登陆查看文件。
部分时候还会提示Undefined index: value，似乎是访问Graph API的时候出现了问题。

![](https://i.loli.net/2021/02/28/1sBCyGT7h2NOA4H.png)

**Comment by misaka123456** [comment]
我和你一样，今天刚出现的问题

**Comment by aotuitx** [comment]
估计是大面积发生了吧，我也出了。
