### ISSUE TITLE
世纪互联绑定之后打不开，之前正常的

### ISSUE THREAD

**Issue by YuhaoTang** [WangNingkai/OLAINDEX#398]
### 1. 该问题的重现步骤是什么？
世纪互联绑定之后打不开
### 2. 你期待的结果是什么？实际看到的又是什么？
首页 500 Undefined index: id
### 3. 问题出现的环境

- 操作系统版本：Ubuntu 20.04.1
- Apache/NGINX 版本：Nginx 1.18.0
- PHP 版本：PHP-7.4
- OLAINDEX 版本：6.0
- 浏览器版本：Chrome 88

[//]: # (如有图片请附上截图)

![image](https://user-images.githubusercontent.com/15133354/109582814-ca297900-7b39-11eb-965c-9f35c27c3c7f.png)
![image](https://user-images.githubusercontent.com/15133354/109583007-25f40200-7b3a-11eb-8fa5-a34adcfca1a3.png)

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/cd6dcf657f73f28fc4197db5657a97e39b0b03c4 这个问题之前已经修复
