### ISSUE TITLE
是否可以播放文件夹内所有音频文件,然后外加读取歌词文件(.lrc)

### ISSUE THREAD

**Issue by aikunzhe** [WangNingkai/OLAINDEX#4]
听完一首歌,要去文件列表点击下一首歌,有点繁琐的操作....希望有,emmm

**Comment by WangNingkai** [comment]
这个的话我还没有考虑呢，我有空看一下这方面的知识

**Comment by woytu** [comment]
> 听完一首歌,要去文件列表点击下一首歌,有点繁琐的操作....希望有,emmm

# 大赞，我也想放这些歌，可以自动循环放就好了

![image](https://user-images.githubusercontent.com/30252550/51188074-2ad4a800-1918-11e9-8499-623286580f43.png)
