### ISSUE TITLE
世纪互联绑定

### ISSUE THREAD

**Issue by caly5144** [WangNingkai/OLAINDEX#40]
大佬怎么绑定世纪互联版啊，我在这个网址https://microsoftgraph.chinacloudapi.cn它自动给我跳到国际版了，世纪互联账户无法登陆。

**Comment by caly5144** [comment]
![image](https://user-images.githubusercontent.com/27693473/48658225-032ca500-ea79-11e8-83c2-d07cf5a59ff9.png)
是在这里申请吗？

**Comment by caly5144** [comment]
这次没有报错，但是好像没有绑定成功，没有显示目录文件，空间也全是0

![image](https://user-images.githubusercontent.com/27693473/48658258-d0cf7780-ea79-11e8-8af0-2e9141714f9d.png)

**Comment by WangNingkai** [comment]
对的部分权限应该没有开启啊

**Comment by caly5144** [comment]
搞定了，谢谢！

**Comment by minitru1014** [comment]
@caly5144 大兄弟，权限要怎么设置 能指导一下吗

**Comment by sxxcb** [comment]
> 世纪互联版，需要命令行执行php artisan od：switch转换到cn版（世纪互联版），然后申请世纪互联版client_id和secret，填写再进行绑定
大佬这一步看不懂啊，在哪里执行php命令啊？我安装程序的服务器么？

**Comment by sddxbests** [comment]
执行 php artisan od:switch，提示无yes选项
![Screenshot_2019-04-24-14-47-38-538_com android chrome](https://user-images.githubusercontent.com/49362031/56638294-4b8f6500-66a0-11e9-99c1-6cd2e2309eb6.png)

**Comment by suyin-long** [comment]
这是怎么回事？
https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&filename=error.png&path=%2Fshare%2Ferror.png&filename=error.png
