### ISSUE TITLE
绑定新账号后出现问题 报错500

### ISSUE THREAD

**Issue by nodesire7** [WangNingkai/OLAINDEX#403]
500
Call to a member function getBody() on null

![image](https://user-images.githubusercontent.com/63827263/111015050-e5ba3c80-83e1-11eb-8adc-d0f9fad92e8d.png)

**Comment by nodesire7** [comment]
可以看见主目录 但是子目录点进去就报错

**Comment by huiges** [comment]
我也是，后台不会报500，但是前台老是报500，访问不好就500，一看日志说的是“请求MsGraph网络错误 The HTTP client sent back an invalid response [。。。。。。”

**Comment by WangNingkai** [comment]
访问资源频率过高，导致的网络响应超时

**Comment by nodesire7** [comment]
> 访问资源频率过高，导致的网络响应超时

根本就没有怎么访问。。只是挂载上去就会报 我主盘没事

**Comment by WangNingkai** [comment]
#404 # # # #
