### ISSUE TITLE
OLAINDEX访问老是报500

### ISSUE THREAD

**Issue by huiges** [WangNingkai/OLAINDEX#404]
### 1. 该问题的重现步骤是什么？

正常请求访问文件，老是报500，后台不会报500
### 2. 你期待的结果是什么？实际看到的又是什么？
期待尽快修复
### 3. 问题出现的环境

- 操作系统版本：CentOS 7.9.2009(Py3.7.8) x64
- Apache/NGINX 版本：Nginx -Tengine2.2.4(2.3.2)
- PHP 版本：7.2-7.4
- OLAINDEX 版本：6.0
- 浏览器版本：Chrome 88.0.4324.150 x64

[//]: # (如有图片请附上截图)
![QQ截图20210313171929](https://user-images.githubusercontent.com/56694990/111025626-4bc5b480-8420-11eb-879c-cc334dcbb48f.png)

**Comment by suyin-long** [comment]
我试了下，按照如下图设置会好点：
![1](https://user-images.githubusercontent.com/49554285/111070333-45ad0200-850c-11eb-9cf0-c2c8364b0eea.png)

**Comment by WangNingkai** [comment]
访问资源频率过高，导致的网络响应超时

**Comment by huiges** [comment]
> 我试了下，按照如下图设置会好点：
> ![1](https://user-images.githubusercontent.com/49554285/111070333-45ad0200-850c-11eb-9cf0-c2c8364b0eea.png)

我试了下我的还是不行，后台还是报如图的错误

**Comment by huiges** [comment]
> 访问资源频率过高，导致的网络响应超时

就相当于正常的文件目录去访问文件，还是经常报500

**Comment by WangNingkai** [comment]
具体日志下方 还有个 `Request Graph Error.`  类似 
![image](https://user-images.githubusercontent.com/23030927/111423401-3952c000-872b-11eb-9bbf-7ef1f71f9c41.png)

可以查看微软那边返回的是什么问题，出现429的话就是账号受限制 @huiges

**Comment by huiges** [comment]
> 具体日志下方 还有个 `Request Graph Error.` 类似
> ![image](https://user-images.githubusercontent.com/23030927/111423401-3952c000-872b-11eb-9bbf-7ef1f71f9c41.png)
> 
> 可以查看微软那边返回的是什么问题，出现429的话就是账号受限制 @huiges

![QQ截图20210317160522](https://user-images.githubusercontent.com/56694990/111434523-999d2e00-873a-11eb-9ebd-aafb52cba9c2.png)
我的没出现429而是提示超时啥的

**Comment by huiges** [comment]
> 具体日志下方 还有个 `Request Graph Error.` 类似
> ![image](https://user-images.githubusercontent.com/23030927/111423401-3952c000-872b-11eb-9bbf-7ef1f71f9c41.png)
> 
> 可以查看微软那边返回的是什么问题，出现429的话就是账号受限制 @huiges

这里有一份错误日志你可以看下
[laravel-2021-03-17.log](https://github.com/WangNingkai/OLAINDEX/files/6154679/laravel-2021-03-17.log)

**Comment by WangNingkai** [comment]
这里看应该是访问超时，国际版的账号访问连接确实会存在一些问题，可以调整超时时间和重试次数

**Comment by huiges** [comment]
> 这里看应该是访问超时，国际版的账号访问连接确实会存在一些问题，可以调整超时时间和重试次数
> 
> https://github.com/WangNingkai/OLAINDEX/blob/5abac5e80f5a531d098a48f5700de35aba56af71/app/Service/GraphClient.php#L121
> 
> https://github.com/WangNingkai/OLAINDEX/blob/5abac5e80f5a531d098a48f5700de35aba56af71/app/Service/GraphRequest.php#L217
> 
> https://github.com/WangNingkai/OLAINDEX/blob/5abac5e80f5a531d098a48f5700de35aba56af71/app/Service/GraphRequest.php#L216

![QQ截图20210317162010](https://user-images.githubusercontent.com/56694990/111436201-a9b60d00-873c-11eb-8842-81552f546782.png)
还是报500，我在设置高点

**Comment by huiges** [comment]
> https://github.com/WangNingkai/OLAINDEX/blob/5abac5e80f5a531d098a48f5700de35aba56af71/app/Service/GraphClient.php#L121
> 
> https://github.com/WangNingkai/OLAINDEX/blob/5abac5e80f5a531d098a48f5700de35aba56af71/app/Service/GraphRequest.php#L217
> 
> https://github.com/WangNingkai/OLAINDEX/blob/5abac5e80f5a531d098a48f5700de35aba56af71/app/Service/GraphRequest.php#L216
改成以下就解决了
OLAINDEX/app/Service/GraphClient.php

Line 121 in 5abac5e

 ->setTimeout(10) 
OLAINDEX/app/Service/GraphRequest.php

Line 217 in 5abac5e

 $curl->setConnectTimeout(10); 
OLAINDEX/app/Service/GraphRequest.php

Line 216 in 5abac5e

 $curl->setRetry(5);

**Comment by GloryBoy239** [comment]
我在拉去部署完网站程序后，执行了转Mysql步骤。会不会是这个的影响。我是按你出的那个教程执行的。以前部署6.0的时候没有转数据库。

**Comment by WangNingkai** [comment]
更新到最新版，一般不会再报错500

**Comment by Jacob-god** [comment]
你好，使用docker安装之后，前台各功能正常，进入后台输入完密码，就报错500.在查看上述解决方案之后，依然无法解决。
主机：centos7.9  aarch64架构
docker版本：Docker version 20.10.6, build 370c289
镜像是：https://hub.docker.com/r/80x86/olaindex
以下是错误日志：
[2021-05-31 18:58:35] local.ERROR: Unsupported operand types (View: /app/resources/views/default/layouts/admin.blade.php) (View: /app/resources/views/default/layouts/admin.blade.php) {"exception":"[object] (ErrorException(code: 0): Unsupported operand types (View: /app/resources/views/default/layouts/admin.blade.php) (View: /app/resources/views/default/layouts/admin.blade.php) at /app/app/Helpers/Tool.php:94, ErrorException(code: 0): Unsupported operand types (View: /app/resources/views/default/layouts/admin.blade.php) at /app/app/Helpers/Tool.php:94, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Unsupported operand types at /app/app/Helpers/Tool.php:94)

**Comment by Jacob-god** [comment]
/app/app/Helpers/Tool.php 第94行如下：

    {
        $units = array(' B', ' KB', ' MB', ' GB', ' TB');
        for ($i = 0; $size >= 1024 && $i < 4; $i++) {
            $size /= 1024;
        }

        return @round($size, 2) . $units[$i];
    }

**Comment by twbworld** [comment]
我也出现了类似问题
![image](https://user-images.githubusercontent.com/52546134/188582278-923b0f58-ca14-4d04-9282-4d04a88b38bd.png)

### 调试发现导致500的出处
请求api `https://login.microsoftonline.com/common/oauth2/v2.0/token` 时报错`invalid_grant`如下:
``` json
{
    "errorCode": 400,
    "errorMessage": "HTTP/1.1 400 Bad Request",
    "request": {
        "client_id": "xxx",
        "client_secret": "xxx",
        "redirect_uri": "https://xxx/callback",
        "refresh_token": "xxxx",
        "grant_type": "refresh_token"
    },
    "response": {
        "error": "invalid_grant",
        "error_description": "AADSTS70000: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope.\r\nTrace ID: xxx\r\nCorrelation ID: xxx\r\nTimestamp: 2022-09-02 03:53:09Z",
        "error_codes": [70000],
        "timestamp": "2022-09-02 03:53:09Z",
        "trace_id": "xxx",
        "correlation_id": "xxx",
        "error_uri": "https://login.microsoftonline.com/error?code=70000"
    }
}
```

到[文档](https://docs.microsoft.com/zh-cn/azure/active-directory/develop/v2-oauth2-auth-code-flow)查看这样描述:
![image](https://user-images.githubusercontent.com/52546134/188584071-06f4c7a4-9be5-406f-b2c4-1912d2e8052f.png)

### `Microsoft Azure` 配置: 
1. 设置了`重定向 URI`
2. 也设置api权限, 如图:
  ![image](https://user-images.githubusercontent.com/52546134/188586600-7d9146b5-0cde-4727-b479-9da9a3e5a940.png)


### 出现的原因未知

### 无奈的解决方案: 
出现500, 都需要另开网页,成功登录 `Microsoft Azure`, 就会神奇的解决了,但过段时间就又会重新500错误

# 有大佬能帮助到我吗?彻底解决这个问题
