### ISSUE TITLE
前后台500 网络开小差了，请稍后重试

### ISSUE THREAD

**Issue by GloryBoy239** [WangNingkai/OLAINDEX#405]
### 1. 该问题的重现步骤是什么？
之前部署6.0，反馈给老王移动端标题只能显示4、5个字，不便查阅。老王回复已做优化，直接更新发现没有变化。于是宝塔删除网站（网站、数据库）重新搭建。重建后，成功绑定账号（ADD上原有配置都没变，只是把原密匙删除后重建了一个密匙）。

后台：文件管理，500 网络开小差了，请稍后重试

前台：500 网络开小差了，请稍后重试 

后台已配置好显示信息，且账号的网盘详情、账号详情均能正常识别。

随后，看老王刚刚又更新了代码，于是再次删除网站，全部重建（ADD上仍然是使用原客户ID，密匙删除重建）。问题依旧存在。

同时查看了之前搭建的5.0版本，该网盘文件能正常查看。

另外，尝试了直接通过绑定账号页里的申请，重新申请绑定，同样500。

### 2. 你期待的结果是什么？实际看到的又是什么？
正常查看、管理网盘文件。

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：Nginx 1.18.0
- PHP 版本：PHP-7.4
- OLAINDEX 版本：6.0
- 浏览器版本：Chorme

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
#404 访问500的网络问题可以查看这里进行设置，具体绑定是什么问题？

**Comment by WangNingkai** [comment]
#404

**Comment by GloryBoy239** [comment]
我按照这个里面说的也调整了，还是不行。而且我这个是后台查看网盘文件也是报500，网络开小差了，请稍后重试。跟她们说的好像还不太一样。

我通过两种方式绑定账号：
1.用前段6.0刚出来时搭建时在ADD里手动配置的ID和URL，因为密匙已经变星号，就把密匙删了重建一个密匙。
2.用后台那个申请按钮，直接在线申请新的ID和密匙。

这两种方式结果都是：
1. 前台：500 网络开小差了，请稍后重试
2. 后台：账号 - 文件管理：网络开小差了，请稍后重试
3. 后台：账号 - 网盘详情、账号详情均能正常识别

与此同时，我尝试访问了另一个搭建的5.0版，是正常访问文件的。

也就是说网盘应该是没有问题，没有什么限制。问题应该出在6.0版与授权账号之间。

相关图片：
![1](https://user-images.githubusercontent.com/68975045/111738192-de040780-88bb-11eb-8b00-608be475735c.jpg)
![2](https://user-images.githubusercontent.com/68975045/111738209-e52b1580-88bb-11eb-91e5-19c78b3a87b1.jpg)
![3](https://user-images.githubusercontent.com/68975045/111738218-e8be9c80-88bb-11eb-8622-d4dad6f6e8f0.jpg)
![4](https://user-images.githubusercontent.com/68975045/111738223-ea886000-88bb-11eb-82f5-56ced3cc9f72.jpg)
![5](https://user-images.githubusercontent.com/68975045/111738228-ed835080-88bb-11eb-9561-ab1ba07fbb3d.jpg)

**Comment by GloryBoy239** [comment]
另外，老王，每访问出现一次500，日志就会生成2条信息，我把他们粘贴下来了（_xxxxxxxxxxx_ 是替换的网址部分，其他都是日志原版）：

1、error | production | 2021-03-19 13:57:39
请求参数 {"apiVersion":"v1.0","method":"get","query":"/me/drive/root:/pwndvzra?expand=thumbnails"}

2、error | production | 2021-03-19 13:57:39
请求MsGraph网络错误 The HTTP client sent back an invalid response [{"file":"/www/wwwroot/_xxxxxxxxxxx_/app/Service/GraphClient.php","line":124,"function":"execute","class":"App\\Service\\GraphRequest","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/app/Service/OneDrive.php","line":492,"function":"execute","class":"App\\Service\\GraphClient","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/app/Service/OneDrive.php","line":158,"function":"_request","class":"App\\Service\\OneDrive","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/app/Http/Controllers/DriveController.php","line":99,"function":"fetchItem","class":"App\\Service\\OneDrive","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Cache/Repository.php","line":385,"function":"App\\Http\\Controllers\\{closure}","class":"App\\Http\\Controllers\\DriveController","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php","line":406,"function":"remember","class":"Illuminate\\Cache\\Repository","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php","line":261,"function":"__call","class":"Illuminate\\Cache\\CacheManager","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/app/Http/Controllers/DriveController.php","line":100,"function":"__callStatic","class":"Illuminate\\Support\\Facades\\Facade","type":"::"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Controller.php","line":54,"function":"query","class":"App\\Http\\Controllers\\DriveController","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php","line":45,"function":"callAction","class":"Illuminate\\Routing\\Controller","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Route.php","line":254,"function":"dispatch","class":"Illuminate\\Routing\\ControllerDispatcher","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Route.php","line":197,"function":"runController","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":693,"function":"run","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":128,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php","line":50,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Routing\\Middleware\\SubstituteBindings","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php","line":78,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php","line":49,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\View\\Middleware\\ShareErrorsFromSession","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php","line":121,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php","line":63,"function":"handleStatefulRequest","class":"Illuminate\\Session\\Middleware\\StartSession","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Session\\Middleware\\StartSession","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php","line":37,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php","line":67,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Cookie\\Middleware\\EncryptCookies","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":695,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":670,"function":"runRouteWithinStack","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":636,"function":"runRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":625,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":166,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":128,"function":"Illuminate\\Foundation\\Http\\{closure}","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php","line":60,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Barryvdh\\Debugbar\\Middleware\\InjectDebugbar","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php","line":27,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php","line":86,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/fideloper/proxy/src/TrustProxies.php","line":57,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":167,"function":"handle","class":"Fideloper\\Proxy\\TrustProxies","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":141,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":110,"function":"sendRequestThroughRouter","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/www/wwwroot/_xxxxxxxxxxx_/public/index.php","line":55,"function":"handle","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"}]

**Comment by GloryBoy239** [comment]
麻烦你帮忙看看！

**Comment by WangNingkai** [comment]
报错信息是三条，还有地下一条英文的 @GloryBoy239  具体看 #404 报错的第三条

**Comment by GloryBoy239** [comment]
1、后台调为：60、60、60
2、下面三个你已经修改成5、5、2了，我调成他们说的10、10、5，具体如下：
OLAINDEX/app/Service/GraphClient.php
 ->setTimeout(10) 
OLAINDEX/app/Service/GraphRequest.php
 $curl->setConnectTimeout(10); 
OLAINDEX/app/Service/GraphRequest.php
 $curl->setRetry(5); 

还是没办法解决！

**Comment by GloryBoy239** [comment]
我在拉取部署完网站程序后，执行了转Mysql步骤。会不会是这个的影响。我是按你的那个教程执行的。上次部署6.0的时候没有转数据库。

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/issues/404#issuecomment-800882878

这张图片的报错是什么？如还是访问超时，看看你服务器链接微软服务器的超时时间大概多少

**Comment by GloryBoy239** [comment]
Request Graph Error. {"errno":22,"message":"HTTP response code said error: The requested URL returned error: 404 Not Found","headers":{"Curl\\CaseInsensitiveArray":[]}}

**Comment by huiges** [comment]
> Request Graph Error. {"errno":22,"message":"HTTP response code said error: The requested URL returned error: 404 Not Found","headers":{"Curl\CaseInsensitiveArray":[]}}

这个问题我也遇到了，但是我的是绑定了两个od账号第一个设置为主账号，前台切换盘符选择第二个账号的内容访问时出现的这个错误，但是主账号的访问不会报错

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/a26885272f584f2558dc39418c6f52f267568368  已调整
