### ISSUE TITLE
切换盘符访问继续报500提示404 Not Found

### ISSUE THREAD

**Issue by huiges** [WangNingkai/OLAINDEX#406]
### 1. 该问题的重现步骤是什么？
绑定了两个od账号第一个设置为主账号，前台切换盘符选择第二个账号的内容访问时报500错误，但是主账号的访问不会报错
错误如下：
Request Graph Error. {"errno":22,"message":"HTTP response code said error: The requested URL returned error: 404 Not Found
","headers":{"Curl\CaseInsensitiveArray":[]}}
### 2. 你期待的结果是什么？实际看到的又是什么？
怎么解决
### 3. 问题出现的环境

- 操作系统版本：CentOS 7.9.2009(Py3.7.8) x64
- Apache/NGINX 版本：Nginx -Tengine2.2.4(2.3.2)
- PHP 版本：7.2-7.4
- OLAINDEX 版本：6.0
- 浏览器版本：Chrome 88.0.4324.150 x64

[//]: # (如有图片请附上截图)
![QQ截图20210319160730](https://user-images.githubusercontent.com/56694990/111749782-398ac100-88cd-11eb-9cc8-c5b64623f053.png)

**Comment by 3chome** [comment]
关闭兼容模式访问可以解决

**Comment by nodesire7** [comment]
> 在基础设置中关闭路径兼容模式访问可以解决

确实有效 副盘可以正常访问了

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/commit/a26885272f584f2558dc39418c6f52f267568368  已调整
