### ISSUE TITLE
HEAD.md 内容无法显示

### ISSUE THREAD

**Issue by 3chome** [WangNingkai/OLAINDEX#408]
### 该问题的重现步骤是什么？

正常安装，使用mdui主题后HEAD.md内容无法显示

### 问题出现的环境

- 操作系统版本：centos 7
- Apache/NGINX 版本：nginx 1.17.10
- PHP 版本：7.4
- OLAINDEX 版本：v6.0 a268852
- 浏览器版本：Chromium 86.0.4240.198

**Comment by WangNingkai** [comment]
默认mdui主题不带HEAD.md
