### ISSUE TITLE
路径兼容模式开启与关闭颠倒

### ISSUE THREAD

**Issue by 3chome** [WangNingkai/OLAINDEX#409]
###  该问题的重现步骤是什么？

路径兼容模式打开后实际是关闭，关闭实际是打开。

###  问题出现的环境

- 操作系统版本：centos 7
- Apache/NGINX 版本：nginx 1.17.10
- PHP 版本：7.4
- OLAINDEX 版本：v6.0 a268852
- 浏览器版本：Chromium 86.0.4240.198

**Comment by WangNingkai** [comment]
路径兼容模式就是单账号模式，未发现你说的颠倒？？
