### ISSUE TITLE
默认网盘使用不带id的url访问时不显示面包屑导航

### ISSUE THREAD

**Issue by daxiaamu** [WangNingkai/OLAINDEX#410]
### 1. 该问题的重现步骤是什么？
使用https://yun.daxiaamu.com/一加手机官方ROM 这个url访问时，不显示面包屑导航
使用https://yun.daxiaamu.com/d/0X1nxvgO/一加手机官方ROM  访问时，就显示面包屑导航
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
面包屑导航是根据id路径解析的，使用完整url访问才可以显示
