### ISSUE TITLE
建议文件夹也能创建短链

### ISSUE THREAD

**Issue by huiges** [WangNingkai/OLAINDEX#412]
现在是文件可以自己创建短链，但是有时候分享给别人的时候是个文件件，有没有可能文件夹也可以创建短链

**Comment by huiges** [comment]
比如文件的短链是https://xxx.xx/t/abcdef,创建文件夹短链是https://xxx.xx/f/abcdef,而且后台可以自己添加短链

**Comment by WangNingkai** [comment]
目前没有考虑文件夹分享功能，你可以根据提交 `pull request` 完善此功能
