### ISSUE TITLE
之前的问题 后台不断报错 页面报错500

### ISSUE THREAD

**Issue by nodesire7** [WangNingkai/OLAINDEX#413]
[laravel-2021-03-24.log](https://github.com/WangNingkai/OLAINDEX/files/6194759/laravel-2021-03-24.log)

![QQ截图20210324140628](https://user-images.githubusercontent.com/63827263/112263419-3a936800-8caa-11eb-8727-20761c1ab9ff.png)

之前发的更新都改过了 问题没有解决

**Comment by nodesire7** [comment]
![image](https://user-images.githubusercontent.com/63827263/112263521-67e01600-8caa-11eb-923a-cd0255a9792e.png)

**Comment by nodesire7** [comment]
现在路径兼容模式可以正常访问了 但是报错仍然一瞬间就上千条
![QQ截图20210324142441](https://user-images.githubusercontent.com/63827263/112265076-d0c88d80-8cac-11eb-90fd-030d41a00d50.png)

**Comment by huiges** [comment]
你可以参考我这个https://github.com/WangNingkai/OLAINDEX/issues/404

**Comment by nodesire7** [comment]
> 你可以参考我这个#404

试过了 没用 一样的报错

**Comment by nodesire7** [comment]
[laravel-2021-03-25.log](https://github.com/WangNingkai/OLAINDEX/files/6202438/laravel-2021-03-25.log)
持续报错问题 几个解决方法都试过了 都不行。。

**Comment by huiges** [comment]
> [laravel-2021-03-25.log](https://github.com/WangNingkai/OLAINDEX/files/6202438/laravel-2021-03-25.log)
> 持续报错问题 几个解决方法都试过了 都不行。。

调高点如下，试下
OLAINDEX/app/Service/GraphClient.php
 ->setTimeout(10) 
OLAINDEX/app/Service/GraphRequest.php
 $curl->setConnectTimeout(10); 
OLAINDEX/app/Service/GraphRequest.php
 $curl->setRetry(5);

**Comment by nodesire7** [comment]
> > [laravel-2021-03-25.log](https://github.com/WangNingkai/OLAINDEX/files/6202438/laravel-2021-03-25.log)
> > 持续报错问题 几个解决方法都试过了 都不行。。
> 
> 调高点如下，试下
> OLAINDEX/app/Service/GraphClient.php
> ->setTimeout(10)
> OLAINDEX/app/Service/GraphRequest.php
> $curl->setConnectTimeout(10);
> OLAINDEX/app/Service/GraphRequest.php
> $curl->setRetry(5);

一样的 就是报错的速度变慢了些而已

**Comment by huiges** [comment]
我看到你的错误基本上都是404，你是不是没更新OLAINDEX啊，git pull更新一下，之前因为路径兼容的问题导致404现在已经修复了，你可以更新一下然后开启路径兼容试一下

**Comment by WangNingkai** [comment]
看样子是没更新，可能有问题冲突，直接覆盖更新吧 @nodesire7

**Comment by nodesire7** [comment]
> 看样子是没更新，可能有问题冲突，直接覆盖更新吧 @nodesire7

更新过了 还是报错啊

**Comment by liuqianqi** [comment]
> 现在的路径模式可以正常访问了但是会报错一瞬间就上千条
> ![QQ截图20210324142441](https://user-images.githubusercontent.com/63827263/112265076-d0c88d80-8cac-11eb-90fd-030d41a00d50.png)

我也出现了同样的问题，请问你解决了吗
