### ISSUE TITLE
绑定国际版账号401错误

### ISSUE THREAD

**Issue by liuqianqi** [WangNingkai/OLAINDEX#415]
![图片](https://user-images.githubusercontent.com/26353444/112494310-e24d8a80-8dbd-11eb-92f9-fe769c57a18f.png)
仔细核对过好多次，建议出个详细教程

**Comment by rumosky** [comment]
我也出现了相同的问题，我的账号是自己教育邮箱注册的1T账号，登录网页版或者客户端都没问题，但是绑定账号最后一步就会出现一楼的那个图，显示401，之后再次尝试绑定，又出现了下图：
![QQ截图20210405130156](https://user-images.githubusercontent.com/41993388/113539083-7cf46780-960f-11eb-9e6d-f2bad35c663d.png)

返回首页之后，显示404|账号不存在

可是我账号是正常的啊

**Comment by liuqianqi** [comment]
教程不全，已解决了

**Comment by realbbits** [comment]
> 
> 
> 教程不全，已解决了

大佬，是哪一步要注意？也遇到绑定报401了

**Comment by liuqianqi** [comment]
tg：@tf189

**Comment by rumosky** [comment]
教程：https://rumosky.com/archives/586

**Comment by rumosky** [comment]
> > 
> > 
> > 教程不全，已解决了
> 
> 大佬，是哪一步要注意？也遇到绑定报401了

教程地址https://rumosky.com/archives/586
