### ISSUE TITLE
我也出现了相同的问题，我的账号是自己教育邮箱注册的1T账号，登录网页版或者客户端都没问题，但是绑定账号最后一步就会出现一楼的那个图，显示401，之后再次尝试绑定，又出现了下图：

### ISSUE THREAD

**Issue by liuqianqi** [WangNingkai/OLAINDEX#421]
我也出现了相同的问题，我的账号是自己教育邮箱注册的1T账号，登录网页版或者客户端都没问题，但是绑定账号最后一步就会出现一楼的那个图，显示401，之后再次尝试绑定，又出现了下图：
![QQ截图20210405130156](https://user-images.githubusercontent.com/41993388/113539083-7cf46780-960f-11eb-9e6d-f2bad35c663d.png)

返回首页之后，显示404|账号不存在

可是我账号是正常的啊

_Originally posted by @rumosky in https://github.com/WangNingkai/OLAINDEX/issues/415#issuecomment-813184775_

**Comment by liuqianqi** [comment]
已经解决了，教程不全而已

**Comment by rumosky** [comment]
> 已经解决了，教程不全而已

可以发一下教程吗？？？感激不尽啊

**Comment by liuqianqi** [comment]
> 
> 
> > 已经解决了，教程不全而已
> 
> 可以发一下教程吗？？？感激不尽啊

没教程哦，可以远程帮你看看tg：@tf189

**Comment by rumosky** [comment]
教程地址https://rumosky.com/archives/586
