### ISSUE TITLE
希望可以加入下载整个文件夹的功能

### ISSUE THREAD

**Issue by IsaacWangTT** [WangNingkai/OLAINDEX#426]
如题，希望大佬能够加一个下载整个文件夹的功能，某些文件进入文件夹得一个一个下，有点麻烦

**Comment by IsaacWangTT** [comment]
如果可以的话可以加个批量下载

**Comment by sunnynctu** [comment]
附议，当然现在也可以用IDM批量下载

**Comment by liuqianqi** [comment]
文件夹下载，涉及到打包压缩，你可以去onedreve压缩打包后下载

**Comment by IsaacWangTT** [comment]
> 文件夹下载，涉及到打包压缩，你可以去onedreve压缩打包后下载

那可以加个压缩包预览
