### ISSUE TITLE
最后一步composer run install-app报错

### ISSUE THREAD

**Issue by janshirley** [WangNingkai/OLAINDEX#429]
### 1. 该问题的重现步骤是什么？
composer run install-app
这一步命令的时候

### 2. 你期待的结果是什么？实际看到的又是什么？
实际出现的是
![image](https://user-images.githubusercontent.com/79647385/115979176-010a9100-a5b7-11eb-9d09-b11e43f61ddf.png)

### 3. 问题出现的环境

- 操作系统版本：centos 8
- Apache/NGINX 版本： nginx/1.18.0
- PHP 版本：PHP 7.4.16
- OLAINDEX 版本：6.0
- 浏览器版本：chrome版本 90.0.4430.85（正式版本）

[//]: # (如有图片请附上截图)
前台显示是这样的
![image](https://user-images.githubusercontent.com/79647385/115979222-40d17880-a5b7-11eb-8f19-10400963f5d7.png)
![image](https://user-images.githubusercontent.com/79647385/115979244-5e064700-a5b7-11eb-94be-dc20578fbe49.png)

比较小白，就完全按照教程操作的，看到有一个问题里说是mysql 的问题，但我改了半天也还是这个样子，求教一下大佬啊，谢谢！！！

**Comment by janshirley** [comment]
重装了一遍好了，可能第一次设置有啥问题

**Comment by liuqianqi** [comment]
记得好像composer版本太高问题吧，降级到1.8试试
