### ISSUE TITLE
ios访问加密文件夹问题

### ISSUE THREAD

**Issue by mcnk328** [WangNingkai/OLAINDEX#435]
### 1. 该问题的重现步骤是什么？
这个问题也有看到其他人反馈过，就是ios在访问加密文件夹时输入密码后又会自动跳转到密码验证页面，但是我发现如果访问的加密文件夹名称是非中文的话，则输入密码后可以顺利访问，反之文件夹名称是中文的话则不行，不知道是不是个例。
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx1.20.0
- PHP 版本：7.4.16
- OLAINDEX 版本：v6.0
- 浏览器版本：alook

[//]: # (如有图片请附上截图)

**Comment by wakaka990702** [comment]
我也是这样，中文名字的文件夹输入密码之后无法进入，我还以为是自己搭建步骤出错了
