### ISSUE TITLE
批量下载的格式为：文件名+空格+下载地址，这样子似乎没办法直接导入下载器下载，比如导入到idm就会报错，希望能去掉文件名和空格

### ISSUE THREAD

**Issue by misaka123456** [WangNingkai/OLAINDEX#437]
批量下载的格式为：文件名+空格+下载地址，这样子似乎没办法直接导入下载器下载，比如导入到idm就会报错，希望能去掉文件名和空格

**Comment by misaka123456** [comment]
不对，不是格式的问题，是这个非直连似乎没办法直接导入到idm下载

**Comment by Origin1699** [comment]
复制带名字和空格的链接可以用idm下载
选择左上角任务 - 从剪切板中添加批量下载任务. 
这样就能正确识别下载链接(至少我的idm可以, 版本6.38)

但是链接中带名字跟空格还有一个问题
在导入potplayer网络播放时, potplayer没法正确识别里的链接, 导致添加失败
