### ISSUE TITLE
.password文件怎么隐藏？我这里进入加密文件夹后可以看见这个文件

### ISSUE THREAD

**Issue by qq-admin** [WangNingkai/OLAINDEX#44]
密码文件怎么隐藏？我看演示站的都是看不到的，也没在设置中找到可以选择隐藏的地方。

**Comment by qq-admin** [comment]
好奇怪，现在又看不见了，昨晚上我确信是看得见的

**Comment by qq-admin** [comment]
明白了，必须要把Nginx配置文件中的缓存配置注释，不能像OneIndex那样加伪静态规则来防止404，注释之后密码文件就看不到了

**Comment by qq-admin** [comment]
瓦萨卡？！是因为我登录了管理员的原因么？！乌龙了~~~

**Comment by WangNingkai** [comment]
管理员的话，我这里是索引全部文件的，包括密码

**Comment by qq-admin** [comment]
我发现好像有时候引用的国外的js和css访问不了，能不能换个源？

**Comment by WangNingkai** [comment]
可以手动切换下的，这个源目前还算稳定，问题是谷歌字体，主要考虑到国内的源不全，静态文件缓存本地比较费空间。
