### ISSUE TITLE
调用 Api 接口上传图片 能否支持 uPic 

### ISSUE THREAD

**Issue by eluotao** [WangNingkai/OLAINDEX#442]
### 1. 该问题的重现步骤是什么？
经常用 uPic 上传图片，这是很好用的一个图床集合上传工具
希望可以改成支持这个软件自定义接口上传  目前不知道怎么配置。

这是地址：https://github.com/gee1k/uPic

我是 Mac 电脑
[//]: # (如有图片请附上截图)

**Comment by OysterQAQ** [comment]
+1

**Comment by ShinokawaRaine** [comment]
https://olaindex.js.org/#/api?id=%e4%b8%8a%e4%bc%a0%e5%9b%be%e5%ba%8a

**Comment by OysterQAQ** [comment]
> https://olaindex.js.org/#/api?id=%e4%b8%8a%e4%bc%a0%e5%9b%be%e5%ba%8a

应该过时了，没维护

**Comment by ShinokawaRaine** [comment]
Usage in v6

POST Api URL:
https://domain.name/api/image-upload

Headers:
Authorization: "Bearer {token}"
Content-Type: "multipart/form-data"

Body:
olaindex_img  type:file  [file.img]

Response:
JSON format  data.url: "https://domain.com/t/abcdef"


v6是这样的 v5应该是文档的内容
PS.请善用网络开发工具 模拟https://domain.com/image 图床上传页面的内容

**Comment by ShinokawaRaine** [comment]
@eluotao  @OysterQAQ 

因为我用的是PicGO所以只能按照upic文档里的页面写一下设置方法

Variables:
https://domain.name  <--安装olaindex的域名(指向/public目录)
{token}  <-- 后台设置的"第三方接口token"

API地址:  https://domain.name/api/image-upload
请求方式:  POST
文件字段名:  olaindex_img
扩展字段:  留空
请求头:  点击右侧"其他字段" 添加以下Header字段
| Key | Value |
| :---: | :---: |
| Authorization | Bearer {token} |
URL路径:  ["data", "url"]
域名:  留空
保存路径:  请参考配置教程进行自定义设置
> 保存路径: 文件储存的路径（包括文件夹）。 支持 {year} {month} {day} {hour} {minute} {second} {since_second} {since_millisecond} {random} {filename} {.suffix} 等变量。比如：上传的图片为 uPic.jpg，设定为 “uPic/{filename}{.suffix}”，则会保存到 “uPic/uPic.jpg”。
> 在保存路径输入框后面的是网址后缀: 可以用于自定义图片处理。

**Comment by OysterQAQ** [comment]
非常感谢 稍后我会尝试一下
