### ISSUE TITLE
申请client_id、client_secret时的链接问题

### ISSUE THREAD

**Issue by qq-admin** [WangNingkai/OLAINDEX#46]
在申请client_id、client_secret时，redirect_uri的链接填写框内，默认是自动把域名填好了，但是并没有加前缀https://，申请的那个可能自己还记得加，当按照步骤把client_id和client_secret填好后一般直接就点保存了，这个时候第二个redirect_uri因为有内容很容易就被忽略了， 然后因为没加https://就会被拒绝。
能否自动也把前缀加上呢？

**Comment by WangNingkai** [comment]
默认的域名是你自己安装输入的，网页安装也已经提醒必须https了，你还忘😂 况且你也可以使用https://olaindex.ningkai.wang 进行中转啊
