### ISSUE TITLE
AADSTS50011错误

### ISSUE THREAD

**Issue by zryyyy** [WangNingkai/OLAINDEX#468]
### 1. 该问题的重现步骤是什么？
在按提示的步骤申请完id和secret后点击绑定，在绑定完后微软的网页提示了
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '97448310-5f7c-48b3-9665-99dcfa6eb7c0'.
### 2. 你期待的结果是什么？实际看到的又是什么？
期待的结果是绑定成功
实际看到的AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '97448310-5f7c-48b3-9665-99dcfa6eb7c0'.
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.18.0
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：95.0.1020.53

[//]: # (如有图片请附上截图)
在查完网上资料以后我去azure查了应用id，没有发现错误的情况
但是在应用的地址上是http://localhost:8000我怀疑是这个问题，但是在申请的时候我的域名并没有写这个
我怀疑是应用地址的原因但是不知道怎么样才能改

**Comment by linyaohui-jutainfo** [comment]
我也遇到相同的问题，不知道如何解决，囧哦！

**Comment by zryyyy** [comment]
> 我也遇到相同的问题，不知道如何解决，囧哦！

我后来发现必须要点进去找到创建的应用的id，不是那个快速创建的应用id

**Comment by linyaohui-jutainfo** [comment]
下午我也发现问题了，确实是程序提交的是localhost:8000的反馈地址，这个估计是程序版本的问题，使用设置提交没有办法，只能是收到到Azure里创建程序后手动填写就好了。非常感谢您
