### ISSUE TITLE
图片无法访问及世纪互联绑定问题

### ISSUE THREAD

**Issue by yfzuix** [WangNingkai/OLAINDEX#469]
### 1. 该问题的重现步骤是什么？
世纪互联绑定时提示需要管理员允许，测试在cloureve、oneindex、zfile上没有这个问题
国际版绑定后图片文件无法访问，查看或下周都404

### 2. 你期待的结果是什么？实际看到的又是什么？
世纪互联能正常授权绑定，图片能正常查看和下载

### 3. 问题出现的环境
- 操作系统版本：centos 8.1
- Apache/NGINX 版本：1.18
- PHP 版本：7.4
- OLAINDEX 版本：6.0
- 浏览器版本：chrome 86.0

[//]: # (如有图片请附上截图)

**Comment by fmalee** [comment]
我也碰到同样的问题，是nginx的重写有问题？还是自身的BUG？

**Comment by WangNingkai** [comment]
nginx需配置图片访问rewrite

**Comment by fmalee** [comment]
> nginx需配置图片访问rewrite

嗯，感谢，注释了就好了。
我用的是OneInStack，使用的是默认的Nginx配置。
WordPress站点用的没有问题，感觉附件的重写也正常，也就没注意到了。
