### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by kistonw** [WangNingkai/OLAINDEX#47]
我的首页怎么没有搜索呢 登录后台才有 还有我想让显示的文件名长度再长点 怎么修改呢

**Comment by WangNingkai** [comment]
搜索本来就是管理员才有的，不然你想泄露你的文件吗。文件名的话自动根据你的客户端屏幕而定的，源码全在view里面

**Comment by kistonw** [comment]
好的吧 不知道为什么我播放10G以上的mkv 声音断断续续 画面顿 期待大神越做越好

**Comment by WangNingkai** [comment]
文件应该是太大了，网络不够稳定，你可以尝试一下dash流播放
