### ISSUE TITLE
看介绍是新增短链接模式，请问是怎么转换短链接的？

### ISSUE THREAD

**Issue by ifuncool** [WangNingkai/OLAINDEX#472]
### 1. 该问题的重现步骤是什么？
后台没有看到短链接转换的入口或者操作按钮

### 2. 你期待的结果是什么？实际看到的又是什么？
如何把长链接转换成短链接，方便分享？

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：NGINX 
- PHP 版本：7.3
- OLAINDEX 版本：v6.0
- 浏览器版本：edge最新

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
自动hash链接转换
