### ISSUE TITLE
突然预览不了，日志报错。

### ISSUE THREAD

**Issue by aotuitx** [WangNingkai/OLAINDEX#479]
`Cannot redirect to an empty URL. {"exception":"[object] (InvalidArgumentException(code: 0): Cannot redirect to an empty URL. at /www/wwwroot/www/vendor/symfony/http-foundation/RedirectResponse.php:86)`

所有预览的报错全是这个代码

**Comment by gongjing666** [comment]
我也是，不知道怎么解决
