### ISSUE TITLE
 Error:401:HTTP/1.1 401 Unauthorized;404 Not Found

### ISSUE THREAD

**Issue by Hentai02** [WangNingkai/OLAINDEX#492]
### 1. 该问题的重现步骤是什么？
按步骤申请，最后绑定账号 Error:401:HTTP/1.1 401 Unauthorized，改成/callback出现404 Not Found
### 2. 你期待的结果是什么？实际看到的又是什么？
文件列表，404
### 3. 问题出现的环境
Ubuntu 22.04 LTS
Docker version 20.10.17, build 100c701
- 操作系统版本：
- Apache/NGINX 版本：nginx/1.18.0 (Ubuntu)
- PHP 版本：
- OLAINDEX 版本：6.0 (amd64-latest)
- 浏览器版本：Microsoft Edge 104.0.1293.54 (正式版本) (64 位)

[//]: # (如有图片请附上截图)
![Snipaste_2022-08-14_14-47-10](https://user-images.githubusercontent.com/54672936/184527540-faf23560-7c4c-446c-afd7-61433b84af68.png)
![Snipaste_2022-08-14_14-46-14](https://user-images.githubusercontent.com/54672936/184527544-ff03c3f9-69b5-4f45-9167-da015463eb80.png)
![Snipaste_2022-08-14_15-50-05](https://user-images.githubusercontent.com/54672936/184527565-394e6c1f-58a7-493b-8b8a-0e7696ad4588.png)

**Comment by Hentai02** [comment]
已解决。。。

**Comment by Dage1819** [comment]
> 已解决。。。

怎么解决的？教教我呗
