### ISSUE TITLE
点击任何文件（夹）会在url上添加d/RxV6xDaK

### ISSUE THREAD

**Issue by ahdiua** [WangNingkai/OLAINDEX#494]
### 1. 该问题的重现步骤是什么？
手动安装，绑定账号后在主页点击任何文件夹
### 2. 你期待的结果是什么？实际看到的又是什么？
链接应该是domain/share，实际是domain/d/RxV6xDaK/share，报500 找不到资源
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.12.2
- PHP 版本：7.4
- OLAINDEX 版本：6.1
- 浏览器版本：Any

[//]: # (如有图片请附上截图)

**Comment by SheepChef** [comment]
请尝试打开路径兼容模式。
