### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by a936919** [WangNingkai/OLAINDEX#5]
可不可以增加一个看图模式 增加按钮在看图片可以直接上一张下一张

**Comment by WangNingkai** [comment]
图片已经加入了列表预览，点击小眼睛就可以预览图片

**Comment by a936919** [comment]
增加一个看图按钮 选中以后该文件夹的图片
缩略图 
https://abbeyok.com/2018/09/23/pyone2-0/
就像这个项目一样
