### ISSUE TITLE
安装报错！

### ISSUE THREAD

**Issue by minitru1014** [WangNingkai/OLAINDEX#51]
[Tip] Requirements Check
wget :  ok
git :  ok
nginx :  ok
php :  ok
install.sh: line 59: /usr/local/php/bin/php: No such file or directory
[Error] PHP Version must be more than 7.1.3

宝塔安装的7.2  是不是脚本有问题啊

**Comment by WangNingkai** [comment]
可能php安装路径不一致吧

**Comment by minitru1014** [comment]
换了台小鸡 换了个域名 依旧一样的报错。上个版本的时候没有问题

**Comment by WangNingkai** [comment]
@minitru1014 你到哪一步报错的

**Comment by minitru1014** [comment]
绑定域名后面，报错的。
![image](https://user-images.githubusercontent.com/28612397/49150310-63f49100-f347-11e8-870c-29e6e860bc7f.png)


翻看前面有个这个，不知道是否有问题。
![image](https://user-images.githubusercontent.com/28612397/49150369-956d5c80-f347-11e8-9b7c-f6f3c88c8593.png)

**Comment by minitru1014** [comment]
我用的是你教程里面的那两步 装的chomposer。应该没错吧

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/49153632-44626600-f351-11e8-9e67-9d5982a8199b.png)

还有这里你都混乱了

正常的操作流程是这样的，我这里丝毫没有问题

![image](https://user-images.githubusercontent.com/23030927/49153685-61973480-f351-11e8-932f-6f234defbb00.png)
![image](https://user-images.githubusercontent.com/23030927/49153794-b20e9200-f351-11e8-884a-b724c745e03b.png)

**Comment by WangNingkai** [comment]
还是那句话，你肯定操作出现了问题，建议你仔细检查，我这里不可能确保每个人环境一致

**Comment by WangNingkai** [comment]
我仔细看了下，这个版本上个版本，安装过程代码我都没改。提供bt账号我可以帮你看下的

**Comment by minitru1014** [comment]
刚刚重装了下系统。刚刚发现宝塔自带composer。我又给装了一遍。可能问题出在这。我再试一下

**Comment by minitru1014** [comment]
您好，bt账号发送到imwnk这个邮箱了

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/49190683-5faf8e80-f3ae-11e8-9249-0bab12f585b6.png)
这个文件设置错误

**Comment by WangNingkai** [comment]
这样就ok了
![image](https://user-images.githubusercontent.com/23030927/49190734-8b327900-f3ae-11e8-9ad0-2f073ba7e806.png)

**Comment by onlineyun** [comment]
_这是一个隐形坑。。。_
`[Tip] Requirements Check`
`wget :  ok`
`git :  ok`
`php :  ok `
`install.sh:行59: /usr/local/php/bin/php: 没有那个文件或目录 `
`[Error] PHP Version must be more than 7.1.3`

php 是通过宝塔安装  或者手动安装 只要你的php  路径不是在 ` /usr/local/php/bin/php` 这个  那就修改下 `install.sh` 第52行的代码


### 解决方法  

`    # php_exe_dir="/usr/local/php/bin/php"    `       原有
` php_exe_dir="/www/server/php/72/bin/php" `   修改后  这个取决于你现在的php路径 当然 如果版本不是7.2 + 那可能出现意外`
