### ISSUE TITLE
视频封面404

### ISSUE THREAD

**Issue by caly5144** [WangNingkai/OLAINDEX#52]
大佬，我重新装了一遍新版olaindex，结果所有视频封面都是404，虽然不影响播放吧……但是强迫症看起来不舒服
![image](https://user-images.githubusercontent.com/27693473/49378392-70158f80-f747-11e8-8ef6-4312bef4c12f.png)

另外我用格式工厂把所有flv转成mp4了，但是这种视频播放没有画面只有声音，请问有解决方案吗？

**Comment by WangNingkai** [comment]
首先，视频封面404 是由于接口转过来的缩略图为空，没有封面，返回的默认封面。
其次，无法播放声音，参考问题可能是视频转码格式不正确导致的，正确的视频格式应该是h.264编码。
