### ISSUE TITLE
无法播放包含中文的视频/音乐

### ISSUE THREAD

**Issue by EdisonJwa** [WangNingkai/OLAINDEX#53]
### 1. 该问题的重现步骤是什么？
文件名包含中文/地址包含中文时无法在线播放
### 2. 你期待的结果是什么？实际看到的又是什么？
在播放地址/名称中包含中文的文件时，持续在缓冲，但是不包含中文(纯英文)的文件播放时，没有问题
### 3. 问题出现的环境

- 操作系统版本：**Debian 9**
- Apache/NGINX 版本：**nginx/1.15.6**
- PHP 版本：**PHP 7.2.12**
- OLAINDEX 版本：**latest**
- 浏览器版本：
  - **Chrome 71.0.3578.80 x64**
  - **Safari/iOS 12.1**
  - **Firefox 64**

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
我展示站点就有包含中文路径的视频，连接正常，请检查网络是否通畅
