### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by MMBBao** [WangNingkai/OLAINDEX#55]
请问一下docker hub的项目什么时候更新呢

**Comment by MMBBao** [comment]
> 目前还没有泊坞窗项目

docker hub 有个linux52/olaindex-docker会维护更新吗，或者有没有办法直接更新他的为最新版，因为我看见他的GitHub项目里有您的提交

**Comment by WangNingkai** [comment]
这个项目啊，它是基于我的项目而修改的，好像也很久没更新了

**Comment by MMBBao** [comment]
> 这个项目啊，它是基于我的项目而修改的，好像也很久没更新了

什么时候出docker版本呢？急求啊，vps上应用都是基于docker的。。。

**Comment by WangNingkai** [comment]
我对这个没有研究，不太会，如果你会的可以提个pr，不胜感激.

**Comment by MMBBao** [comment]
> 我对这个没有研究，不太会，如果你会的可以提个PR，不胜感激。

我去看看他的项目，能不能提取Dockerfile

**Comment by MMBBao** [comment]
> 我对这个没有研究，不太会，如果你会的可以提个PR，不胜感激。

“修改.env DB_CONNECTION = sqlite”

请问这个怎么修改呢？没有找到wiki，我现在不能成功build docker

**Comment by WangNingkai** [comment]
这是之前的版本，现在这里不再使用数据库了，可以去掉的。

docker 环境我也不太清楚

**Comment by xczh** [comment]
已增加Docker一键安装方式，完善Docker安装文档，等待作者Review~

> 我对这个没有研究，不太会，如果你会的可以提个pr，不胜感激.

**Comment by WH-2099** [comment]
建议自动化发布 Docker
