### ISSUE TITLE
腾讯云vps搭建脚本提示nginx失败

### ISSUE THREAD

**Issue by daidaideya** [WangNingkai/OLAINDEX#57]
腾讯云vps使用oneinstack搭建 安装脚本提示
[root@VM_0_3_centos]# ./install.sh 
[Tip] Requirements Check
wget :  ok  
git :  ok 
nginx :  failed 

Centos7，nginx+php7.3

**Comment by WangNingkai** [comment]
如果说nginx 已安装请忽略此脚本，按照wiki手动安装就行。此脚本仅供参考
