### ISSUE TITLE
关于加快访问速度的建议

### ISSUE THREAD

**Issue by vcheckzen** [WangNingkai/OLAINDEX#58]
### 1. 该问题的重现步骤是什么？
每个文件夹加载较慢

### 2. 你期待的结果是什么？实际看到的又是什么？
加载速度快一点

### 3. 问题出现的环境

- 操作系统版本：CentOS 7 x64
- Apache/NGINX 版本：nginx 1.14
- PHP 版本：7.2
- OLAINDEX 版本：3.2
- 浏览器版本：Google Chrome 71.0.3578.80

[//]: # (如有图片请附上截图)

希望作者把加快访问速度加入开发需求，本人能想到的是 Redis 和静态化（事先完全生成 html），希望作者考虑一下

**Comment by WangNingkai** [comment]
其实页面有加入文件缓存，需要后台设置缓存时间，然后也可以在后台通过刷新缓存，对页面加载有一定的帮助。
