### ISSUE TITLE
查看 json 后缀文件 500

### ISSUE THREAD

**Issue by vcheckzen** [WangNingkai/OLAINDEX#59]
### 1. 该问题的重现步骤是什么？
查看 json 后缀文件 500 错误
### 2. 你期待的结果是什么？实际看到的又是什么？
正常查看
### 3. 问题出现的环境

- 操作系统版本：CentOS 7 x64
- Apache/NGINX 版本：nginx 0.14
- PHP 版本：7.2
- OLAINDEX 版本：3.2.1
- 浏览器版本：Google Chrome 71.0.3578.80

[//]: # (如有图片请附上截图)

**Comment by vcheckzen** [comment]
> ### 1. 该问题的重现步骤是什么？
> 查看 json 后缀文件 500 错误
> 
> ### 2. 你期待的结果是什么？实际看到的又是什么？
> 正常查看
> 
> ### 3. 问题出现的环境
> * 操作系统版本：
> * Apache/NGINX 版本：nginx 0.14
> * PHP 版本：7.2
> * OLAINDEX 版本：3.2.1
> * 浏览器版本：Google Chrome 71.0.3578.80

发现作者这个文件夹也 500 了
https://dev.ningkai.wang/home/books

**Comment by WangNingkai** [comment]
已修复，json格式的文件解析内容是对象，不方便显示。我这里做了兼容

**Comment by vcheckzen** [comment]
> 已修复，json格式的文件解析内容是对象，不方便显示。我这里做了兼容

已更新测试，发现空格和换行符被删除，内容全部显示在一行。3.2 以及之前版本可以正常显示。

**Comment by WangNingkai** [comment]
你确定3.2 以及之前版本可以正常显示吗，这个内容我没有改过

**Comment by vcheckzen** [comment]
> [53d4c07](https://github.com/WangNingkai/OLAINDEX/commit/53d4c074b15cd379faa01897de7dfb43cd4893b6) 再试下看看

可以正常获取和显示了
