### ISSUE TITLE
后台管理密码是什么。。

### ISSUE THREAD

**Issue by nocease** [WangNingkai/OLAINDEX#60]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
具体问题请查看wiki 中说明，默认密码12345678
发件人: 不停止i<mailto:notifications@github.com>
发送时间: 2018年12月13日 17:44
收件人: WangNingkai/OLAINDEX<mailto:OLAINDEX@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [WangNingkai/OLAINDEX] 后台管理密码是什么。。 (#60)

1. 该问题的重现步骤是什么？
2. 你期待的结果是什么？实际看到的又是什么？
3. 问题出现的环境

  *   操作系统版本：
  *   Apache/NGINX 版本：
  *   PHP 版本：
  *   OLAINDEX 版本：
  *   浏览器版本：

―
