### ISSUE TITLE
绑定账号时提示我们无法完成你的请求

### ISSUE THREAD

**Issue by isecret** [WangNingkai/OLAINDEX#62]
### 1. 该问题的重现步骤是什么？
似乎该问题我在 issues 中没有看见，但是我真的一直重复这一步。

### 2. 你期待的结果是什么？实际看到的又是什么？
在绑定账号的时候出现了：
```
我们无法完成你的请求
Microsoft 帐户遇到技术问题，请稍后再试。
```

然后没有其他消息了，我在 URL 上看到了一些信息：
```
https://login.live.com/err.srf?lc=2052#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=http%253A%252F%252Ffiles.mydomain.me
```

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：nginx/1.14.2
- PHP 版本：7.2.13( NTS )
- OLAINDEX 版本：Newer
- 浏览器版本：Chorme Newer

[//]: # (如有图片请附上截图)

**Comment by isecret** [comment]
似乎是因为申请回调地址的时候失败的原因，提示 signInUrl 无效？

**Comment by WangNingkai** [comment]
确实是这样，可以使用我wiki提供的回调和client账号
