### ISSUE TITLE
关于在 Heroku 部署时 HTTPS 的跳转

### ISSUE THREAD

**Issue by ReiujiUtsuho** [WangNingkai/OLAINDEX#63]
使用 HTTPS 地址访问首页时会跳转至 HTTP 地址的 /home 路径，手动改为 HTTPS 也可正常访问

经调查发现似乎是 Heroku 使用负载均衡导致，解决办法为：
在 `app/Http/Middleware/TrustProxies.php` 中
将 `protected $proxies;` 改为 `protected $proxies = '**';`

经测试，首页可正常跳转
此处改动对其他非 Heroku 环境影响未知，有待测试

参考：[Heroku上のLaravel 5.5でHTTPSを有効にする](https://qiita.com/imfiare/items/51630851fb8b511b69f4)

**Comment by WangNingkai** [comment]
嗯，根据官方文档表面，如果你使用 Amazon AWS 或其他的「云」负载均衡器提供程序，你可能不知道负载均衡器的实际 IP 地址。在这种情况下，你可以使用 ** 来信任所有代理，这使得你可以快速自定义应用程序信任的负载均衡器或代理。不过还是建议只在此种类型的云上进行修改

```
/**
 * 这个应用程序的可信代理列表
 *
 * @var array
 */
protected $proxies = '**';
```

**Comment by wi1dcard** [comment]
https://devcenter.heroku.com/articles/getting-started-with-laravel#trusting-the-load-balancer

https://laravel.com/docs/5.7/requests#configuring-trusted-proxies
