### ISSUE TITLE
404

### ISSUE THREAD

**Issue by MMBBao** [WangNingkai/OLAINDEX#64]
Oneinstack自动安装打开网页报错403是为什么？Nginx？需要怎么操作？

**Comment by WangNingkai** [comment]
报错请仔细参考wiki指南，nginx目录设置错误
![image](https://user-images.githubusercontent.com/23030927/50124561-32b11600-02a0-11e9-96c2-427eac51c8be.png)

**Comment by MMBBao** [comment]
不是脚本自动安装吗...我去看看

**Comment by MMBBao** [comment]
修改root /xxx.com/public 后，依然404

https://i.loli.net/2018/12/18/5c18611c89da7.jpeg

**Comment by WangNingkai** [comment]
你还是没有指定到你存放的目录

**Comment by wi1dcard** [comment]
@MMBBao 丢出来你的 Nginx 配置文件内容、root 目录内容及权限这样才方便大佬们排查...

**Comment by MMBBao** [comment]
搞定了，在虚拟机里跑脚本新建olaindex文件夹了...不是在网站根目录
