### ISSUE TITLE
按照您的步骤用宝塔安装完之后出现 500错误界面，不知道是什么原因

### ISSUE THREAD

**Issue by xrw002** [WangNingkai/OLAINDEX#66]
[2018-12-18 01:32:04] local.ERROR: file_put_contents(/www/wwwroot/cloud_A.phpll.cc/storage/framework/cache/data/df/ba/dfba7aade0868074c2861c98e2a9a92f3178a51b): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/www/wwwroot/cloud_A.phpll.cc/storage/framework/cache/data/df/ba/dfba7aade0868074c2861c98e2a9a92f3178a51b): failed to open stream: No such file or directory at /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/www/wwwroot/cl...', 122, Array)
#1 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/www/wwwroot/cl...', '1545154324a:27:...', 2)
#2 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(65): Illuminate\\Filesystem\\Filesystem->put('/www/wwwroot/cl...', '1545154324a:27:...', true)
#3 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(208): Illuminate\\Cache\\FileStore->put('config', Array, 1440)
#4 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(340): Illuminate\\Cache\\Repository->put('config', Array, 1440)
#5 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(323): Illuminate\\Cache\\Repository->remember('config', 1440, Object(Closure))
#6 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#7 /www/wwwroot/cloud_A.phpll.cc/app/Helpers/Tool.php(298): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#8 /www/wwwroot/cloud_A.phpll.cc/routes/web.php(27): App\\Helpers\\Tool::config('image_home', 0)
#9 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\\Routing\\Router->{closure}()
#10 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(172): Illuminate\\Routing\\Route->runCallable()
#11 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#12 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#34 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#35 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#36 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#37 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#38 /www/wwwroot/cloud_A.phpll.cc/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#56 /www/wwwroot/cloud_A.phpll.cc/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#57 {main}
"}

**Comment by WangNingkai** [comment]
权限啊，没给权限，chown 和chmod

**Comment by xrw002** [comment]
文件夹还是文件

**Comment by WangNingkai** [comment]
[cid:image001.png@01D4971A.A9AC6B20]

**Comment by xrw002** [comment]
`[2018-12-18 01:32:04] local.ERROR: file_put_contents(/www/wwwroot/cloud_A.phpll.cc/storage/framework/cache/data/df/ba/dfba7aade0868074c2861c98e2a9a92f3178a51b): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/www/wwwroot/cloud_A.phpll.cc/storage/framework/cache/data/df/ba/dfba7aade0868074c2861c98e2a9a92f3178a51b): failed to open stream: No such file or directory at /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/www/wwwroot/cl...', 122, Array)
#1 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/www/wwwroot/cl...', '1545154324a:27:...', 2)
#2 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(65): Illuminate\\Filesystem\\Filesystem->put('/www/wwwroot/cl...', '1545154324a:27:...', true)
#3 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(208): Illuminate\\Cache\\FileStore->put('config', Array, 1440)
#4 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(340): Illuminate\\Cache\\Repository->put('config', Array, 1440)
#5 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(323): Illuminate\\Cache\\Repository->remember('config', 1440, Object(Closure))
#6 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#7 /www/wwwroot/cloud_A.phpll.cc/app/Helpers/Tool.php(298): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#8 /www/wwwroot/cloud_A.phpll.cc/routes/web.php(27): App\\Helpers\\Tool::config('image_home', 0)
#9 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\\Routing\\Router->{closure}()
#10 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(172): Illuminate\\Routing\\Route->runCallable()
#11 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#12 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#34 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#35 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#36 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#37 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#38 /www/wwwroot/cloud_A.phpll.cc/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /www/wwwroot/cloud_A.phpll.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#56 /www/wwwroot/cloud_A.phpll.cc/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#57 {main}
"} `

**Comment by WangNingkai** [comment]
请仔细看wiki啊，不看也不按照要求安装。
![image](https://user-images.githubusercontent.com/23030927/50158285-b43f8d00-030e-11e9-8563-95f6790f3913.png)

**Comment by xrw002** [comment]
执行了啊 大佬

**Comment by WangNingkai** [comment]
不可能，明摆了说你目录权限不足，无法写入缓存
![image](https://user-images.githubusercontent.com/23030927/50158561-68d9ae80-030f-11e9-8e9a-197f225abc4f.png)

**Comment by xrw002** [comment]
`
Welcome to Alibaba Cloud Elastic Compute Service !

[root@izj6cgyhphkjpl8recozwpz ~]# /www/wwwroot/cloud_A.phpll.cc
-bash: /www/wwwroot/cloud_A.phpll.cc: Is a directory
[root@izj6cgyhphkjpl8recozwpz ~]# cd /www/wwwroot/cloud_A.phpll.cc
[root@izj6cgyhphkjpl8recozwpz cloud_A.phpll.cc]# chmod -R 755 storage/
[root@izj6cgyhphkjpl8recozwpz cloud_A.phpll.cc]# chown -R www:www *
[root@izj6cgyhphkjpl8recozwpz cloud_A.phpll.cc]# chmod 777 storage/app/config.json
[root@izj6cgyhphkjpl8recozwpz cloud_A.phpll.cc]#

`  是这样吗

**Comment by xrw002** [comment]
我到目录给全部权限看看  谢谢 呵呵

**Comment by WangNingkai** [comment]
权限给足了，就不会有问题的。

**Comment by xrw002** [comment]
谢谢 要给全部权限  谢谢 解决了

**Comment by xrw002** [comment]
要https对吧 大佬

**Comment by WangNingkai** [comment]
对的，需要安装的时候就填写正确的，可以使用我的回调

**Comment by xrw002** [comment]
搞定了 谢谢大佬

**Comment by xrw002** [comment]
大佬回调可用长久用吗

**Comment by xrw002** [comment]
大佬在项目加个捐赠呵呵 毕竟现在开源的不多了
