### ISSUE TITLE
请问一定要用nginx吗

### ISSUE THREAD

**Issue by FFFcat** [WangNingkai/OLAINDEX#67]
我已经把全部东西都装完了…我是用caddy的。但是打开网址的时候没有东西显示，我用oneindex的可以打开…PHP是正常的…

**Comment by WangNingkai** [comment]
可以用Caddy的，只要配置好相关参数。但是推荐nginx

**Comment by FFFcat** [comment]
但是为什么我配置好后打不开网站呢。。请问是不是我的composer没开？该怎么开？我是用脚本搭建的，全部都OK了没有报错，也设置public了。。

**Comment by WangNingkai** [comment]
打不开网站显示什么报错什么呢，Caddy的配置贴出来，composer是php依赖包管理器，你安装没，并且要把依赖安装完毕

**Comment by FFFcat** [comment]
domain:443{
        gzip
	timeouts none
	root /var/www/caddy/olaindex/public
	log /etc/caddy/olaindex.log
    fastcgi / /run/php/php7.2-fpm.sock php {
         ext .php
         split .php
         index index.php
	}
用脚本的时候全部都OK了，运行环境也配置完了。。网页是
该网页无法正常运作，目前无法处理此请求。
HTTP ERROR 500

同样的caddy配置 oneindex可以打开，也是php环境

**Comment by FFFcat** [comment]
![image_2018-12-19_12-14-33](https://user-images.githubusercontent.com/41832582/50198738-dde8ca80-0387-11e9-8fc9-4dea2fd171d3.png)
和这个有关吗？刚刚又重装了

**Comment by WangNingkai** [comment]
composer安装成功了但是，有一个问题就是你的权限没有成功，确保php的对文件和文件夹的操作写入权限
