### ISSUE TITLE
界面能不能改成“方块图”似的效果展示出来？

### ISSUE THREAD

**Issue by asleep2** [WangNingkai/OLAINDEX#7]
然后在网页右边空余的地方做一个“聊天室”？

我发现这一类onedrive项目都是采用这种”目录检索式”的界面。 
我想要更直观、更傻瓜一点的界面。类似这种
![screenshot-slate_hu84ad76af68df9c5d6f0163a2a067b043_560698_750x500_fill_catmullrom_top_2](https://user-images.githubusercontent.com/39230916/46735249-418bb300-ccc8-11e8-9a4e-9c16530e1843.png)

https://themes.gohugo.io/slate/

**Comment by WangNingkai** [comment]
@asleep2 直观的显示，目前没有找到合适的主题，聊天室这个功能我感觉没必要，太多的功能反而没多大用处
