### ISSUE TITLE
文件/文件夹的复制与移动究竟如何实现

### ISSUE THREAD

**Issue by Sherlockwoo** [WangNingkai/OLAINDEX#75]
描述只有一句话一笔带过，后台管理也写的比较含糊，翻了issues没有类似问题
比如我要移动根目录/upload/文件夹下文件到根目录/media/文件夹

后台管理

源地址：
[路径://]/upload/
填写完整 OneDrive 地址
目标地址：
[路径://]/media/
移动文件和离线下载（包括文件名）请填写完整文件地址，创建、删除分享时可不填

这样是否正确？如果有误能否告知正确填写方式

**Comment by WangNingkai** [comment]
移动复制，起始和目标路径从根目录开始，源如包含文件填写完整文件路径，目录路径仅需填写需要移动的目录，填写文件路径无效。

**Comment by Sherlockwoo** [comment]
> 对的。移动复制，起始和目标路径从根目录开始，源如包含文件填写完整文件路径，目录路径仅需填写需要移动的目录，填写文件路径无效。

但是点击提交之后没有操作成功的反馈，然后刷新缓存发现文件没有移动成功。

**Comment by WangNingkai** [comment]
没有报错提示吗，如果有问题的话，会提示的应该

**Comment by Sherlockwoo** [comment]
没有提示，像按钮失效一样按了没反应

**Comment by WangNingkai** [comment]
不应该啊，我今天还试了，没问题的，你更新到最新，确保你填写的都对，源路径填写所在路径和目标路径填写移动的父级目录，还有如果目录里存在了同名的会报错的。

**Comment by Sherlockwoo** [comment]
现在git pull 到最新的就可以了 ！还有一个问题就是目前不支持文件夹下所以文件移到另一个文件夹是吗？

另外，感谢你的作品和耐心的回复！

**Comment by WangNingkai** [comment]
按理说是支持复制移动整个文件夹的，不过我这里没有测试，你可以尝试一下

**Comment by Sherlockwoo** [comment]
比如/home/A/下有xx.mp4 xx.rm xx.mkv 复制到/test/

源地址：/home/A/
目标地址：/test/

成功后得到/test/A/下有xx.mp4 xx.rm xx.mkv 

而不是/test/下有xx.mp4 xx.rm xx.mkv 

每次移动单个文件或文件夹是没有问题的

**Comment by WangNingkai** [comment]
你这个是移动文件夹，而不是移动文件

**Comment by Sherlockwoo** [comment]
我再摸索摸索 再次感谢
