### ISSUE TITLE
加强防盗链功能就好了！

### ISSUE THREAD

**Issue by wuraowo** [WangNingkai/OLAINDEX#77]
如果能加强防盗链就好了
避免被人恶意分享导致API被限制
开启防盗链直接浏览器输入还是可以下载

**Comment by WangNingkai** [comment]
看来你对防盗链有误解啊，防盗链本来就是过滤外链的作用，即防止盗链，过度引用。不是所谓的加了就访问不了的。而如果你想不让浏览器浏览下载、不被过度分享的话，加密目录就可以了。另外防盗链，从应用层面上过滤也不那么容易的，有心之人还是能绕过的，所以应用防盗链的话，建议还是加上在web服务器上的设置为好。
