### ISSUE TITLE
浏览器出现500错误

### ISSUE THREAD

**Issue by BGMjie** [WangNingkai/OLAINDEX#78]
### 1. 该问题的重现步骤是什么？
按照以上教程的所有步骤安装了3遍以上。可是还是不成功
我猜测可能跟ssl和nginx的配置有关
不知道如何配置ssl
希望可以出LNMP环境的教程
### 2. 你期待的结果是什么？实际看到的又是什么？
出现500错误

### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：1.14.1
- PHP 版本：7.2.6
- OLAINDEX 版本：最新版本
- 浏览器版本：chorme最新版本

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/38123875/50494230-ee223900-0a5c-11e9-9786-7c084c244fd8.png)
![image](https://user-images.githubusercontent.com/38123875/50494243-072aea00-0a5d-11e9-9bce-83ea233e9d73.png)

**Comment by WangNingkai** [comment]
请参考wiki 确保  `.env`文件设置正确，如仍有错误，建议贴出，storage/logs 文件下最新的报错日志，以供检查。

**Comment by BGMjie** [comment]
![image](https://user-images.githubusercontent.com/38123875/50498803-a2808700-0a7e-11e9-8751-a62041cd2429.png)
![image](https://user-images.githubusercontent.com/38123875/50498830-dd82ba80-0a7e-11e9-9b69-687f24f9ea01.png)
没有报错日志

**Comment by WangNingkai** [comment]
这么报500不可能没有日志的啊，会不会权限没给足？这样吧，开启debug 。你把 `.env` 文件下的 __APP_DEBUG__ 改为 __true__ 然后执行命令 `php artisan config:cache` 在返回主页面看报错显示内容

**Comment by lonepair** [comment]
我按照BT面板安装教程安装时也出现了这种情况，不过还没再次尝试。另外[演示站点](https://dev.ningkai.wang/home/system/Vagrant)也出现了同样的500错误。

- NGINX版本:1.8
- PHP版本:7.2
- OLAINDEX 版本:最新版本
- 浏览器版本:Chorme最新版本

**Comment by BGMjie** [comment]
![image](https://user-images.githubusercontent.com/38123875/50522848-fc795f00-0b07-11e9-9bd0-b3960ff7a59e.png)
还是重新安装了，还是没有用  浏览器也没有报错

**Comment by WangNingkai** [comment]
你这里，应该是配置不对
