### ISSUE TITLE
自定义版权问题

### ISSUE THREAD

**Issue by m1911** [WangNingkai/OLAINDEX#79]
![bq](https://user-images.githubusercontent.com/10194213/50514079-eacb9380-0ad6-11e9-995c-736861cd49e5.png)
使用了自定义版权 就变成了Made by zbz Made by IMWNK  那这自定义有啥用？

**Comment by WangNingkai** [comment]
自定义是，给个选项让你可以添加自己的信息。底部开发者版权这样影响吗？

**Comment by m1911** [comment]
@WangNingkai  我只是觉得比较影响美观，要么完全把前端你的版权覆盖了留下后台版权  要么这功能其实比较鸡肋

**Comment by WangNingkai** [comment]
@m1911  考虑到一些站点，需要加个外链，所以添加了这个，不是每个人都需要用的

**Comment by m1911** [comment]
@WangNingkai  看到你博客那个 说明 其实可以在开启的时候直接把你的版权在首页给替换了

**Comment by WangNingkai** [comment]
默认都是显示的，不过可以在我的版权前面添加其他信息。我的个人信息不会去掉的
