### ISSUE TITLE
远程文件夹的显示问题解决了没？

### ISSUE THREAD

**Issue by landall** [WangNingkai/OLAINDEX#8]
OneIndex不能正确地读取其他人分享到本人OneDrive并且加到了自己目录树的文件夹，不知道这边解决了么，我目前看是用:/path:/访问的方法访问的是mount前的本地占位符导致的问题。用drive-id和item-id访问就正确了。

**Comment by WangNingkai** [comment]
@landall 这个问题，我还没有遇到，不过确实路径上还有点问题，我多测试点情况来查看问题。

**Comment by landall** [comment]
我看了一眼代码，你用item id好像是可以的，但share过来的文件夹不能用/me/drive开头，要利用那个文件夹信息里的remoteitem项里的drive id和item id，到别人的drive里去访问。目前只有第一级目录好像可能被mount了别人共享的文件夹。

**Comment by WangNingkai** [comment]
@landall 到时候我看一下具体情况，看看能不能兼容这种

**Comment by landall** [comment]
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-sharing-links?view=odsp-graph-online

A remote item provides the information necessary to make a call to the actual item it represents. The remote item is a placeholder in the user's drive for that item, but cannot be accessed like an item in the user's drive. For example, requesting the children collection for a remote item will result in an error from the server.

To enumerate the contents of this shared folder, the remoteItem property is used to construct a request to the shared folder contained in the remote drive.

GET /drives/{drive-id}/items/{item-id}/children
