### ISSUE TITLE
正常播放视频时音量键无法显示，快进后音量键显现

### ISSUE THREAD

**Issue by waahaa** [WangNingkai/OLAINDEX#81]
### 1. 该问题的重现步骤是什么？
           在不快进的状态下播放视频。

### 2. 你期待的结果是什么？实际看到的又是什么？
          期待的结果：音量键正常显现
          实际：音量键无法显示

### 3. 问题出现的环境

- 操作系统版本：服务器端：debian 8；桌面端：win10 1809
- Apache/NGINX 版本：Nginx 1.14
- PHP 版本：7.2
- OLAINDEX 版本：3.2.1
- 浏览器版本：Chrome 71.0.3578.98（64 位）

[//]: # (如有图片请附上截图)
正常播放时：
![p1 -](https://user-images.githubusercontent.com/41323324/50546096-019bf280-0c5d-11e9-9efb-49e9abb5f81b.png)
快进后：
![p2 -](https://user-images.githubusercontent.com/41323324/50546103-1082a500-0c5d-11e9-9c05-3b326661f023.png)

**Comment by waahaa** [comment]
清理缓存后音量键正常显示了

**Comment by WangNingkai** [comment]
这个问题一直存在吗？我目前还没有发现，浏览器的缓存吗还是？

**Comment by waahaa** [comment]
@WangNingkai 最近才注意到的，在后台管理清理的缓存

**Comment by WangNingkai** [comment]
能通过清理缓存结局的话，应该就是缓存的问题，播放器一般不会出现问题的

**Comment by Sherlockwoo** [comment]
应该是和浏览器有关 试了下手机版chrome没有上述情况，但是少了倒数第二个的分享按钮

**Comment by WangNingkai** [comment]
@waahaa 对的也有浏览器不兼容的情况的
