### ISSUE TITLE
PHP7.3版本。安装完毕500

### ISSUE THREAD

**Issue by lovees** [WangNingkai/OLAINDEX#83]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

Configuration cache cleared!
Configuration cached successfully!
Password：[ 12345678 ]

   Symfony\Component\Process\Exception\LogicException  : The Process class relies on proc_open, which is not available on your PHP installation.

  at /www/wwwroot/VentasGsmlante.Net/vendor/symfony/process/Process.php:143
    139|      */
    140|     public function __construct($command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)
    141|     {
    142|         if (!\function_exists('proc_open')) {
  > 143|             throw new LogicException('The Process class relies on proc_open, which is not available on your PHP installation.');
    144|         }
    145| 
    146|         if (!\is_array($command)) {
    147|             @trigger_error(sprintf('Passing a command as string when creating a "%s" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.', __CLASS__), E_USER_DEPRECATED);

  Exception trace:

  1   Symfony\Component\Process\Process::__construct()
      /www/wwwroot/VentasGsmlante.Net/app/Console/Commands/OneDrive/Install.php:80

  2   App\Console\Commands\OneDrive\Install::handle()
      /www/wwwroot/VentasGsmlante.Net/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  Please use the argument -v to see more details.

**Comment by WangNingkai** [comment]
你没有看完wiki吧，上面说明了，要开启函数，你还没开

**Comment by lovees** [comment]
> 你没有看完wiki吧，上面说明了，要开启函数，你还没开

抱歉，函数被我禁用了，现已安装完毕，但我不想挂钩OneDrive可以吗？
使用本地硬盘数据

**Comment by waahaa** [comment]
> 抱歉，函数被我禁用了，现已安装完毕，但我不想挂钩OneDrive可以吗？
> 使用本地硬盘数据
推荐用nextcloud

**Comment by lovees** [comment]
上传的4MB限制在哪修改呢

**Comment by 766** [comment]
> 上传的4MB限制在哪修改呢

![image](https://user-images.githubusercontent.com/6436579/50571468-ad247e80-0de6-11e9-8584-fe10ea2a50f8.png)

**Comment by 766** [comment]
> 你没有看完wiki吧，上面说明了，要开启函数，你还没开

hero 500怎么解决

**Comment by WangNingkai** [comment]
@lovees @766 这个修改的话没有用的，因为这里的上传方式只支持的4m的文件上传的，如果想大文件上传的话，目前还是推荐命令行上传
