### ISSUE TITLE
视频无法播放，F12 报 406 错误

### ISSUE THREAD

**Issue by vcheckzen** [WangNingkai/OLAINDEX#85]
### 1. 该问题的重现步骤是什么？
打开视频
### 2. 你期待的结果是什么？实际看到的又是什么？
可以在线播放。无法播放，报 406 错误
### 3. 问题出现的环境

- 操作系统版本：CentOS 7 x64
- Apache/NGINX 版本：nginx 0.14
- PHP 版本：7.2
- OLAINDEX 版本：3.2.1
- 浏览器版本：Google Chrome 71.0.3578.98

[//]: # (如有图片请附上截图)
发生错误请求的 [链接](https://australiaeast1-mediap.svc.ms/transform/videotranscode?provider=Spo&docId=https%3a%2f%2fonedroptbsteduau-my.sharepoint.com%2f_api%2fv2.0%2fdrives%2fb!ZyWPB3G6-EetswlYu40wymfxwt_DMENCvHVsnO89SKEvQjaMk22FTYhImrbqkbkN%2fitems%2f01TJM4JDOQICY2JTYSEFG2XUZGAYQJDXXH%3ftempauth%3deyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvb25lZHJvcHRic3RlZHVhdS1teS5zaGFyZXBvaW50LmNvbUAxNDY3ZDZhOS1hZjc0LTRmNDUtOGE2NC1jYzg3NzU2Nzg1MWUiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNTQ2NDAzMzYxIiwiZXhwIjoiMTU0NjQyNDk2MSIsImVuZHBvaW50dXJsIjoiZnZPRkJ2b0xzdzRPajRPTTJla08xVTBnRVpIODRWQml5alROSVRaSTM2ND0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE2NyIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTVRsbE1UVmpObVF0TVdRd055MDBZVFk1TFdFeVpUSXRNbUV6TnpjM1pqSTNZekZoIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik1EYzRaakkxTmpjdFltRTNNUzAwTjJZNExXRmtZak10TURrMU9HSmlPR1F6TUdOaCIsImFwcF9kaXNwbGF5bmFtZSI6Ik9MQUlOREVYIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiMGYwNzE3NjUtYjA1Mi00MTRkLWJlMGItZTJhNzU2MGI0YmNmIiwidGlkIjoiMTQ2N2Q2YTktYWY3NC00ZjQ1LThhNjQtY2M4Nzc1Njc4NTFlIiwidXBuIjoiMTAyNDE5QG9ubWljcm9zb2Z0Lm5ldCIsInB1aWQiOiIxMDAzM0ZGRjk0RjY3NjczIiwic2NwIjoiYWxsZmlsZXMud3JpdGUgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGx9.cVN2NzduTVl3dWdJRzVJYURsQVNSMENPdEpkY20xeUNNUGNDTWJrdVQxWT0%26version%3dPublished&format=dash&track=audio&inputFormat=avi&cs=MGYwNzE3NjUtYjA1Mi00MTRkLWJlMGItZTJhNzU2MGI0YmNmfFNQTw&correlationid=19e15c6d-1d07-4a69-a2e2-2a3777f27c1a.0cd9277f-9bbb-46a6-aee7-eaa6c9c7c938&transcodeAhead=0&part=initsegment&quality=audmed)

![](https://i.loli.net/2019/01/02/5c2c3f5c3269f.png)

**Comment by WangNingkai** [comment]
什么格式的视频，部分事情格式的话，接口无法转换

**Comment by vcheckzen** [comment]
> 这里我给出一个方案，你可以下载一个potplayer,复制下载链接到播放器利用本地解码器播放，看一下在线播放是否异常

avi 格式，复制地址到 vlc 可以播放，potplayer 应该也行

**Comment by vcheckzen** [comment]
> > 这里我给出一个方案，你可以下载一个potplayer,复制下载链接到播放器利用本地解码器播放，看一下在线播放是否异常
> 
> avi 格式，复制地址到 vlc 可以播放，potplayer 应该也行

我传了其他格式视频测试，可以加载，但是很卡，播放 1s 停顿 2s；
也测试了别人搭建的 olaindex，同样很卡；
同时测试了别人搭建的 oneindex，可以流畅播放；
因此我猜测是不是 olaindex 所采用的接口有性能问题那?

**Comment by vcheckzen** [comment]
> > > 这里我给出一个方案，你可以下载一个potplayer,复制下载链接到播放器利用本地解码器播放，看一下在线播放是否异常
> > 
> > 
> > avi 格式，复制地址到 vlc 可以播放，potplayer 应该也行
> 
> 已测试其他格式视频，可以加载，但是很卡，播放 1s 停顿 2s；
> 这种情况 olaindex 和 oneindex 同时存在，因此，暂时采纳使用播放器的方法
> 
> [olaindex 测试地址](https://2333m.top/show/%E7%94%B5%E5%BD%B1/%E5%A4%8D%E4%BB%87%E8%80%85%E8%81%94%E7%9B%9F3/rep-avengersinfinitywar.2018.1080p.bluray.x264.mkv)
> [oneindex 测试地址](https://ypw.tw/%E7%94%B5%E5%BD%B1/%E5%A4%8D%E4%BB%87%E8%80%85%E8%81%94%E7%9B%9F3/rep-avengersinfinitywar.2018.1080p.bluray.x264.mkv)

发现用播放器也很卡，只能是 onedrive 的锅了，在线观看无望

**Comment by waahaa** [comment]
@vcheckzen 跟网络状况有关吧，我用PotPlayer播放很顺畅
