### ISSUE TITLE
m3u8 格式视频不能播放吗

### ISSUE THREAD

**Issue by ulifuqiang** [WangNingkai/OLAINDEX#86]
### 1. m3u8视频没法播放吗？

- 操作系统版本：
- Apache/NGINX 版本：1.14.1

- PHP 版本：7.3
- OLAINDEX 版本：3.2.1
- 浏览器版本：谷歌版本 71.0.3578.98（正式版本） （64 位）

[//]: # (如有图片请附上截图)

**Comment by WangNingkai** [comment]
这个确实不支持
