### ISSUE TITLE
目录加密无效？

### ISSUE THREAD

**Issue by ikangi** [WangNingkai/OLAINDEX#87]
首先感谢作者写出这么棒的程序。

根目录是 /web/
如果想对/web/目录下的/test/加密，密码是123123
下面这两种写法都无效
 /test/ 123123
 /web/test/ 123123
正确的写法是？

**Comment by ikangi** [comment]
每次修改都有清理缓存
下面这两种也都试过，无效。。。
/web/test 123123
/test 123123

**Comment by WangNingkai** [comment]
这样表达问题不够清楚的，建议复现你的操作过程，格式写法，并附上截图，否则无法定位你的问题

**Comment by ikangi** [comment]
![2019-1-4 17-49-32](https://user-images.githubusercontent.com/15985353/50682250-376c1d00-1049-11e9-814f-159b42d89ad9.png)

然后就是 提交修改，清理缓存

**Comment by WangNingkai** [comment]
根目录调整的什么

**Comment by ikangi** [comment]
![2019-1-4 19-51-39](https://user-images.githubusercontent.com/15985353/50686926-38597a80-105a-11e9-8336-660f5c36a338.png)

**Comment by ikangi** [comment]
![2019-1-4 19-54-52](https://user-images.githubusercontent.com/15985353/50687004-a0a85c00-105a-11e9-9ea6-c162a8f67f74.png)
这样也无效

**Comment by WangNingkai** [comment]
这样肯定不可以的啊，我不是一开始就说了根目录的 `/web` 这么填写，不要填写多余填写根目录的，这样拼路径就多了

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/50687414-30023f00-105c-11e9-9c0e-5499c0d825ae.png)
我这个就没事，你自己看看问题在哪里

**Comment by ikangi** [comment]
![2019-1-4 20-53-26](https://user-images.githubusercontent.com/15985353/50688974-cf2a3500-1062-11e9-9604-16c480045183.png)
我这样试过的，也不行

**Comment by WangNingkai** [comment]
不可能，那么多都没有问题的，人家这样设置，我这样设置，一点问题没有

**Comment by ikangi** [comment]
我也不知道为什么，就是不行，是不是我服务器环境设置有问题？

**Comment by ikangi** [comment]
我地址发给您，帮忙看一下？

**Comment by WangNingkai** [comment]
站点地址，后台密码邮箱 发给我 我看看呢

**Comment by ikangi** [comment]
好的，谢谢
