### ISSUE TITLE
速度优化建议。

### ISSUE THREAD

**Issue by sanshuifeibing** [WangNingkai/OLAINDEX#88]
### 1. 该问题的重现步骤是什么？
首次加载页面速度非常慢。
### 2. 你期待的结果是什么？实际看到的又是什么？
优化一下加载速度。
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：NGINX 1.15
- PHP 版本：PHP 7.2 
- OLAINDEX 版本：3.2.1
- 浏览器版本：Chrome 63

OneIndex的bug层出不穷，让我不得不寻找同类产品，发现OLAIndex，真心优雅，舒服。
可能做得太好了，暂时没有发现什么bug，以后发现会第一时间提交。

目前的问题应该就是首次加载页面的速度非常慢，这个应该有优化空间。

**Comment by WangNingkai** [comment]
你可以后台预生成缓存，或者命令行手动加下缓存，还可以调理laravel的任务调度

**Comment by sanshuifeibing** [comment]
> 你可以后台预生成缓存，或者命令行手动加下缓存，还可以调理laravel的任务调度

感谢提醒，已设置。
