### ISSUE TITLE
还是关于速度的问题，加载实在是有点慢

### ISSUE THREAD

**Issue by vft9nesd** [WangNingkai/OLAINDEX#89]
1. 关于缓存，如同其他issuse回答的，具体应该怎样手动生成？

1. 基于Laravel框架开发的，所以它是否支持Redis或者Memcache？具体应该怎么配置

**Comment by WangNingkai** [comment]
wiki里已详细说明，请仔细阅读

**Comment by vft9nesd** [comment]
3Q~是我粗心了
