### ISSUE TITLE
请问这个打开原图是什么问题？

### ISSUE THREAD

**Issue by woytu** [WangNingkai/OLAINDEX#91]
## 最新版本点击查看原图

![image](https://user-images.githubusercontent.com/30252550/51191170-d1bc4280-191e-11e9-945c-fae0f46fedae.png)

**Comment by WangNingkai** [comment]
https://github.com/WangNingkai/OLAINDEX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%AA%92%E4%BD%93%E6%96%87%E4%BB%B6%E6%98%BE%E7%A4%BA-404-%E9%97%AE%E9%A2%98 参考wiki文档  可能你后台有什么限制导致图片无法加载

**Comment by woytu** [comment]
在哪里添加`lang="zh-CN"`能全局生效？Chrome浏览器的翻译太烦人了
