### ISSUE TITLE
关于回调地址

### ISSUE THREAD

**Issue by sxxcb** [WangNingkai/OLAINDEX#92]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)
我是用的自带的回调地址，另一个程序的用的自己的，但是感觉用您的回调我调用视频速度很快，用我自己的有点卡，不知道是不是这个原因，想问下大佬回调会不会影响调用视频网速。

**Comment by sxxcb** [comment]
还有缓存问题，后台的缓存可以设置定时刷新么？不刷新会有什么影响么？

**Comment by WangNingkai** [comment]
@sxxcb 没有迹象表明 回调这个会影响到视频网速 可能是你的本地的网速原因
缓存可以设置定时刷新的 你只需要加一条crontab  可以参考Wiki 有设置的

**Comment by sxxcb** [comment]
> @sxxcb没有迹象表明回调这个会影响到视频网速可能是你的本地的网速原因
> 缓存可以设置定时刷新的你只需要加一条crontab可以参考Wiki有设置的

这个缓存不刷新会有什么影响？抱歉，对这方面不是很懂。还有我本地是电信200M，播放视频只有200Kb左右，但是我开启代理（日本位置）就可以达到几Mb。是微软限制了国内IP么？

**Comment by WangNingkai** [comment]
@sxxcb 缓存定时刷新 可以后台缓存目录结构 提升访问速度 一般来说也不会很慢的 取决于微软服务器的位置了 当然肯定不会在国内 所以翻墙当然会快点 不过还有可能网络原因 晚间一般速度都不好
