### ISSUE TITLE
请问是否可以改一个本地网盘的项目？

### ISSUE THREAD

**Issue by woytu** [WangNingkai/OLAINDEX#93]
# 比如这个项目这样https://github.com/ToyoDAdoubi/DirectoryLister

# https://file.woytu.com 这是我基于这个项目搭建的，但是体验相对你这个项目来说还是差点，比如没有后台功能，没有上传功能，没有文件夹加密功能，README.md文档是用的README.html不能用Markdown语法

# 希望您可以把OLAINDEX中的微软API去掉然后做成一个本地项目，不知道这样是否可行？

**Comment by WangNingkai** [comment]
这个是可以做的  有时间可以做个离线版的

**Comment by zhoushanbao1124** [comment]
有同样的需求，麻烦大佬有时间的的话修改一下

**Comment by woytu** [comment]
> 有同样的需求，麻烦大佬有时间的的话修改一下

### 可以临时用用https://github.com/woytu/DirectoryLister

**Comment by qiuye8023** [comment]
装完才知道本项目是显示onedrive文件的一款web软件，之前用的是DirectoryLister， 还以为这个也是本地版的，所以同样希望出本地版的，因为onedrive对于国人来讲还是太难用了。

**Comment by landall** [comment]
> 装完才知道本项目是显示onedrive文件的一款web软件，之前用的是DirectoryLister， 还以为这个也是本地版的，所以同样希望出本地版的，因为onedrive对于国人来讲还是太难用了。

对于国人而言，免费又不删文件的网盘已经不多了。。。。

**Comment by taozitaozi** [comment]
> 这个是可以做的 有时间可以做个离线版的

支持大佬，现在远程连回家里用的h5ai，感觉没这个好看，而且不支持二级文件夹加密。就想要一个好看又较轻量的，nextcloud等等功能有又太多不是我需要的。
