### ISSUE TITLE
请问如何设置网页图标呢？

### ISSUE THREAD

**Issue by sanshuifeibing** [WangNingkai/OLAINDEX#94]
em..不要嫌弃这种白痴问题，拜托。
因为我确实不太懂php，如果是html这种页面的话就还会添加图标，php就无能为力了。
我甚至不知道主页的操作是哪个文件，尝试过在index.php用html语法来添加图标，但报错。

能否告知一下小弟，具体在哪个文件的哪个位置修改？
感谢。

**Comment by WangNingkai** [comment]
网页图标改起来还是比较简单的    覆盖public目录下的favicon.ico就可以了

**Comment by sanshuifeibing** [comment]
> 网页图标改起来还是比较简单的 覆盖public目录下的favicon.ico就可以了

啊，原来这么简单，之前是直接git clone代码，里边没有favicon.ico，所以一直不知道可以直接放pubilic里修改，感谢感谢。

**Comment by 1349422030** [comment]
我现在放了一个ico图标在public目录下，但是还是显示不了网页图标
![image](https://user-images.githubusercontent.com/35253997/54874540-5dbf7e80-4e28-11e9-8a1f-91f8b7a765d0.png)
以前没有图标的时候是404，现在这个地方不报404了，但是类型显示为html，我看了下演示站点
![image](https://user-images.githubusercontent.com/35253997/54874561-91020d80-4e28-11e9-92c4-f953bf8840dc.png)
服务器上的文件看起来是这个样子的
![image](https://user-images.githubusercontent.com/35253997/54874563-ac6d1880-4e28-11e9-9453-0bc9c85cdcf6.png)
