### ISSUE TITLE
世纪互联报错404

### ISSUE THREAD

**Issue by sxxcb** [WangNingkai/OLAINDEX#95]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- PHP 版本：
- OLAINDEX 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

到最后一步绑定登录账户时，返回首页显示：
Get OneDrive source content error. {"errno":22,"msg":"HTTP response code said error: The requested URL returned error: 404 Not Found"}

**Comment by sxxcb** [comment]
还有我绑定最开始有报错错误：Error: 401: HTTP/1.1 401 Unauthorized  不知道什么情况

**Comment by WangNingkai** [comment]
401 授权错误 你的信息填写不正确 无法取得权限

**Comment by sxxcb** [comment]
> 401授权错误你的信息填写不正确无法取得权限

不好意思大佬，刚刚绑定成功了，应该是权限问题，问下大佬，能不能支持绑定多个盘啊，这样一个网盘一个域名好麻烦的..

**Comment by sxxcb** [comment]
> 401授权错误你的信息填写不正确无法取得权限

哎，我刚刚换了个服务器绑定，结果到了最后一步，绑定账号那里卡主了，点绑定转一下就没反应了，正常应该是转到微软登录窗口。不知道是啥原因...这次的服务器系统是Ubuntu18.04.1,用的宝塔以前的是centos7.3用的宝塔

**Comment by WangNingkai** [comment]
@sxxcb 目前不支持多网盘 绑定多个配置比较麻烦  出现问题建议清理缓存在进行绑定
