### ISSUE TITLE
这个是什么问题

### ISSUE THREAD

**Issue by jarodvip** [WangNingkai/OLAINDEX#96]
- Installation request for laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.12, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
    - /etc/php.d/curl.ini
    - /etc/php.d/fileinfo.ini
    - /etc/php.d/json.ini
    - /etc/php.d/phar.ini
    - /etc/php.d/zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /root/olaindex/artisan on line 33

**Comment by WangNingkai** [comment]
@qazwse4541 @jarodvip   看报错 应该都是 composer 依赖安装失败 建议你检查你的php扩展安装完整了没 在进行安装
