### ISSUE TITLE
文件排序

### ISSUE THREAD

**Issue by kedyao** [WangNingkai/OLAINDEX#97]
能否将把文件进行时间排序。默认的文件名称排序能更改吗。

**Comment by WangNingkai** [comment]
@kedyao  排序可以更改的 我这里按照的是默认的排序 可以在源码里根据需要更改排序的

**Comment by WangNingkai** [comment]
@kedyao  已添加 具体方法参考changelog

**Comment by kedyao** [comment]
谢谢作者，程序目录下升级命令 git pull 出错
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

**Comment by WangNingkai** [comment]
这个是git操作 问题 参考常见常见异常处理就可以了

**Comment by kedyao** [comment]
我重新安装了，在后台设置里没看见哪有设置文件夹排序的选项呢

**Comment by WangNingkai** [comment]
你看changelog说明，不是后台，你在链接上加字段就可以了

**Comment by kedyao** [comment]
小白还是等简单的设置吧，谢谢作者耐心解答

**Comment by WangNingkai** [comment]
目前这种方式是最便捷的灵活的

**Comment by kedyao** [comment]
主要是我看不到你说的这些专业词语，在哪个链接加什么字段，安装我都是按照教程一步一步复制粘贴来的，这些真不太懂，非常喜欢您做的程序，但涉及到您说的这些专业上的还有点摸不到头脑，请您见谅

**Comment by chiakge** [comment]
如何永久设置默认排序规则，更改哪个源文件

**Comment by iiivii** [comment]
同问，修改哪个文件可以永久设置默认排序，希望可以设置为根据名称排序的，感觉链接加上字段还是有些麻烦。

**Comment by kongwy** [comment]
目前通过 URL 参数实现的排序实在不太友好，可否考虑一下增加以下选项：

- 在管理界面添加设置项允许选择默认排序；
- 在文件列表页面允许访客通过点选顶部“文件”、“修改日期”、“大小”进行排序方式切换。

**Comment by xdrnz** [comment]
这个程序确实是除了排序不友好，其他都一级棒

**Comment by xiaolugo** [comment]
能否显示文件夹大小，现在好像只能显示文件大小，文件夹都是"-"。

**Comment by jiangjiangflies** [comment]
> 如何永久设置默认排序规则，更改哪个源文件

层主找到哪个源文件了吗？我也想改
