### ISSUE TITLE
我想给aplayer加hls.js 请问怎么做?

### ISSUE THREAD

**Issue by asleep2** [WangNingkai/OLAINDEX#98]
<img src="https://i.loli.net/2019/01/29/5c4fd050b4bd7.png" alt="sasd获.PNG" title="sasd获.PNG" />
并且想再加个alac.js 以支持alac格式音频

**Comment by WangNingkai** [comment]
![image](https://user-images.githubusercontent.com/23030927/51884831-dc1d1880-23c3-11e9-84bc-3c4a46aa4585.png)
此目录修改显示加载音频脚本
