### ISSUE TITLE
期待.password功能

### ISSUE THREAD

**Issue by Zxilly** [WangNingkai/OLAINDEX#99]
Oneindex的这个操作逻辑还是比较直观的

**Comment by WangNingkai** [comment]
@Zxilly 之前有个功能不过就是没办法递归加密，所以改成这个了

**Comment by Zxilly** [comment]
> @Zxilly 之前有个功能不过就是没办法递归加密，所以改成这个了

不需要递归啊，以顶级为准

**Comment by WangNingkai** [comment]
按照顶级的话 如果知道子目录的 就可以通过路径访问 除非再加.password文件或者一级一级判断 这样就比较费事了 @Zxilly

**Comment by Zxilly** [comment]
我应该可以写一个规则转换来解决
先看文档
